import pathlib

content = r'''// Generated by AI (GitHub Copilot) - 2026-06-29
// Local security master for auto-populating identifiers and reference data.
// When the user enters any one of Ticker / CUSIP / ISIN, the other fields fill in.

export interface SecurityMasterEntry {
  ticker: string;            // Bloomberg-style ticker, e.g. "AAPL US"
  cusip: string;
  isin: string;
  name: string;              // Display name
  price: number;             // Last / indicative price
  country: string;           // ISO 2-letter country code
  settlementLocation: string; // DTC | CDS | Fed
}

/** Static list sourced from HOOPP mock order data + common Canadian/US holdings */
export const SECURITY_MASTER: SecurityMasterEntry[] = [
  // US Equities
  { ticker: "AAPL US",  cusip: "037833100", isin: "US0378331005", name: "Apple Inc",              price: 198.11, country: "US", settlementLocation: "DTC" },
  { ticker: "MSFT US",  cusip: "594918104", isin: "US5949181045", name: "Microsoft Corp",         price: 452.35, country: "US", settlementLocation: "DTC" },
  { ticker: "NVDA US",  cusip: "67066G104", isin: "US67066G1040", name: "NVIDIA Corp",            price: 135.58, country: "US", settlementLocation: "DTC" },
  { ticker: "TSLA US",  cusip: "88160R101", isin: "US88160R1014", name: "Tesla Inc",              price: 248.42, country: "US", settlementLocation: "DTC" },
  { ticker: "AMZN US",  cusip: "023135106", isin: "US0231351067", name: "Amazon.com Inc",         price: 205.74, country: "US", settlementLocation: "DTC" },
  { ticker: "GOOG US",  cusip: "02079K305", isin: "US02079K3059", name: "Alphabet Inc Cl C",      price: 178.36, country: "US", settlementLocation: "DTC" },
  { ticker: "GOOGL US", cusip: "02079K107", isin: "US02079K1079", name: "Alphabet Inc Cl A",      price: 176.98, country: "US", settlementLocation: "DTC" },
  { ticker: "META US",  cusip: "30303M102", isin: "US30303M1027", name: "Meta Platforms Inc",     price: 510.92, country: "US", settlementLocation: "DTC" },
  { ticker: "JPM US",   cusip: "46625H100", isin: "US46625H1005", name: "JPMorgan Chase & Co",    price: 221.15, country: "US", settlementLocation: "DTC" },
  { ticker: "GS US",    cusip: "38141G104", isin: "US38141G1040", name: "Goldman Sachs Group",    price: 482.90, country: "US", settlementLocation: "DTC" },
  { ticker: "BAC US",   cusip: "060505104", isin: "US0605051046", name: "Bank of America Corp",   price: 42.67,  country: "US", settlementLocation: "DTC" },
  { ticker: "MS US",    cusip: "617446448", isin: "US6174464486", name: "Morgan Stanley",         price: 104.33, country: "US", settlementLocation: "DTC" },
  { ticker: "V US",     cusip: "92826C839", isin: "US92826C8394", name: "Visa Inc",               price: 291.44, country: "US", settlementLocation: "DTC" },
  { ticker: "MA US",    cusip: "57636Q104", isin: "US57636Q1040", name: "Mastercard Inc",         price: 478.20, country: "US", settlementLocation: "DTC" },
  { ticker: "JNJ US",   cusip: "478160104", isin: "US4781601046", name: "Johnson & Johnson",      price: 155.82, country: "US", settlementLocation: "DTC" },
  { ticker: "UNH US",   cusip: "91324P102", isin: "US91324P1021", name: "UnitedHealth Group",     price: 532.10, country: "US", settlementLocation: "DTC" },
  { ticker: "PG US",    cusip: "742718109", isin: "US7427181091", name: "Procter & Gamble",       price: 168.45, country: "US", settlementLocation: "DTC" },
  { ticker: "HD US",    cusip: "437076102", isin: "US4370761029", name: "Home Depot Inc",         price: 362.78, country: "US", settlementLocation: "DTC" },
  { ticker: "XOM US",   cusip: "30231G102", isin: "US30231G1022", name: "Exxon Mobil Corp",       price: 109.56, country: "US", settlementLocation: "DTC" },
  { ticker: "CVX US",   cusip: "166764100", isin: "US1667641005", name: "Chevron Corp",           price: 154.22, country: "US", settlementLocation: "DTC" },
  { ticker: "BRK/B US", cusip: "084670702", isin: "US0846707026", name: "Berkshire Hathaway Cl B",price: 432.15, country: "US", settlementLocation: "DTC" },

  // Canadian Equities
  { ticker: "RY CN",    cusip: "780087102", isin: "CA7800871021", name: "Royal Bank of Canada",         price: 138.42, country: "CA", settlementLocation: "CDS" },
  { ticker: "TD CN",    cusip: "891160509", isin: "CA8911605092", name: "Toronto-Dominion Bank",        price: 82.15,  country: "CA", settlementLocation: "CDS" },
  { ticker: "BNS CN",   cusip: "064149107", isin: "CA0641491075", name: "Bank of Nova Scotia",          price: 72.88,  country: "CA", settlementLocation: "CDS" },
  { ticker: "BMO CN",   cusip: "063671101", isin: "CA0636711016", name: "Bank of Montreal",             price: 125.30, country: "CA", settlementLocation: "CDS" },
  { ticker: "CM CN",    cusip: "136069101", isin: "CA1360691010", name: "Canadian Imperial Bank",       price: 89.54,  country: "CA", settlementLocation: "CDS" },
  { ticker: "ENB CN",   cusip: "29250N105", isin: "CA29250N1050", name: "Enbridge Inc",                 price: 55.76,  country: "CA", settlementLocation: "CDS" },
  { ticker: "CNR CN",   cusip: "136375102", isin: "CA1363751027", name: "Canadian National Railway",    price: 162.90, country: "CA", settlementLocation: "CDS" },
  { ticker: "CP CN",    cusip: "13646K108", isin: "CA13646K1084", name: "Canadian Pacific Kansas City", price: 105.44, country: "CA", settlementLocation: "CDS" },
  { ticker: "SU CN",    cusip: "867224107", isin: "CA8672241079", name: "Suncor Energy Inc",            price: 52.18,  country: "CA", settlementLocation: "CDS" },
  { ticker: "MFC CN",   cusip: "56501R106", isin: "CA56501R1064", name: "Manulife Financial",           price: 36.72,  country: "CA", settlementLocation: "CDS" },
  { ticker: "SLF CN",   cusip: "866796105", isin: "CA8667961053", name: "Sun Life Financial",           price: 71.30,  country: "CA", settlementLocation: "CDS" },
  { ticker: "TRP CN",   cusip: "89353D107", isin: "CA89353D1078", name: "TC Energy Corp",               price: 58.94,  country: "CA", settlementLocation: "CDS" },
  { ticker: "BCE CN",   cusip: "05534B760", isin: "CA05534B7604", name: "BCE Inc",                      price: 46.32,  country: "CA", settlementLocation: "CDS" },
  { ticker: "T CN",     cusip: "87971M103", isin: "CA87971M1032", name: "TELUS Corp",                   price: 27.85,  country: "CA", settlementLocation: "CDS" },
  { ticker: "ABX CN",   cusip: "067901108", isin: "CA0679011084", name: "Barrick Gold Corp",            price: 24.16,  country: "CA", settlementLocation: "CDS" },
  { ticker: "NTR CN",   cusip: "67077M108", isin: "CA67077M1086", name: "Nutrien Ltd",                  price: 62.40,  country: "CA", settlementLocation: "CDS" },
  { ticker: "CSU CN",   cusip: "20464R101", isin: "CA20464R1010", name: "Constellation Software",       price: 4120.00,country: "CA", settlementLocation: "CDS" },
  { ticker: "SHOP CN",  cusip: "82509L107", isin: "CA82509L1076", name: "Shopify Inc",                  price: 108.55, country: "CA", settlementLocation: "CDS" },

  // US Fixed Income
  { ticker: "T 2.5 05/31",   cusip: "91282CJL6", isin: "US91282CJL63", name: "UST 2.5% 05/31",  price: 96.84,  country: "US", settlementLocation: "Fed" },
  { ticker: "T 3.0 02/28",   cusip: "91282CHN3", isin: "US91282CHN39", name: "UST 3.0% 02/28",  price: 98.12,  country: "US", settlementLocation: "Fed" },
  { ticker: "T 4.25 11/34",  cusip: "91282CLR5", isin: "US91282CLR59", name: "UST 4.25% 11/34", price: 101.45, country: "US", settlementLocation: "Fed" },
  { ticker: "T 1.5 08/26",   cusip: "91282CDH4", isin: "US91282CDH43", name: "UST 1.5% 08/26",  price: 94.38,  country: "US", settlementLocation: "Fed" },
];

// Lookup Indexes (built once)

const byTicker = new Map<string, SecurityMasterEntry>();
const byCusip  = new Map<string, SecurityMasterEntry>();
const byIsin   = new Map<string, SecurityMasterEntry>();

for (const sec of SECURITY_MASTER) {
  byTicker.set(sec.ticker.toUpperCase(), sec);
  byCusip.set(sec.cusip.toUpperCase(), sec);
  byIsin.set(sec.isin.toUpperCase(), sec);
}

/**
 * Look up a security by any single identifier.
 * Returns the full entry or undefined if not found.
 */
export function lookupSecurity(
  field: "ticker" | "cusip" | "isin",
  value: string,
): SecurityMasterEntry | undefined {
  const v = value.trim().toUpperCase();
  if (!v) return undefined;
  switch (field) {
    case "ticker": return byTicker.get(v);
    case "cusip":  return byCusip.get(v);
    case "isin":   return byIsin.get(v);
  }
}
'''

fp = pathlib.Path(r'C:\Dev\SFP\seclending-storyboard\src\data\securityMaster.ts')
fp.write_text(content.lstrip(), encoding='utf-8')
print('DONE')
