// Generated by AI (GitHub Copilot) - 2026-06-26
// API service layer for SecLending API Hub (http://localhost:5116)

const BASE_URL = "http://localhost:5116/api";

// ─── Common Types ───────────────────────────────────────────────────────────

export interface RequestMetadata {
  requestId: string;
  timeStampUtc: string;
}

export interface AckMetadata {
  correlationId: string;
  ackType: string;
  timeStampUtc: string;
}

export interface AckData {
  statusCode: string;
  statusMessage: string;
}

export interface AckResponse {
  metadata: AckMetadata;
  data: AckData;
}

export interface SecurityIdentifier {
  idType: string; // "CUSIP" | "ISIN" | "SEDOL" | "TICKER"
  idValue: string;
}

// ─── Open Order Types ───────────────────────────────────────────────────────

export interface OpenOrderData {
  lenderEntityId: string;
  lenderParentId: string;
  borrowerEntityId: string;
  borrowerParentId: string;
  quoteId?: string;
  securityIdentifiers: SecurityIdentifier[];
  country: string;
  transactionType: string; // "BORROW" | "LEND"
  quantity: number;
  loanRate: number;
  collateralType?: string;
  collateralCurrency?: string;
  loanSettlementDate?: string;
  collateralSettlementDate?: string;
  settlementType?: string; // "FOP" | "DVP"
  loanPrice?: number;
  securityPrice?: number;
  loanValue?: number;
  allowCounterOffer?: boolean;
  orderExpiryUtc?: string;
}

export interface OpenOrderRequest {
  metadata: RequestMetadata;
  data: OpenOrderData;
}

export interface OrderDecision {
  correlationId: string;
  decision: string; // "Accept" | "Reject" | "Counter"
  counterQuantity?: number;
  counterRate?: number;
  counterLoanPrice?: number;
  reasonCode?: string;
}

export interface OrderDecisionRequest {
  metadata: RequestMetadata;
  data: {
    callerEntityId: string;
    orderDecisions: OrderDecision[];
  };
}

// ─── Recall Types ───────────────────────────────────────────────────────────

export interface RecallData {
  lenderEntityId: string;
  lenderParentId: string;
  borrowerEntityId: string;
  borrowerParentId: string;
  securityIdentifiers: SecurityIdentifier[];
  country: string;
  transactionType: string;
  quantity: number;
  outstandingLoanQuantity?: number;
  orderDate?: string;
  settlementDate: string;
  collateralType?: string;
  collateralCurrency?: string;
  settlementType?: string;
  loanPrice?: number;
  securityPrice?: number;
  loanValue?: number;
  reasonCode?: string;
}

export interface RecallRequest {
  metadata: RequestMetadata;
  data: RecallData;
}

export interface RecallDecision {
  correlationId: string;
  decision: string; // "FullReturn" | "PartialReturn" | "Reject"
  returnQuantity?: number;
  proposedSettlementDate?: string;
  reasonCode?: string;
}

export interface RecallDecisionRequest {
  metadata: RequestMetadata;
  data: {
    callerEntityId: string;
    decisions: RecallDecision[];
  };
}

// ─── Return (Repay) Types ───────────────────────────────────────────────────

export interface ReturnData {
  lenderEntityId: string;
  lenderParentId: string;
  borrowerEntityId: string;
  borrowerParentId: string;
  securityIdentifiers: SecurityIdentifier[];
  country: string;
  transactionType: string;
  quantity: number;
  outstandingLoanQuantity?: number;
  orderDate?: string;
  settlementDate: string;
  collateralType?: string;
  collateralCurrency?: string;
  settlementType?: string;
  loanPrice?: number;
  securityPrice?: number;
  loanValue?: number;
  reasonCode?: string;
}

export interface ReturnRequest {
  metadata: RequestMetadata;
  data: ReturnData;
}

export interface ReturnDecision {
  correlationId: string;
  decision: string; // "FullReturn" | "Reject"
  reasonCode?: string;
}

export interface ReturnDecisionRequest {
  metadata: RequestMetadata;
  data: {
    callerEntityId: string;
    decisions: ReturnDecision[];
  };
}

// ─── GET Response Types ─────────────────────────────────────────────────────

export interface StoredOrderEntry {
  correlationId: string;
  orderStatus: string;
  submissionTimeUtc: string;
  payload: unknown;
  decision: unknown;
}

export interface GetOrdersResponse {
  metadata: { requestId: string; timeStampUtc: string; queryParams: { type?: string; sinceUtc?: string } };
  data: {
    callerEntityId: string;
    orders: StoredOrderEntry[];
  };
}

// ─── API Result Wrapper ─────────────────────────────────────────────────────

export type ApiResult<T> =
  | { success: true; data: T }
  | { success: false; error: string; statusCode?: number };

// ─── Helper ─────────────────────────────────────────────────────────────────

function buildMetadata(): RequestMetadata {
  return {
    requestId: crypto.randomUUID(),
    timeStampUtc: new Date().toISOString(),
  };
}

async function apiCall<T>(url: string, options: RequestInit): Promise<ApiResult<T>> {
  try {
    const res = await fetch(url, {
      ...options,
      headers: { "Content-Type": "application/json", ...options.headers },
    });
    const body = await res.json();
    if (res.ok) {
      return { success: true, data: body as T };
    }
    return { success: false, error: body?.data?.statusMessage ?? body?.title ?? res.statusText, statusCode: res.status };
  } catch (err) {
    return { success: false, error: err instanceof Error ? err.message : "Network error" };
  }
}

// ─── Open Order Endpoints ───────────────────────────────────────────────────

/** POST /api/open-borrow-orders — Submit a new Borrow or Lend order */
export async function submitOpenOrder(data: OpenOrderData): Promise<ApiResult<AckResponse>> {
  const request: OpenOrderRequest = { metadata: buildMetadata(), data };
  return apiCall<AckResponse>(`${BASE_URL}/open-borrow-orders`, {
    method: "POST",
    body: JSON.stringify(request),
  });
}

/** GET /api/open-borrow-orders — Poll for orders (submitted or responded) */
export async function getOpenOrders(
  callerEntityId: string,
  type: "submitted" | "responded" = "submitted",
  sinceUtc?: string,
): Promise<ApiResult<GetOrdersResponse>> {
  const params = new URLSearchParams({ callerEntityId, type });
  if (sinceUtc) params.set("sinceUtc", sinceUtc);
  return apiCall<GetOrdersResponse>(`${BASE_URL}/open-borrow-orders?${params}`, { method: "GET" });
}

/** PATCH /api/open-borrow-orders — Accept, Reject, or Counter an order */
export async function decideOpenOrder(
  callerEntityId: string,
  decisions: OrderDecision[],
): Promise<ApiResult<AckResponse>> {
  const request: OrderDecisionRequest = {
    metadata: buildMetadata(),
    data: { callerEntityId, orderDecisions: decisions },
  };
  return apiCall<AckResponse>(`${BASE_URL}/open-borrow-orders`, {
    method: "PATCH",
    body: JSON.stringify(request),
  });
}

// ─── Recall Endpoints ───────────────────────────────────────────────────────

/** POST /api/recalls — Submit a recall (Lender initiates) */
export async function submitRecall(data: RecallData): Promise<ApiResult<AckResponse>> {
  const request: RecallRequest = { metadata: buildMetadata(), data };
  return apiCall<AckResponse>(`${BASE_URL}/recalls`, {
    method: "POST",
    body: JSON.stringify(request),
  });
}

/** GET /api/recalls — Poll for recalls (new or responded) */
export async function getRecalls(
  callerEntityId: string,
  type: "new" | "responded" = "new",
  sinceUtc?: string,
): Promise<ApiResult<GetOrdersResponse>> {
  const params = new URLSearchParams({ callerEntityId, type });
  if (sinceUtc) params.set("sinceUtc", sinceUtc);
  return apiCall<GetOrdersResponse>(`${BASE_URL}/recalls?${params}`, { method: "GET" });
}

/** PATCH /api/recalls — Borrower responds to recall (FullReturn/PartialReturn/Reject) */
export async function decideRecall(
  callerEntityId: string,
  decisions: RecallDecision[],
): Promise<ApiResult<AckResponse>> {
  const request: RecallDecisionRequest = {
    metadata: buildMetadata(),
    data: { callerEntityId, decisions },
  };
  return apiCall<AckResponse>(`${BASE_URL}/recalls`, {
    method: "PATCH",
    body: JSON.stringify(request),
  });
}

// ─── Return (Repay) Endpoints ───────────────────────────────────────────────

/** POST /api/returns — Submit a return/repay (Borrower initiates) */
export async function submitReturn(data: ReturnData): Promise<ApiResult<AckResponse>> {
  const request: ReturnRequest = { metadata: buildMetadata(), data };
  return apiCall<AckResponse>(`${BASE_URL}/returns`, {
    method: "POST",
    body: JSON.stringify(request),
  });
}

/** GET /api/returns — Poll for returns (new or responded) */
export async function getReturns(
  callerEntityId: string,
  type: "new" | "responded" = "new",
  sinceUtc?: string,
): Promise<ApiResult<GetOrdersResponse>> {
  const params = new URLSearchParams({ callerEntityId, type });
  if (sinceUtc) params.set("sinceUtc", sinceUtc);
  return apiCall<GetOrdersResponse>(`${BASE_URL}/returns?${params}`, { method: "GET" });
}

/** PATCH /api/returns — Lender responds to return request (FullReturn/Reject) */
export async function decideReturn(
  callerEntityId: string,
  decisions: ReturnDecision[],
): Promise<ApiResult<AckResponse>> {
  const request: ReturnDecisionRequest = {
    metadata: buildMetadata(),
    data: { callerEntityId, decisions },
  };
  return apiCall<AckResponse>(`${BASE_URL}/returns`, {
    method: "PATCH",
    body: JSON.stringify(request),
  });
}

// ─── RFQ (Request for Quote) Endpoints ──────────────────────────────────────

export interface RfqLine {
  securityIdentifiers: SecurityIdentifier[];
  country?: string;
  collateralType?: string;
  collateralCurrency?: string;
  bidRate?: number;
  bidQuantity: number;
  loanSettlementDate?: string;
  collateralSettlementDate?: string;
  settlementType?: string;
}

export interface RfqData {
  borrowerEntityId: string;
  borrowerParentId: string;
  lenderEntityId: string;
  lenderParentId: string;
  requestForQuotes: RfqLine[];
}

export interface RfqRequest {
  metadata: RequestMetadata;
  data: RfqData;
}

/** POST /api/request-for-quotes — Submit RFQ to a single counterparty (one call per CP) */
export async function submitRfq(data: RfqData): Promise<ApiResult<AckResponse>> {
  const request: RfqRequest = { metadata: buildMetadata(), data };
  return apiCall<AckResponse>(`${BASE_URL}/request-for-quotes`, {
    method: "POST",
    body: JSON.stringify(request),
  });
}
