// Generated by AI (GitHub Copilot) - 2026-06-26
import { createContext, useContext, useState, useCallback, type ReactNode } from "react";

export type EntityId = "HOOPP" | "SEB";

export interface PerspectiveEntity {
  id: EntityId;
  label: string;
  role: string;
  email: string;
}

export const ENTITIES: PerspectiveEntity[] = [
  { id: "HOOPP", label: "HOOPP", role: "Lender", email: "alex.ye@hoopp.com" },
  { id: "SEB", label: "SEB AB", role: "Borrower", email: "lars.bergman@seb.se" },
];

const STORAGE_KEY = "seclending-perspective";

function loadPersistedEntity(): PerspectiveEntity {
  try {
    const stored = sessionStorage.getItem(STORAGE_KEY);
    if (stored) {
      const found = ENTITIES.find((e) => e.id === stored);
      if (found) return found;
    }
  } catch { /* sessionStorage unavailable */ }
  return ENTITIES[0];
}

interface PerspectiveContextValue {
  current: PerspectiveEntity;
  setCurrent: (entity: PerspectiveEntity) => void;
  counterpartyId: EntityId;
}

const PerspectiveContext = createContext<PerspectiveContextValue>({
  current: ENTITIES[0],
  setCurrent: () => {},
  counterpartyId: "SEB",
});

export function PerspectiveProvider({ children }: { children: ReactNode }) {
  const [current, setCurrentState] = useState<PerspectiveEntity>(loadPersistedEntity);
  const counterpartyId: EntityId = current.id === "HOOPP" ? "SEB" : "HOOPP";

  const setCurrent = useCallback((entity: PerspectiveEntity) => {
    setCurrentState(entity);
    try { sessionStorage.setItem(STORAGE_KEY, entity.id); } catch { /* ignore */ }
  }, []);

  return (
    <PerspectiveContext.Provider value={{ current, setCurrent, counterpartyId }}>
      {children}
    </PerspectiveContext.Provider>
  );
}

export function usePerspective() {
  return useContext(PerspectiveContext);
}
