// Generated by AI (GitHub Copilot) - 2026-06-29
import { useState, useMemo, useCallback, useRef } from "react";
import {
  Box, Typography, Button, Tooltip, TextField, Checkbox, FormControlLabel,
  Select, MenuItem, FormControl, InputLabel, InputAdornment, IconButton, Dialog,
  DialogTitle, DialogContent, DialogActions, Divider, List, ListItemButton,
  ListItemIcon, ListItemText, Chip,
} from "@mui/material";
import type { SelectChangeEvent } from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";
import SendIcon from "@mui/icons-material/Send";
import FilterAltIcon from "@mui/icons-material/FilterAlt";
import RefreshIcon from "@mui/icons-material/Refresh";
import ReceiptLongIcon from "@mui/icons-material/ReceiptLong";
import UpcomingIcon from "@mui/icons-material/Upcoming";
import ShowChartIcon from "@mui/icons-material/ShowChart";
import AttachMoneyIcon from "@mui/icons-material/AttachMoney";
import CurrencyExchangeIcon from "@mui/icons-material/CurrencyExchange";
import AccountBalanceIcon from "@mui/icons-material/AccountBalance";
import TrendingUpIcon from "@mui/icons-material/TrendingUp";
import ChevronLeftIcon from "@mui/icons-material/ChevronLeft";
import ChevronRightIcon from "@mui/icons-material/ChevronRight";
import ShoppingBasketIcon from "@mui/icons-material/ShoppingBasket";
import { AgGridReact } from "ag-grid-react";
import type { ColDef, GridReadyEvent } from "ag-grid-community";
import { AllCommunityModule, ModuleRegistry, themeQuartz } from "ag-grid-community";
import { AllEnterpriseModule } from "ag-grid-enterprise";
import { useThemeMode } from "../contexts/ThemeContext";

ModuleRegistry.registerModules([AllCommunityModule, AllEnterpriseModule]);

/* ── Theme ── */
const sfpDarkTheme = themeQuartz.withParams({
  backgroundColor: "#1a2332",
  foregroundColor: "#e8eaed",
  headerBackgroundColor: "#141d28",
  oddRowBackgroundColor: "#1e2a3a",
  rowHoverColor: "#253347",
  selectedRowBackgroundColor: "#1e3a5f",
  borderColor: "#2d3748",
  accentColor: "#5c9ce6",
  chromeBackgroundColor: "#141d28",
  headerFontSize: 11,
  fontSize: 12,
});

const sfpLightTheme = themeQuartz.withParams({
  backgroundColor: "#ffffff",
  foregroundColor: "#1e293b",
  headerBackgroundColor: "#f1f5f9",
  oddRowBackgroundColor: "#f8fafc",
  rowHoverColor: "#e2e8f0",
  selectedRowBackgroundColor: "#dbeafe",
  borderColor: "#e2e8f0",
  accentColor: "#1a73e8",
  chromeBackgroundColor: "#f1f5f9",
  headerFontSize: 11,
  fontSize: 12,
});

/* ── Event Types (matches SFP) ── */
type EventType = "LongToRepay" | "UpcomingShorts - FO" | "UpcomingShorts - CM" | "Proxy Voting";
type InstrumentType = "Equity" | "Bond" | "GDR/ADR" | "ABS" | "Index Bond";

/* ── Model (matches UpcomingEvent from SFP) ── */
interface UpcomingEvent {
  id: string;
  securityId: string;
  cusip: string;
  isin: string;
  eventType: EventType;
  nominal: number;
  eventTypeNominal: number;
  eventMarketValue: number;
  positionMarketValue: number;
  currency: string;
  programType: string;
  quantity: number;
  bps: number;
  modelPortfolio: string;
  counterpartyId: string;
  instrumentType: InstrumentType;
  collateralPool: string;
  tag: string;
  borrowIntExt: string;
  settlement: string;
  isSubmitted: number;
}

/* ── Counterparties for RFQ ── */
const COUNTERPARTIES = [
  { id: "seb", name: "SEB", region: "Europe" },
  { id: "bmo", name: "BMO Capital Markets", region: "Canada" },
  { id: "rbc", name: "RBC Capital Markets", region: "Canada" },
  { id: "gs", name: "Goldman Sachs", region: "US" },
  { id: "jpm", name: "JP Morgan", region: "US" },
  { id: "ms", name: "Morgan Stanley", region: "US" },
  { id: "citi", name: "Citibank", region: "US" },
  { id: "bnp", name: "BNP Paribas", region: "Europe" },
  { id: "hsbc", name: "HSBC", region: "Europe" },
  { id: "td", name: "TD Securities", region: "Canada" },
  { id: "scotiabank", name: "Scotiabank", region: "Canada" },
  { id: "national", name: "National Bank", region: "Canada" },
];

/* ── Mock Data ── */
const mockUpcomingEvents: UpcomingEvent[] = [
  { id: "1", securityId: "AAPL", cusip: "037833100", isin: "US0378331005", eventType: "UpcomingShorts - FO", nominal: 75000, eventTypeNominal: 50000, eventMarketValue: 9925000, positionMarketValue: 14887500, currency: "USD", programType: "Agency - GC", quantity: 50000, bps: 35, modelPortfolio: "US Large Cap", counterpartyId: "Goldman Sachs", instrumentType: "Equity", collateralPool: "GC Pool A", tag: "DEAL-2451", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "2", securityId: "AAPL", cusip: "037833100", isin: "US0378331005", eventType: "UpcomingShorts - FO", nominal: 75000, eventTypeNominal: 50000, eventMarketValue: 9925000, positionMarketValue: 4970000, currency: "USD", programType: "Agency - Exclusive", quantity: 25000, bps: 45, modelPortfolio: "US Large Cap", counterpartyId: "Morgan Stanley", instrumentType: "Equity", collateralPool: "GC Pool A", tag: "DEAL-2451", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "3", securityId: "MSFT", cusip: "594918104", isin: "US5949181045", eventType: "UpcomingShorts - FO", nominal: 30000, eventTypeNominal: 30000, eventMarketValue: 13356000, positionMarketValue: 13356000, currency: "USD", programType: "Agency - GC", quantity: 30000, bps: 25, modelPortfolio: "US Large Cap", counterpartyId: "JP Morgan", instrumentType: "Equity", collateralPool: "GC Pool A", tag: "DEAL-2452", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "4", securityId: "NVDA", cusip: "67066G104", isin: "US67066G1040", eventType: "UpcomingShorts - FO", nominal: 20000, eventTypeNominal: 15000, eventMarketValue: 2037000, positionMarketValue: 2716000, currency: "USD", programType: "Agency - Exclusive", quantity: 15000, bps: 55, modelPortfolio: "US Tech", counterpartyId: "Goldman Sachs", instrumentType: "Equity", collateralPool: "Tech Pool", tag: "DEAL-2453", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "5", securityId: "NVDA", cusip: "67066G104", isin: "US67066G1040", eventType: "UpcomingShorts - FO", nominal: 20000, eventTypeNominal: 15000, eventMarketValue: 2037000, positionMarketValue: 678900, currency: "USD", programType: "Principal", quantity: 5000, bps: 60, modelPortfolio: "US Tech", counterpartyId: "Citibank", instrumentType: "Equity", collateralPool: "Tech Pool", tag: "DEAL-2453", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "6", securityId: "SHOP", cusip: "82509L107", isin: "CA82509L1076", eventType: "UpcomingShorts - CM", nominal: 40000, eventTypeNominal: 40000, eventMarketValue: 5692000, positionMarketValue: 5692000, currency: "CAD", programType: "Agency - GC", quantity: 40000, bps: 30, modelPortfolio: "CAD Growth", counterpartyId: "BMO Capital Markets", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "DEAL-3001", borrowIntExt: "External", settlement: "CDS", isSubmitted: 0 },
  { id: "7", securityId: "RY", cusip: "780087102", isin: "CA7800871021", eventType: "UpcomingShorts - CM", nominal: 100000, eventTypeNominal: 100000, eventMarketValue: 17240000, positionMarketValue: 17240000, currency: "CAD", programType: "Agency - GC", quantity: 100000, bps: 8, modelPortfolio: "CAD Financials", counterpartyId: "RBC Capital Markets", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "", borrowIntExt: "Internal", settlement: "CDS", isSubmitted: 0 },
  { id: "8", securityId: "TD", cusip: "891160509", isin: "CA8911605092", eventType: "LongToRepay", nominal: 60000, eventTypeNominal: 60000, eventMarketValue: 4956000, positionMarketValue: 4956000, currency: "CAD", programType: "Agency - GC", quantity: 60000, bps: 12, modelPortfolio: "CAD Financials", counterpartyId: "TD Securities", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "DEAL-1200", borrowIntExt: "External", settlement: "CDS", isSubmitted: 0 },
  { id: "9", securityId: "TD", cusip: "891160509", isin: "CA8911605092", eventType: "LongToRepay", nominal: 60000, eventTypeNominal: 60000, eventMarketValue: 4956000, positionMarketValue: 2478000, currency: "CAD", programType: "Agency - Exclusive", quantity: 30000, bps: 15, modelPortfolio: "CAD Financials", counterpartyId: "Scotiabank", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "DEAL-1201", borrowIntExt: "External", settlement: "CDS", isSubmitted: 0 },
  { id: "10", securityId: "BNS", cusip: "064149107", isin: "CA0641491075", eventType: "LongToRepay", nominal: 80000, eventTypeNominal: 80000, eventMarketValue: 5856000, positionMarketValue: 5856000, currency: "CAD", programType: "Principal", quantity: 80000, bps: 10, modelPortfolio: "CAD Financials", counterpartyId: "National Bank", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "", borrowIntExt: "External", settlement: "CDS", isSubmitted: 1 },
  { id: "11", securityId: "TSLA", cusip: "88160R101", isin: "US88160R1014", eventType: "UpcomingShorts - FO", nominal: 12000, eventTypeNominal: 12000, eventMarketValue: 3145800, positionMarketValue: 3145800, currency: "USD", programType: "Agency - GC", quantity: 12000, bps: 85, modelPortfolio: "US Growth", counterpartyId: "Morgan Stanley", instrumentType: "Equity", collateralPool: "Spec Pool", tag: "DEAL-2460", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "12", securityId: "AMZN", cusip: "023135106", isin: "US0231351067", eventType: "UpcomingShorts - FO", nominal: 35000, eventTypeNominal: 35000, eventMarketValue: 6923000, positionMarketValue: 6923000, currency: "USD", programType: "Agency - GC", quantity: 35000, bps: 20, modelPortfolio: "US Large Cap", counterpartyId: "JP Morgan", instrumentType: "Equity", collateralPool: "GC Pool A", tag: "DEAL-2455", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "13", securityId: "ENB", cusip: "29250N105", isin: "CA29250N1050", eventType: "UpcomingShorts - CM", nominal: 150000, eventTypeNominal: 150000, eventMarketValue: 8835000, positionMarketValue: 8835000, currency: "CAD", programType: "Agency - GC", quantity: 150000, bps: 12, modelPortfolio: "CAD Infrastructure", counterpartyId: "TD Securities", instrumentType: "Equity", collateralPool: "CAD Pool", tag: "", borrowIntExt: "External", settlement: "CDS", isSubmitted: 0 },
  { id: "14", securityId: "XBB.TO", cusip: "N/A", isin: "CA9368BEY38", eventType: "LongToRepay", nominal: 500000, eventTypeNominal: 500000, eventMarketValue: 14850000, positionMarketValue: 14850000, currency: "CAD", programType: "Agency - GC", quantity: 500000, bps: 5, modelPortfolio: "Fixed Income", counterpartyId: "BMO Capital Markets", instrumentType: "Bond", collateralPool: "Bond Pool", tag: "DEAL-4001", borrowIntExt: "External", settlement: "CDS", isSubmitted: 0 },
  { id: "15", securityId: "JPM", cusip: "46625H100", isin: "US46625H1005", eventType: "Proxy Voting", nominal: 45000, eventTypeNominal: 45000, eventMarketValue: 11056500, positionMarketValue: 11056500, currency: "USD", programType: "Agency - GC", quantity: 45000, bps: 18, modelPortfolio: "US Financials", counterpartyId: "Goldman Sachs", instrumentType: "Equity", collateralPool: "GC Pool A", tag: "", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
  { id: "16", securityId: "META", cusip: "30303M102", isin: "US30303M1027", eventType: "UpcomingShorts - FO", nominal: 8000, eventTypeNominal: 8000, eventMarketValue: 4082400, positionMarketValue: 4082400, currency: "USD", programType: "Principal", quantity: 8000, bps: 40, modelPortfolio: "US Tech", counterpartyId: "Citibank", instrumentType: "Equity", collateralPool: "Tech Pool", tag: "DEAL-2470", borrowIntExt: "External", settlement: "DTC", isSubmitted: 0 },
];

/* ── Available calendar dates ── */
const AVAILABLE_DATES = ["2026-06-27", "2026-06-29", "2026-06-30", "2026-07-01", "2026-07-02", "2026-07-03"];

/* ── Component ── */
export default function SourcingPage() {
  const { mode } = useThemeMode();
  const gridRef = useRef<AgGridReact<UpcomingEvent>>(null);
  const gridTheme = mode === "dark" ? sfpDarkTheme : sfpLightTheme;

  // Filters (left panel)
  const [selectedDate, setSelectedDate] = useState("2026-06-29");
  const [eventTypeFilter, setEventTypeFilter] = useState<EventType>("UpcomingShorts - FO");
  const [instrumentFilter, setInstrumentFilter] = useState<InstrumentType | "">("");
  const [nominalFilter, setNominalFilter] = useState(false);
  const [searchTerm, setSearchTerm] = useState("");

  // Selection
  const [selectedRowCount, setSelectedRowCount] = useState(0);

  // RFQ Dialog
  const [rfqDialogOpen, setRfqDialogOpen] = useState(false);
  const [rfqSelectedCPs, setRfqSelectedCPs] = useState<string[]>([]);
  const [rfqExpiry, setRfqExpiry] = useState("15 min");
  const [rfqNotes, setRfqNotes] = useState("");

  // Last refresh timestamp
  const [lastRefresh] = useState(new Date());

  // Computed counts
  const counts = useMemo(() => {
    const ltr = mockUpcomingEvents.filter((e) => e.eventType === "LongToRepay").length;
    const shortsFO = mockUpcomingEvents.filter((e) => e.eventType === "UpcomingShorts - FO").length;
    const shortsCM = mockUpcomingEvents.filter((e) => e.eventType === "UpcomingShorts - CM").length;
    const proxy = mockUpcomingEvents.filter((e) => e.eventType === "Proxy Voting").length;
    const equity = mockUpcomingEvents.filter((e) => e.instrumentType === "Equity").length;
    const bond = mockUpcomingEvents.filter((e) => e.instrumentType === "Bond").length;
    const gdr = mockUpcomingEvents.filter((e) => e.instrumentType === "GDR/ADR").length;
    const abs = mockUpcomingEvents.filter((e) => e.instrumentType === "ABS").length;
    const indexBond = mockUpcomingEvents.filter((e) => e.instrumentType === "Index Bond").length;
    const above100 = mockUpcomingEvents.filter((e) => e.eventType === "LongToRepay" && e.nominal >= 100000).length;
    return { ltr, shortsFO, shortsCM, proxy, equity, bond, gdr, abs, indexBond, above100 };
  }, []);

  // Filtered grid data
  const filteredData = useMemo(() => {
    let data = mockUpcomingEvents.filter((e) => e.eventType === eventTypeFilter);
    if (instrumentFilter) data = data.filter((e) => e.instrumentType === instrumentFilter);
    if (nominalFilter && eventTypeFilter === "LongToRepay") data = data.filter((e) => e.nominal >= 100000);
    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      data = data.filter((e) => e.securityId.toLowerCase().includes(term) || e.cusip.includes(term) || e.isin.toLowerCase().includes(term));
    }
    return data;
  }, [eventTypeFilter, instrumentFilter, nominalFilter, searchTerm]);

  // Column definitions (match SFP sourcingGrid)
  const columnDefs: ColDef<UpcomingEvent>[] = useMemo(() => [
    { headerName: "", checkboxSelection: true, headerCheckboxSelection: true, width: 40, sortable: false, filter: false, resizable: false, suppressHeaderMenuButton: true },
    { headerName: "Ticker", field: "securityId", width: 100, rowGroup: true, hide: true },
    { headerName: "Event", field: "eventType", width: 140 },
    { headerName: "CUSIP", field: "cusip", width: 100 },
    { headerName: "ISIN", field: "isin", width: 120 },
    { headerName: "Total Shorts", field: "nominal", width: 110, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
    { headerName: "Event Shorts", field: "eventTypeNominal", width: 110, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
    { headerName: "Event Market Value", field: "eventMarketValue", width: 140, type: "numericColumn", valueFormatter: (p) => p.value != null ? `$${p.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "" },
    { headerName: "Currency", field: "currency", width: 85 },
    { headerName: "Program Type", field: "programType", width: 150 },
    { headerName: "Quantity", field: "quantity", width: 100, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
    { headerName: "BPS", field: "bps", width: 70, type: "numericColumn" },
    { headerName: "Model Portfolio", field: "modelPortfolio", width: 130 },
    { headerName: "Sec Lender", field: "counterpartyId", width: 150 },
    { headerName: "Instrument Type", field: "instrumentType", width: 130 },
    { headerName: "Position Market Value", field: "positionMarketValue", width: 160, type: "numericColumn", valueFormatter: (p) => p.value != null ? `$${p.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : "" },
    { headerName: "Collateral Pool", field: "collateralPool", width: 130 },
    { headerName: "Deal Label", field: "tag", width: 120 },
    { headerName: "Borrow Int/Ext", field: "borrowIntExt", width: 110 },
  ], []);

  const onGridReady = useCallback((event: GridReadyEvent) => {
    event.api.autoSizeAllColumns();
  }, []);

  const onSelectionChanged = useCallback(() => {
    const api = gridRef.current?.api;
    if (api) setSelectedRowCount(api.getSelectedRows().length);
  }, []);

  // RFQ handlers
  const handleOpenRfqDialog = () => {
    setRfqSelectedCPs([]);
    setRfqExpiry("15 min");
    setRfqNotes("");
    setRfqDialogOpen(true);
  };

  const handleToggleCP = (cpId: string) => {
    setRfqSelectedCPs((prev) => prev.includes(cpId) ? prev.filter((id) => id !== cpId) : [...prev, cpId]);
  };

  const handleSelectAllCPs = (region?: string) => {
    const ids = region ? COUNTERPARTIES.filter((cp) => cp.region === region).map((cp) => cp.id) : COUNTERPARTIES.map((cp) => cp.id);
    const allSelected = ids.every((id) => rfqSelectedCPs.includes(id));
    if (allSelected) {
      setRfqSelectedCPs((prev) => prev.filter((id) => !ids.includes(id)));
    } else {
      setRfqSelectedCPs((prev) => [...new Set([...prev, ...ids])]);
    }
  };

  const handleSendRfq = () => {
    setRfqDialogOpen(false);
  };

  // Button states
  const rfqEnabled = useMemo(() => {
    if (selectedRowCount === 0) return false;
    const api = gridRef.current?.api;
    if (!api) return false;
    const selected = api.getSelectedRows();
    return selected.every((o) => o.isSubmitted !== 1);
  }, [selectedRowCount]);

  return (
    <Box sx={{ display: "flex", height: "100%", gap: 0 }}>
      {/* ═══ LEFT SIDEBAR — Event Filters (280px) ═══ */}
      <Box sx={{ width: 270, minWidth: 270, display: "flex", flexDirection: "column", borderRight: 1, borderRightColor: "divider", overflow: "auto", pr: 1 }}>
        {/* Calendar section */}
        <Box sx={{ p: 1.5, borderBottom: 1, borderBottomColor: "divider" }}>
          <Typography variant="body2" sx={{ fontWeight: 600, fontSize: "0.75rem", color: "text.secondary", mb: 1, display: "flex", alignItems: "center", gap: 0.5 }}>
            <FilterAltIcon sx={{ fontSize: 14 }} /> DATE
          </Typography>
          <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 1 }}>
            <IconButton size="small"><ChevronLeftIcon sx={{ fontSize: 16 }} /></IconButton>
            <Typography sx={{ fontSize: "0.8rem", fontWeight: 600 }}>June 2026</Typography>
            <IconButton size="small"><ChevronRightIcon sx={{ fontSize: 16 }} /></IconButton>
          </Box>
          {/* Simple date chips instead of full calendar */}
          <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
            {AVAILABLE_DATES.map((d) => (
              <Chip
                key={d}
                label={d.slice(5)}
                size="small"
                onClick={() => setSelectedDate(d)}
                sx={{
                  fontSize: "0.7rem", height: 22, cursor: "pointer",
                  bgcolor: selectedDate === d ? "primary.main" : "action.hover",
                  color: selectedDate === d ? "#fff" : "text.primary",
                  fontWeight: selectedDate === d ? 700 : 400,
                }}
              />
            ))}
          </Box>
        </Box>

        {/* Nominal filter */}
        <Box sx={{ p: 1.5, borderBottom: 1, borderBottomColor: "divider" }}>
          <Typography variant="body2" sx={{ fontWeight: 600, fontSize: "0.75rem", color: "text.secondary", mb: 0.5, display: "flex", alignItems: "center", gap: 0.5 }}>
            <FilterAltIcon sx={{ fontSize: 14 }} /> NOMINAL
          </Typography>
          <List dense disablePadding>
            <ListItemButton
              selected={nominalFilter}
              onClick={() => setNominalFilter(!nominalFilter)}
              disabled={eventTypeFilter !== "LongToRepay"}
              sx={{ borderRadius: 1, py: 0.3 }}
            >
              <ListItemIcon sx={{ minWidth: 30 }}><ReceiptLongIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Above 100k" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.above100}</Typography>
            </ListItemButton>
          </List>
        </Box>

        {/* Event Type filters */}
        <Box sx={{ p: 1.5, borderBottom: 1, borderBottomColor: "divider" }}>
          <Typography variant="body2" sx={{ fontWeight: 600, fontSize: "0.75rem", color: "text.secondary", mb: 0.5, display: "flex", alignItems: "center", gap: 0.5 }}>
            <FilterAltIcon sx={{ fontSize: 14 }} /> EVENT TYPE
          </Typography>
          <List dense disablePadding>
            <ListItemButton selected={eventTypeFilter === "LongToRepay"} onClick={() => setEventTypeFilter("LongToRepay")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><ReceiptLongIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Long to Repay" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.ltr}</Typography>
            </ListItemButton>
            <ListItemButton selected={eventTypeFilter === "UpcomingShorts - FO"} onClick={() => setEventTypeFilter("UpcomingShorts - FO")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><UpcomingIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Upcoming Shorts - FO" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.shortsFO}</Typography>
            </ListItemButton>
            <ListItemButton selected={eventTypeFilter === "UpcomingShorts - CM"} onClick={() => setEventTypeFilter("UpcomingShorts - CM")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><UpcomingIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Upcoming Shorts - CM" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.shortsCM}</Typography>
            </ListItemButton>
            <ListItemButton selected={eventTypeFilter === "Proxy Voting"} onClick={() => setEventTypeFilter("Proxy Voting")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><UpcomingIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Corp Meeting Recall" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.proxy}</Typography>
            </ListItemButton>
          </List>
        </Box>

        {/* Instrument Type filters */}
        <Box sx={{ p: 1.5 }}>
          <Typography variant="body2" sx={{ fontWeight: 600, fontSize: "0.75rem", color: "text.secondary", mb: 0.5, display: "flex", alignItems: "center", gap: 0.5 }}>
            <FilterAltIcon sx={{ fontSize: 14 }} /> INSTRUMENT TYPE
          </Typography>
          <List dense disablePadding>
            <ListItemButton selected={instrumentFilter === "Equity"} onClick={() => setInstrumentFilter(instrumentFilter === "Equity" ? "" : "Equity")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><ShowChartIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Equity" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.equity}</Typography>
            </ListItemButton>
            <ListItemButton selected={instrumentFilter === "Bond"} onClick={() => setInstrumentFilter(instrumentFilter === "Bond" ? "" : "Bond")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><AttachMoneyIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Bond" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.bond}</Typography>
            </ListItemButton>
            <ListItemButton selected={instrumentFilter === "GDR/ADR"} onClick={() => setInstrumentFilter(instrumentFilter === "GDR/ADR" ? "" : "GDR/ADR")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><CurrencyExchangeIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="GDR / ADR" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.gdr}</Typography>
            </ListItemButton>
            <ListItemButton selected={instrumentFilter === "ABS"} onClick={() => setInstrumentFilter(instrumentFilter === "ABS" ? "" : "ABS")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><AccountBalanceIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="ABS" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.abs}</Typography>
            </ListItemButton>
            <ListItemButton selected={instrumentFilter === "Index Bond"} onClick={() => setInstrumentFilter(instrumentFilter === "Index Bond" ? "" : "Index Bond")} sx={{ borderRadius: 1, py: 0.3 }}>
              <ListItemIcon sx={{ minWidth: 30 }}><TrendingUpIcon sx={{ fontSize: 16 }} /></ListItemIcon>
              <ListItemText primary="Index Bond" slotProps={{ primary: { sx: { fontSize: "0.78rem" } } }} />
              <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>{counts.indexBond}</Typography>
            </ListItemButton>
          </List>
        </Box>
      </Box>

      {/* ═══ MAIN CONTENT (right) ═══ */}
      <Box sx={{ flex: 1, display: "flex", flexDirection: "column", minWidth: 0 }}>
        {/* Search Section */}
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5, px: 1.5, py: 0.75 }}>
          <TextField
            size="small"
            placeholder="Search by Security Identifier..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            slotProps={{
              input: {
                startAdornment: <InputAdornment position="start"><SearchIcon sx={{ fontSize: 16 }} /></InputAdornment>,
              },
            }}
            sx={{ width: 280 }}
          />
          <Box sx={{ flex: 1 }} />
          <Tooltip title="Refresh data">
            <IconButton size="small" sx={{ color: "text.secondary" }}><RefreshIcon sx={{ fontSize: 18 }} /></IconButton>
          </Tooltip>
        </Box>

        {/* AG Grid */}
        <Box sx={{ flex: 1, px: 1.5, minHeight: 0 }}>
          <AgGridReact<UpcomingEvent>
            ref={gridRef}
            theme={gridTheme}
            rowData={filteredData}
            columnDefs={columnDefs}
            rowSelection={{ mode: "multiRow", groupSelects: "descendants" }}
            groupDisplayType="groupRows"
            onGridReady={onGridReady}
            onSelectionChanged={onSelectionChanged}
            getRowId={(params) => params.data.id}
            suppressCellFocus
            animateRows
            rowHeight={30}
            headerHeight={28}
            suppressAggFuncInHeader
            autoGroupColumnDef={{ headerName: "Security", minWidth: 220, cellRendererParams: { suppressCount: false } }}
          />
        </Box>

        {/* Bottom Section */}
        <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", px: 1.5, py: 1, borderTop: 1, borderTopColor: "divider" }}>
          <Typography variant="body2" sx={{ color: "text.secondary", fontSize: "0.75rem" }}>
            Data Refreshed: {lastRefresh.toLocaleTimeString()} | {filteredData.length} records
          </Typography>
          <Box sx={{ display: "flex", gap: 1.5 }}>
            <Button
              variant="contained"
              size="small"
              startIcon={<ShoppingBasketIcon />}
              disabled={selectedRowCount === 0}
              sx={{ textTransform: "none", fontWeight: 600 }}
            >
              Create Basket{selectedRowCount > 0 ? ` (${selectedRowCount})` : ""}
            </Button>
            <Button
              variant="contained"
              size="small"
              startIcon={<SendIcon />}
              disabled={!rfqEnabled}
              onClick={handleOpenRfqDialog}
              sx={{ textTransform: "none", fontWeight: 600, bgcolor: "#6366f1", "&:hover": { bgcolor: "#4f46e5" }, "&.Mui-disabled": { bgcolor: "action.disabledBackground", color: "text.disabled" } }}
            >
              Initiate RFQ{selectedRowCount > 0 ? ` (${selectedRowCount})` : ""}
            </Button>
          </Box>
        </Box>
      </Box>

      {/* ═══ RFQ Dialog ═══ */}
      <Dialog open={rfqDialogOpen} onClose={() => setRfqDialogOpen(false)} maxWidth="sm" fullWidth slotProps={{ paper: { sx: { bgcolor: "background.paper", backgroundImage: "none" } } }}>
        <DialogTitle sx={{ fontSize: "1rem", fontWeight: 600, pb: 1 }}>
          Initiate RFQ Request
          <Typography variant="body2" sx={{ color: "text.secondary", fontSize: "0.8rem", mt: 0.5 }}>
            Blast RFQ to selected counterparties for {selectedRowCount} position{selectedRowCount === 1 ? "" : "s"}
          </Typography>
        </DialogTitle>
        <DialogContent>
          {/* Selected securities */}
          <Box sx={{ mb: 2, p: 1.5, borderRadius: 1, bgcolor: "action.hover" }}>
            <Typography variant="body2" sx={{ fontWeight: 600, mb: 0.5, fontSize: "0.8rem" }}>Selected Positions:</Typography>
            <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0.5 }}>
              {gridRef.current?.api?.getSelectedRows().map((row) => (
                <Chip key={row.id} label={`${row.securityId} (${row.quantity.toLocaleString()} @ ${row.bps}bps)`} size="small" sx={{ height: 20, fontSize: "0.7rem" }} />
              ))}
            </Box>
          </Box>

          <Divider sx={{ mb: 2 }} />

          {/* Counterparty selection */}
          <Typography variant="body2" sx={{ fontWeight: 600, mb: 1, fontSize: "0.8rem" }}>Select Counterparties:</Typography>
          <Box sx={{ display: "flex", gap: 1, mb: 1.5 }}>
            <Button size="small" variant="outlined" onClick={() => handleSelectAllCPs()} sx={{ textTransform: "none", fontSize: "0.7rem" }}>All</Button>
            <Button size="small" variant="outlined" onClick={() => handleSelectAllCPs("Canada")} sx={{ textTransform: "none", fontSize: "0.7rem" }}>All Canada</Button>
            <Button size="small" variant="outlined" onClick={() => handleSelectAllCPs("US")} sx={{ textTransform: "none", fontSize: "0.7rem" }}>All US</Button>
            <Button size="small" variant="outlined" onClick={() => handleSelectAllCPs("Europe")} sx={{ textTransform: "none", fontSize: "0.7rem" }}>All Europe</Button>
          </Box>
          <Box sx={{ display: "flex", flexWrap: "wrap", gap: 0 }}>
            {COUNTERPARTIES.map((cp) => (
              <FormControlLabel
                key={cp.id}
                control={<Checkbox size="small" checked={rfqSelectedCPs.includes(cp.id)} onChange={() => handleToggleCP(cp.id)} />}
                label={<Typography sx={{ fontSize: "0.8rem" }}>{cp.name} <span style={{ color: "#6b7280", fontSize: "0.7rem" }}>({cp.region})</span></Typography>}
                sx={{ width: "50%", m: 0 }}
              />
            ))}
          </Box>

          <Divider sx={{ my: 2 }} />

          {/* RFQ Options */}
          <Box sx={{ display: "flex", gap: 2, alignItems: "center" }}>
            <FormControl size="small" sx={{ minWidth: 130 }}>
              <InputLabel>Quote Expiry</InputLabel>
              <Select value={rfqExpiry} label="Quote Expiry" onChange={(e: SelectChangeEvent) => setRfqExpiry(e.target.value)}>
                <MenuItem value="15 min">15 min</MenuItem>
                <MenuItem value="30 min">30 min</MenuItem>
                <MenuItem value="1 hour">1 hour</MenuItem>
                <MenuItem value="2 hours">2 hours</MenuItem>
                <MenuItem value="EOD">End of Day</MenuItem>
              </Select>
            </FormControl>
            <TextField
              size="small"
              label="Notes (optional)"
              value={rfqNotes}
              onChange={(e) => setRfqNotes(e.target.value)}
              sx={{ flex: 1 }}
              placeholder="e.g., Urgent - need by T+1"
            />
          </Box>
        </DialogContent>
        <DialogActions sx={{ px: 3, pb: 2 }}>
          <Button onClick={() => setRfqDialogOpen(false)} sx={{ textTransform: "none" }}>Cancel</Button>
          <Button
            variant="contained"
            startIcon={<SendIcon />}
            disabled={rfqSelectedCPs.length === 0}
            onClick={handleSendRfq}
            sx={{ textTransform: "none", fontWeight: 600, bgcolor: "#6366f1", "&:hover": { bgcolor: "#4f46e5" } }}
          >
            Send RFQ to {rfqSelectedCPs.length} counterpart{rfqSelectedCPs.length === 1 ? "y" : "ies"}
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
