// Generated by AI (GitHub Copilot) - 2026-06-26
import { useState, useMemo, useCallback, useRef, useEffect, forwardRef, useImperativeHandle } from "react";
import {
  Box, Typography, Button, Chip, ToggleButton, ToggleButtonGroup, Tooltip, TextField,
  Select, MenuItem, FormControl, InputLabel, InputAdornment, IconButton,
} from "@mui/material";
import type { SelectChangeEvent } from "@mui/material";
import AddIcon from "@mui/icons-material/Add";
import FilterAltIcon from "@mui/icons-material/FilterAlt";
import RefreshIcon from "@mui/icons-material/Refresh";
import EditNoteIcon from "@mui/icons-material/EditNote";
import SearchIcon from "@mui/icons-material/Search";
import ClearIcon from "@mui/icons-material/Clear";
import SendIcon from "@mui/icons-material/Send";
import { AgGridReact } from "ag-grid-react";
import type { ColDef, ICellRendererParams, ICellEditorParams, GridReadyEvent, ColumnMovedEvent, SortChangedEvent, ColumnResizedEvent, CellValueChangedEvent } from "ag-grid-community";
import { AllCommunityModule, ModuleRegistry, themeQuartz } from "ag-grid-community";
import { AllEnterpriseModule } from "ag-grid-enterprise";
import {
  mockOrders, type Order, type OrderStatus, type OrderType, type SettlementType, type SettlementLocation,
  getInitiatedBy, getSecLenderLabel, getOrderTypeForViewer, getNextActionBy, getLastUpdatedBy,
  ENTITY_LABELS, ALL_ENTITY_IDS, MAX_COUNTER_OFFERS, MANDATORY_NEW_ORDER_FIELDS, createNewOrderRow,
} from "../mockData";
import { statusColors, tradeTypeColors } from "../theme";
import { submitOpenOrder } from "../services/apiClient";
import { lookupSecurity } from "../data/securityMaster";
import OrderDetailPanel from "../components/OrderDetailPanel";
import { usePerspective } from "../contexts/PerspectiveContext";
import { useThemeMode } from "../contexts/ThemeContext";

ModuleRegistry.registerModules([AllCommunityModule, AllEnterpriseModule]);

const ALL_STATUSES: OrderStatus[] = ["New","Draft","Submitted","Pending","Countered","Accepted","Rejected","Booking","Booked","Failed","Expired","Cancelled"];
const ORDER_TYPES: OrderType[] = ["Borrow", "Lend", "Recall", "Repay"];
const ALL_SETTLEMENT_TYPES: SettlementType[] = ["FOP", "DVP"];
const ALL_SETTLEMENT_LOCATIONS: SettlementLocation[] = ["DTC", "CDS", "Fed"];

/* ── Session storage keys for grid state persistence ── */
const GRID_COL_STATE_KEY = "seclending-grid-col-state-v4";

const sfpDarkTheme = themeQuartz.withParams({
  backgroundColor: "#1a2332",
  foregroundColor: "#e8eaed",
  headerBackgroundColor: "#141d28",
  
  oddRowBackgroundColor: "#1e2a3a",
  rowHoverColor: "#253347",
  selectedRowBackgroundColor: "#1e3a5f",
  borderColor: "#2d3748",
  accentColor: "#5c9ce6",
  chromeBackgroundColor: "#141d28",
  headerFontSize: 11,
  fontSize: 13,
});

const sfpLightTheme = themeQuartz.withParams({
  backgroundColor: "#ffffff",
  foregroundColor: "#1e293b",
  headerBackgroundColor: "#f1f5f9",
  
  oddRowBackgroundColor: "#f8fafc",
  rowHoverColor: "#e2e8f0",
  selectedRowBackgroundColor: "#dbeafe",
  borderColor: "#e2e8f0",
  accentColor: "#1a73e8",
  chromeBackgroundColor: "#f1f5f9",
  headerFontSize: 11,
  fontSize: 13,
});

/* ── Expiry urgency helpers ── */
function getExpiryUrgency(expiryUtc: string): { color: string; label: string; flash: boolean } {
  const now = Date.now();
  const expiry = new Date(expiryUtc).getTime();
  const diff = expiry - now;
  if (diff <= 0) return { color: "#6b7280", label: "Expired", flash: false };
  const mins = diff / 60000;
  if (mins <= 5) return { color: "#ef4444", label: "< 5 min", flash: true };
  if (mins <= 15) return { color: "#f97316", label: "< 15 min", flash: true };
  if (mins <= 60) return { color: "#eab308", label: "< 1 hr", flash: false };
  return { color: "#9ca3af", label: "", flash: false };
}

/* ── Cell Renderers ── */

function StatusCellRenderer(params: ICellRendererParams<Order>) {
  const order = params.data;
  if (!order) return null;
  const status = order.status;
  const color = statusColors[status] || "#9ca3af";
  const counterCount = order.counterOfferCount;
  const showCounter = counterCount > 0 && status === "Countered";
  return (
    <span style={{ color, fontWeight: 600, fontSize: "0.8rem" }}>
      {status}
      {showCounter && (
        <span style={{ color: counterCount >= MAX_COUNTER_OFFERS ? "#ef4444" : "#eab308", marginLeft: 4, fontSize: "0.7rem" }}>
          ({counterCount}/{MAX_COUNTER_OFFERS}{counterCount >= MAX_COUNTER_OFFERS ? " FINAL" : ""})
        </span>
      )}
    </span>
  );
}

function OrderTypeCellRenderer(params: ICellRendererParams<Order>) {
  const type = params.value as OrderType;
  const colors = tradeTypeColors[type] || { bg: "#374151", text: "#e8eaed" };
  return (
    <Chip
      label={type}
      size="small"
      sx={{
        bgcolor: colors.bg,
        color: colors.text,
        height: 20,
        fontSize: "0.7rem",
        fontWeight: 600,
      }}
    />
  );
}

function PendingWithCellRenderer(params: ICellRendererParams<Order>) {
  const val = params.value as string;
  if (!val || val === "\u2014") {
    return <span style={{ color: "#6b7280", fontSize: "0.8rem" }}>{val}</span>;
  }
  return (
    <span style={{ color: "#f59e0b", fontWeight: 500, fontSize: "0.8rem" }}>
      {val}
    </span>
  );
}

function ExpiryCellRenderer(params: ICellRendererParams<Order>) {
  if (!params.data || !params.data.orderExpiryUtc) return null;
  const raw = params.data.orderExpiryUtc;
  const isNew = params.data.status === "New";

  // For New rows, show the duration label (e.g. "15 min") or formatted custom time
  if (isNew) {
    const isPreset = EXPIRY_PRESETS.some((p) => p.label === raw);
    if (isPreset) {
      return <span style={{ color: "#93c5fd", fontSize: "0.8rem", fontWeight: 500 }}>{raw}</span>;
    }
    // Custom ISO — show formatted
    if (!isNaN(Date.parse(raw))) {
      const d = new Date(raw);
      const h = d.getHours(); const ampm = h >= 12 ? "PM" : "AM";
      const hh = String(h % 12 || 12).padStart(2, "0");
      const mm = String(d.getMinutes()).padStart(2, "0");
      const dateStr = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
      return <span style={{ color: "#93c5fd", fontSize: "0.8rem", fontWeight: 500 }}>{dateStr} {hh}:{mm} {ampm}</span>;
    }
    return <span style={{ color: "#6b7280", fontSize: "0.8rem" }}>{raw}</span>;
  }

  // For submitted/existing rows — show timestamp with urgency
  const urgency = getExpiryUrgency(raw);
  const d = new Date(raw);
  const h = d.getHours();
  const ampm = h >= 12 ? "PM" : "AM";
  const hh = String(h % 12 || 12).padStart(2, "0");
  const mm = String(d.getMinutes()).padStart(2, "0");
  const dateStr = `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`;
  const timeStr = `${hh}:${mm} ${ampm}`;
  const isTerminal = ["Booked","Failed","Expired","Cancelled","Rejected"].includes(params.data.status);

  return (
    <span
      style={{
        color: isTerminal ? "#6b7280" : urgency.color,
        fontWeight: isTerminal ? 400 : (urgency.flash ? 700 : 500),
        fontSize: "0.8rem",
        animation: urgency.flash && !isTerminal ? "expiry-pulse 1s ease-in-out infinite" : undefined,
      }}
    >
      {dateStr} {timeStr}
      {urgency.label && !isTerminal && (
        <span style={{ marginLeft: 4, fontSize: "0.65rem", opacity: 0.9 }}>
          {urgency.label}
        </span>
      )}
    </span>
  );
}

function SettlementTypeCellRenderer(params: ICellRendererParams<Order>) {
  const val = params.value as string;
  const isDVP = val === "DVP";
  return (
    <Chip
      label={val}
      size="small"
      sx={{
        bgcolor: isDVP ? "rgba(96,165,250,0.15)" : "rgba(52,211,153,0.15)",
        color: isDVP ? "#60a5fa" : "#34d399",
        height: 20,
        fontSize: "0.7rem",
        fontWeight: 600,
        border: `1px solid ${isDVP ? "rgba(96,165,250,0.3)" : "rgba(52,211,153,0.3)"}`,
      }}
    />
  );
}

const EDITABLE_CELL_CLASS = "editable-cell";
const NEW_ROW_EDITABLE_CLASS = "new-row-editable";

/* ── Custom Expiry Cell Editor ── */
const EXPIRY_PRESETS = [
  { label: "15 min", minutes: 15 },
  { label: "30 min", minutes: 30 },
  { label: "1 hour", minutes: 60 },
  { label: "2 hours", minutes: 120 },
  { label: "EOD", minutes: -1 },
] as const;

/** Resolve an expiry label ("15 min", "EOD", or ISO string) to an actual ISO timestamp */
function resolveExpiryToIso(label: string): string {
  const preset = EXPIRY_PRESETS.find((p) => p.label === label);
  if (preset) {
    if (preset.minutes === -1) {
      const eod = new Date(); eod.setHours(17, 0, 0, 0);
      if (eod.getTime() <= Date.now()) eod.setDate(eod.getDate() + 1);
      return eod.toISOString();
    }
    return new Date(Date.now() + preset.minutes * 60 * 1000).toISOString();
  }
  // Already an ISO string or custom datetime
  if (label && !isNaN(Date.parse(label))) return new Date(label).toISOString();
  // Fallback: +15 min
  return new Date(Date.now() + 15 * 60 * 1000).toISOString();
}

const ExpiryCellEditor = forwardRef((props: ICellEditorParams, ref) => {
  const [value, setValue] = useState<string>(props.value || "15 min");
  const [showCustom, setShowCustom] = useState(false);
  const refInput = useRef<HTMLInputElement>(null);

  useImperativeHandle(ref, () => ({
    getValue: () => value,
    isCancelAfterEnd: () => !value,
  }));

  useEffect(() => { if (showCustom && refInput.current) refInput.current.focus(); }, [showCustom]);

  const selectPreset = (label: string) => {
    setValue(label);
    setTimeout(() => props.stopEditing(), 0);
  };

  const confirmCustom = () => {
    if (refInput.current?.value) {
      const d = new Date(refInput.current.value);
      setValue(d.toISOString());
      setTimeout(() => props.stopEditing(), 0);
    }
  };

  const defaultDT = (() => {
    const d = value && !isNaN(Date.parse(value)) && !EXPIRY_PRESETS.some(p => p.label === value)
      ? new Date(value) : new Date(Date.now() + 15 * 60000);
    return d.toISOString().slice(0, 16);
  })();

  return (
    <div style={{ padding: 8, background: "#1e293b", border: "1px solid #334155", borderRadius: 6, width: 220, zIndex: 999 }}>
      <div style={{ display: "flex", flexWrap: "wrap", gap: 4, marginBottom: 6 }}>
        {EXPIRY_PRESETS.map((p) => (
          <button
            key={p.label}
            onClick={() => selectPreset(p.label)}
            style={{ padding: "3px 8px", fontSize: 11, borderRadius: 4, border: value === p.label ? "1px solid #60a5fa" : "1px solid #475569", background: value === p.label ? "#1e3a5f" : "#334155", color: value === p.label ? "#93c5fd" : "#e2e8f0", cursor: "pointer", fontWeight: value === p.label ? 700 : 400 }}
          >
            {p.label}
          </button>
        ))}
      </div>
      {!showCustom ? (
        <button
          onClick={() => setShowCustom(true)}
          style={{ width: "100%", padding: "4px 8px", fontSize: 11, borderRadius: 4, border: "1px solid #475569", background: "#1e3a5f", color: "#93c5fd", cursor: "pointer" }}
        >
          Custom time...
        </button>
      ) : (
        <div style={{ display: "flex", gap: 4 }}>
          <input
            ref={refInput}
            type="datetime-local"
            defaultValue={defaultDT}
            style={{ flex: 1, fontSize: 11, padding: "3px 4px", borderRadius: 4, border: "1px solid #475569", background: "#0f172a", color: "#e2e8f0" }}
            onKeyDown={(e) => { if (e.key === "Enter") confirmCustom(); }}
          />
          <button
            onClick={confirmCustom}
            style={{ padding: "3px 8px", fontSize: 11, borderRadius: 4, border: "1px solid #475569", background: "#166534", color: "#bbf7d0", cursor: "pointer" }}
          >
            OK
          </button>
        </div>
      )}
    </div>
  );
});

/** Check if a cell value is "empty" for mandatory validation */
function isMandatoryEmpty(value: unknown): boolean {
  if (value == null) return true;
  if (typeof value === "string" && value.trim() === "") return true;
  if (typeof value === "number" && value === 0) return true;
  return false;
}

/* ── Orders Page ── */

export default function OrdersPage() {
  const gridRef = useRef<AgGridReact<Order>>(null);
  const { current } = usePerspective();
  const { mode } = useThemeMode();
  const [typeFilter, setTypeFilter] = useState<"All" | "Borrow" | "Lend" | "Recall" | "Repay">("All");
  const [selectedOrder, setSelectedOrder] = useState<Order | null>(null);
  const [bulkBps, setBulkBps] = useState("");
  const [bulkQuantity, setBulkQuantity] = useState("");
  const [bulkTradeDate, setBulkTradeDate] = useState("");
  const [bulkDvpPrice, setBulkDvpPrice] = useState("");
  const [bulkSettlementDate, setBulkSettlementDate] = useState("");
  const [bulkType, setBulkType] = useState("");
  const [selectedRowCount, setSelectedRowCount] = useState(0);
  const [rowData, setRowData] = useState<Order[]>([]);

  // Inline filter bar state
  const [filterStatus, setFilterStatus] = useState("");
  const [filterSettlement, setFilterSettlement] = useState("");
  const [filterSecLender, setFilterSecLender] = useState("");
  const [filterPendingWith, setFilterPendingWith] = useState("");
  const [filterSettlementLocation, setFilterSettlementLocation] = useState("");
  const [searchTerm, setSearchTerm] = useState("");

  const gridStateRestored = useRef(false);

  const allSecLenders = useMemo(
    () => Array.from(new Set(mockOrders
      .filter((o) => o.lenderEntityId === current.id || o.borrowerEntityId === current.id)
      .map((o) => getSecLenderLabel(o, current.id)))).sort(),
    [current.id],
  );

  const allPendingWith = useMemo(
    () => Array.from(new Set(mockOrders
      .filter((o) => o.lenderEntityId === current.id || o.borrowerEntityId === current.id)
      .map((o) => getNextActionBy(o))
      .filter((v) => v !== "\u2014"))).sort(),
    [current.id],
  );

  const resetFilters = useCallback(() => {
    setFilterStatus("");
    setFilterSettlement("");
    setFilterSecLender("");
    setFilterPendingWith("");
    setFilterSettlementLocation("");
    setSearchTerm("");
  }, []);

  const hasActiveFilters = filterStatus || filterSettlement || filterSecLender || filterPendingWith || filterSettlementLocation || searchTerm;

  useEffect(() => {
    let data = mockOrders.filter((o) => o.lenderEntityId === current.id || o.borrowerEntityId === current.id);
    if (typeFilter !== "All") data = data.filter((o) => getOrderTypeForViewer(o, current.id) === typeFilter);
    if (filterStatus) data = data.filter((o) => o.status === filterStatus);
    if (filterSettlement) data = data.filter((o) => o.settlementType === filterSettlement);
    if (filterSecLender) data = data.filter((o) => getSecLenderLabel(o, current.id) === filterSecLender);
    if (filterPendingWith) data = data.filter((o) => getNextActionBy(o) === filterPendingWith);
    if (filterSettlementLocation) data = data.filter((o) => o.settlementLocation === filterSettlementLocation);
    if (searchTerm) {
      const term = searchTerm.toLowerCase();
      data = data.filter((o) =>
        o.orderId.toLowerCase().includes(term) ||
        o.securityId.toLowerCase().includes(term) ||
        o.cusip.toLowerCase().includes(term) ||
        o.isin.toLowerCase().includes(term) ||
        o.status.toLowerCase().includes(term) ||
        getSecLenderLabel(o, current.id).toLowerCase().includes(term) ||
        (o.notes && o.notes.toLowerCase().includes(term))
      );
    }
    setRowData(data);
  }, [typeFilter, filterStatus, filterSettlement, filterSecLender, filterPendingWith, filterSettlementLocation, searchTerm, current.id]);

  /** Helper: editable only when row status is New */
  const isNewRow = (p: { data?: Order | null }) => p.data?.status === "New";
  const isEditableAlways = () => true;

  const columnDefs = useMemo(() => [
    { headerName: "Status", field: "status", width: 140, cellRenderer: StatusCellRenderer, headerTooltip: "Current status" },
    { headerName: "Type", field: "orderType", colId: "type", width: 100, editable: isNewRow, cellEditor: "agSelectCellEditor", cellEditorParams: { values: ["", ...ORDER_TYPES] }, cellRenderer: OrderTypeCellRenderer, valueGetter: (p) => p.data ? (p.data.status === "New" ? p.data.orderType : getOrderTypeForViewer(p.data, current.id)) : "", cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New", "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.orderType) }, headerTooltip: "Transaction type" },
    { headerName: "Action Pending", colId: "pendingWith", width: 130, valueGetter: (p) => p.data ? getNextActionBy(p.data) : "", cellRenderer: PendingWithCellRenderer, headerTooltip: "The party expected to take the next action" },
    { headerName: "Order Expiry", colId: "expiry", width: 185, editable: (p) => p.data?.status === "New", cellRenderer: ExpiryCellRenderer, cellEditor: ExpiryCellEditor, cellEditorPopup: true, valueGetter: (p) => p.data?.orderExpiryUtc ?? "", valueSetter: (p) => { p.data.orderExpiryUtc = p.newValue; return true; }, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New" }, headerTooltip: "Order expiry — click to set duration" },
    { headerName: "Sec Lender", field: "lenderEntityId", colId: "secLender", width: 160, editable: isNewRow, cellEditor: "agSelectCellEditor", cellEditorParams: { values: ALL_ENTITY_IDS }, valueGetter: (p) => p.data ? (p.data.status === "New" ? (ENTITY_LABELS[p.data.lenderEntityId] || "") : getSecLenderLabel(p.data, current.id)) : "", valueSetter: (p) => { p.data.lenderEntityId = p.newValue; return true; }, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New", "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.lenderEntityId) }, headerTooltip: "Securities lending account" },
    { headerName: "Security ID", field: "securityId", width: 110, editable: isNewRow, cellStyle: { fontWeight: 500 }, valueParser: (p) => String(p.newValue ?? "").toUpperCase(), cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New", "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.securityId) }, headerTooltip: "Security identifier" },
    { headerName: "CUSIP", field: "cusip", width: 110, editable: isNewRow, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New" }, headerTooltip: "CUSIP" },
    { headerName: "ISIN", field: "isin", width: 140, editable: isNewRow, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New" }, headerTooltip: "ISIN" },
    { headerName: "Allow Counter?", field: "allowCounterOffer", colId: "allowCounter", width: 120, cellRenderer: "agCheckboxCellRenderer", cellEditor: "agCheckboxCellEditor", editable: (p) => p.data?.status === "New" || (!!p.data && p.data.counterOfferCount < MAX_COUNTER_OFFERS) },
    { headerName: "Settlement", field: "settlementType", width: 110, editable: isNewRow, cellEditor: "agSelectCellEditor", cellEditorParams: { values: ["FOP", "DVP"] }, cellRenderer: SettlementTypeCellRenderer, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New", "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.settlementType) }, headerTooltip: "FOP or DVP" },
    { headerName: "Quantity", field: "quantity", width: 110, type: "numericColumn", editable: isEditableAlways, cellClass: EDITABLE_CELL_CLASS, valueFormatter: (p) => (p.value != null && p.value !== 0) ? p.value.toLocaleString() : "", valueParser: (p) => Number(String(p.newValue).replace(/,/g, "")) || 0, cellClassRules: { "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.quantity) }, headerTooltip: "Shares/units" },
    { headerName: "BPS", field: "feeRate", width: 80, editable: isEditableAlways, cellClassRules: { [EDITABLE_CELL_CLASS]: () => true, "mandatory-empty": (p) => p.data?.status === "New" && (p.data?.orderType === "Borrow" || p.data?.orderType === "Lend") && p.data?.feeRate == null }, valueGetter: (p) => p.data?.feeRate != null ? p.data.feeRate * 100 : null, valueSetter: (p) => { const v = p.newValue == null || String(p.newValue).trim() === "" ? null : Number(p.newValue) / 100; p.data.feeRate = v; return true; }, valueFormatter: (p) => { if (p.value == null) return ""; const v = Number(p.value); return Number.isInteger(v) ? String(v) : v.toFixed(3).replace(/0+$/, "").replace(/\.$/, ""); }, headerTooltip: "Fee rate in BPS" },
    { headerName: "Settle Loc", field: "settlementLocation", colId: "settleLoc", width: 100, editable: isNewRow, cellEditor: "agSelectCellEditor", cellEditorParams: { values: ["DTC", "CDS", "Fed"] }, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New", "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.settlementLocation) }, headerTooltip: "Settlement location" },
    { headerName: "Price", field: "price", width: 100, type: "numericColumn", editable: isNewRow, cellClassRules: { [NEW_ROW_EDITABLE_CLASS]: (p) => p.data?.status === "New" }, valueFormatter: (p) => (p.value != null && p.value !== 0) ? p.value.toFixed(2) : "", valueParser: (p) => parseFloat(p.newValue) || 0, headerTooltip: "Market price" },
    { headerName: "DVP Price", field: "dvpPrice", width: 110, type: "numericColumn", editable: isEditableAlways, cellClassRules: { [EDITABLE_CELL_CLASS]: () => true, "mandatory-empty": (p) => p.data?.status === "New" && p.data?.settlementType === "DVP" && isMandatoryEmpty(p.data?.dvpPrice) }, valueFormatter: (p) => (p.value != null && p.value !== 0) ? p.value.toFixed(2) : "", valueParser: (p) => parseFloat(p.newValue) || 0, headerTooltip: "DVP price" },
    { headerName: "Market Value", colId: "marketValue", valueGetter: (p) => { if (!p.data) return null; const mv = p.data.settlementType === "FOP" ? p.data.quantity * p.data.price : p.data.quantity * p.data.dvpPrice; return mv || null; }, width: 140, type: "numericColumn", valueFormatter: (p) => p.value != null ? "$" + p.value.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 }) : "", headerTooltip: "Calculated market value" },
    { headerName: "Trade Date", field: "tradeDate", width: 130, editable: isEditableAlways, cellClass: EDITABLE_CELL_CLASS, cellClassRules: { "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.tradeDate) }, headerTooltip: "Trade date" },
    { headerName: "Settlement Date", field: "settlementDate", width: 130, editable: isEditableAlways, cellClass: EDITABLE_CELL_CLASS, cellClassRules: { "mandatory-empty": (p) => p.data?.status === "New" && isMandatoryEmpty(p.data?.settlementDate) }, headerTooltip: "Settlement date" },
    { headerName: "Last Updated", field: "lastUpdatedUtc", width: 180, valueFormatter: (p) => { if (!p.value) return ""; const d = new Date(p.value); const yyyy = d.getFullYear(); const mo = String(d.getMonth()+1).padStart(2,"0"); const dd = String(d.getDate()).padStart(2,"0"); let h = d.getHours(); const ampm = h >= 12 ? "PM" : "AM"; h = h % 12 || 12; return yyyy+"-"+mo+"-"+dd+" "+String(h).padStart(2,"0")+":"+String(d.getMinutes()).padStart(2,"0")+":"+String(d.getSeconds()).padStart(2,"0")+" "+ampm; } },
    { headerName: "Last Updated By", colId: "lastUpdatedBy", width: 170, valueGetter: (p) => p.data ? getLastUpdatedBy(p.data) : "" },
    { headerName: "Initiated By", colId: "initiatedBy", width: 120, valueGetter: (p) => p.data ? getInitiatedBy(p.data, current.id) : "" },
  ] as ColDef<Order>[], [current.id]);

  const defaultColDef = useMemo<ColDef>(() => ({
    resizable: true,
    sortable: true,
    filter: true,
    suppressHeaderFilterButton: true,
  }), []);

  const getRowId = useCallback((params: { data: Order }) => params.data.orderId, []);

  const statusBar = useMemo(() => ({
    statusPanels: [
      { statusPanel: "agAggregationComponent" },
    ],
  }), []);

  /* ── Grid State Persistence ── */

  const saveGridState = useCallback(() => {
    const api = gridRef.current?.api;
    if (!api || !gridStateRestored.current) return;
    try {
      const colState = api.getColumnState();
      sessionStorage.setItem(GRID_COL_STATE_KEY, JSON.stringify(colState));
    } catch { /* ignore */ }
  }, []);

  const restoreGridState = useCallback((api: GridReadyEvent["api"]) => {
    try {
      const saved = sessionStorage.getItem(GRID_COL_STATE_KEY);
      if (saved) {
        api.applyColumnState({ state: JSON.parse(saved), applyOrder: true });
        gridStateRestored.current = true;
      }
      // If no saved state, defer sizing to onFirstDataRendered
    } catch { /* ignore */ }
  }, []);

  const onGridReady = useCallback((event: GridReadyEvent) => {
    restoreGridState(event.api);
  }, [restoreGridState]);

  const onFirstDataRendered = useCallback(() => {
    gridStateRestored.current = true;
  }, []);

  const onColumnMoved = useCallback((_event: ColumnMovedEvent) => { saveGridState(); }, [saveGridState]);
  const onSortChanged = useCallback((_event: SortChangedEvent) => { saveGridState(); }, [saveGridState]);
  const onColumnResized = useCallback((event: ColumnResizedEvent) => { if (event.finished) saveGridState(); }, [saveGridState]);
  const onColumnVisible = useCallback(() => { saveGridState(); }, [saveGridState]);

  /** Auto-populate security fields when one identifier is entered on a New row */
  const onCellValueChanged = useCallback((event: CellValueChangedEvent<Order>) => {
    if (!event.data || event.data.status !== "New") return;
    const field = event.colDef.field as string;
    const value = String(event.newValue ?? "").trim();
    if (!value) return;
    let match;
    if (field === "securityId") match = lookupSecurity("ticker", value);
    else if (field === "cusip") match = lookupSecurity("cusip", value);
    else if (field === "isin") match = lookupSecurity("isin", value);
    if (!match) return;
    // Always overwrite all related fields from the security master
    const updated = { ...event.data };
    if (field !== "securityId") updated.securityId = match.ticker;
    if (field !== "cusip") updated.cusip = match.cusip;
    if (field !== "isin") updated.isin = match.isin;
    updated.price = match.price;
    updated.settlementLocation = match.settlementLocation as SettlementLocation;
    event.api.applyTransaction({ update: [updated] });
  }, []);

  const onViewDetails = useCallback((order: Order) => {
    setSelectedOrder(order);
  }, []);

  const onSelectionChanged = useCallback(() => {
    const api = gridRef.current?.api;
    if (api) setSelectedRowCount(api.getSelectedRows().length);
  }, []);

  const handleApplyBulk = useCallback(() => {
    const api = gridRef.current?.api;
    if (!api) return;
    const selectedNodes = api.getSelectedNodes();
    if (selectedNodes.length === 0) return;
    selectedNodes.forEach((node) => {
      const data = { ...node.data! };
      if (bulkQuantity) data.quantity = Number(bulkQuantity.replace(/,/g, "")) || data.quantity;
      if (bulkBps) data.feeRate = (Number(bulkBps) || 0) / 100;
      if (bulkDvpPrice) data.dvpPrice = parseFloat(bulkDvpPrice) || data.dvpPrice;
      if (bulkTradeDate) data.tradeDate = bulkTradeDate;
      if (bulkSettlementDate) data.settlementDate = bulkSettlementDate;
      if (bulkType) data.orderType = bulkType as OrderType;
      node.setData(data);
    });
    api.refreshCells({ force: true });
    api.deselectAll();
    setSelectedRowCount(0);
  }, [bulkBps, bulkQuantity, bulkDvpPrice, bulkTradeDate, bulkSettlementDate, bulkType]);

  const handleAddOrder = useCallback(() => {
    const newRow = createNewOrderRow(current.id);
    setRowData((prev) => [newRow, ...prev]);
    // Scroll grid to top so user sees the new row
    setTimeout(() => gridRef.current?.api?.ensureIndexVisible(0, "top"), 50);
  }, [current.id]);

  const onDeleteNewRow = useCallback((orderId: string) => {
    setRowData((prev) => prev.filter((r) => r.orderId !== orderId));
  }, []);

  const onSubmitNewRow = useCallback(async (orderId: string) => {
    const row = rowData.find((r) => r.orderId === orderId);
    if (!row) return;
    // Validate mandatory fields
    const missing = MANDATORY_NEW_ORDER_FIELDS.filter((f) => isMandatoryEmpty((row as unknown as Record<string, unknown>)[f]));
    if (missing.length > 0) {
      alert("Please fill mandatory fields: " + missing.join(", "));
      return;
    }
    // Fire-and-forget API call (best effort — prototype always persists locally)
    // Map UI row fields → OpenOrderData shape expected by the API
    const securityIdentifiers = [
      ...(row.cusip ? [{ idType: "CUSIP", idValue: row.cusip }] : []),
      ...(row.isin ? [{ idType: "ISIN", idValue: row.isin }] : []),
      ...(row.securityId ? [{ idType: "TICKER", idValue: row.securityId }] : []),
    ];
    const transactionType = row.orderType === "Borrow" ? "BORROW" : row.orderType === "Lend" ? "LEND" : row.orderType.toUpperCase();
    const secMaster = lookupSecurity("ticker", row.securityId) ?? lookupSecurity("cusip", row.cusip);
    submitOpenOrder({
      lenderEntityId: row.lenderEntityId,
      lenderParentId: row.lenderEntityId,
      borrowerEntityId: row.borrowerEntityId || current.id,
      borrowerParentId: row.borrowerEntityId || current.id,
      securityIdentifiers,
      country: secMaster?.country ?? "CA",
      transactionType,
      quantity: row.quantity,
      loanRate: row.feeRate ?? 0,
      settlementType: row.settlementType,
      loanSettlementDate: row.settlementDate,
      collateralSettlementDate: row.settlementDate,
      loanPrice: row.dvpPrice || row.price,
      securityPrice: row.price,
      loanValue: row.quantity * (row.dvpPrice || row.price),
      allowCounterOffer: row.allowCounterOffer,
      orderExpiryUtc: resolveExpiryToIso(row.orderExpiryUtc),
    }).catch(() => { /* best-effort */ });
    // Update row locally — status, expiry resolved from label, last updated
    const now = new Date();
    const expiryUtc = resolveExpiryToIso(row.orderExpiryUtc);
    setRowData((prev) => prev.map((r) => r.orderId === orderId ? {
      ...r,
      status: "Submitted" as const,
      orderExpiryUtc: expiryUtc,
      lastUpdatedUtc: now.toISOString(),
      lastUpdatedByEntityId: current.id,
      lastUpdatedByUserId: current.email,
    } : r));
  }, [rowData, current.id, current.email]);

  const gridContext = useMemo(() => ({ onViewDetails, onDeleteNewRow, onSubmitNewRow }), [onViewDetails, onDeleteNewRow, onSubmitNewRow]);

  /** Compute button enabled states based on status + perspective matrix */
  const buttonStates = useMemo(() => {
    const api = gridRef.current?.api;
    if (!api || selectedRowCount === 0) return { accept: false, counter: false, reject: false, submit: false };
    const selected = api.getSelectedRows();

    // Submit: enabled only if ALL selected rows are "New"
    const submitEnabled = selected.length > 0 && selected.every((o) => o.status === "New");

    // Accept/Reject/Counter: enabled only if ALL selected rows are actionable by current viewer
    const actionableStatuses = ["Pending", "Countered"];
    const allActionable = selected.length > 0 && selected.every((o) => {
      if (!actionableStatuses.includes(o.status)) return false;
      // Check if action is pending on the current viewer
      if (o.status === "Pending") {
        // Pending = action is on the non-submitter
        return o.submittedByEntityId !== current.id;
      }
      if (o.status === "Countered") {
        // Countered = action is on the party who did NOT last update
        return o.lastUpdatedByEntityId !== current.id;
      }
      return false;
    });

    const acceptEnabled = allActionable;
    const rejectEnabled = allActionable;
    // Counter: additionally requires allowCounterOffer and not at max
    const counterEnabled = allActionable && selected.every((o) => o.allowCounterOffer && o.counterOfferCount < MAX_COUNTER_OFFERS);

    return { accept: acceptEnabled, counter: counterEnabled, reject: rejectEnabled, submit: submitEnabled };
  }, [selectedRowCount, current.id]);

  return (
    <Box sx={{ display: "flex", flexDirection: "column", height: "100%", gap: 1 }}>
      {/* Expiry flash CSS animation */}
      <style>{`
        @keyframes expiry-pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.4; }
        }
      `}</style>

      {/* Top toolbar */}
      <Box sx={{ display: "flex", alignItems: "center", gap: 2, px: 1, pt: 1 }}>
        <Typography variant="h4" sx={{ color: "text.primary" }}>Orders</Typography>
        <ToggleButtonGroup value={typeFilter} exclusive onChange={(_, val) => val && setTypeFilter(val)} size="small" sx={{ ml: 2 }}>
          <ToggleButton value="All">All</ToggleButton>
          <ToggleButton value="Borrow"><Chip label="Borrow" size="small" sx={{ bgcolor: tradeTypeColors.Borrow.bg, color: tradeTypeColors.Borrow.text, height: 20, fontSize: "0.7rem" }} /></ToggleButton>
          <ToggleButton value="Lend"><Chip label="Lend" size="small" sx={{ bgcolor: tradeTypeColors.Lend.bg, color: tradeTypeColors.Lend.text, height: 20, fontSize: "0.7rem" }} /></ToggleButton>
          <ToggleButton value="Recall"><Chip label="Recall" size="small" sx={{ bgcolor: tradeTypeColors.Recall.bg, color: tradeTypeColors.Recall.text, height: 20, fontSize: "0.7rem" }} /></ToggleButton>
          <ToggleButton value="Repay"><Chip label="Repay" size="small" sx={{ bgcolor: tradeTypeColors.Repay.bg, color: tradeTypeColors.Repay.text, height: 20, fontSize: "0.7rem" }} /></ToggleButton>
        </ToggleButtonGroup>
        <Box sx={{ flexGrow: 1 }} />
        <Tooltip title="Refresh orders"><Button size="small" startIcon={<RefreshIcon />} sx={{ color: "text.secondary" }}>Refresh</Button></Tooltip>
        <Button variant="contained" size="small" startIcon={<AddIcon />} color="primary" onClick={handleAddOrder}>New Order</Button>
      </Box>

      {/* Inline Filter Bar */}
      <Box sx={{ display: "flex", alignItems: "center", flexWrap: "wrap", gap: "10px", px: 1.5, py: "7px", mx: 1, bgcolor: "background.default", borderTopLeftRadius: "7px", borderTopRightRadius: "7px", borderBottom: 1, borderBottomColor: "divider" }}>
        <FilterAltIcon sx={{ color: hasActiveFilters ? "primary.main" : "text.disabled", fontSize: 20 }} />
        <FormControl size="small" sx={{ minWidth: 130 }}>
          <InputLabel>Status</InputLabel>
          <Select value={filterStatus} label="Status" onChange={(e: SelectChangeEvent) => setFilterStatus(e.target.value)}>
            <MenuItem value=""><em>All</em></MenuItem>
            {ALL_STATUSES.map((s) => <MenuItem key={s} value={s}>{s}</MenuItem>)}
          </Select>
        </FormControl>
        <FormControl size="small" sx={{ minWidth: 120 }}>
          <InputLabel>Settlement</InputLabel>
          <Select value={filterSettlement} label="Settlement" onChange={(e: SelectChangeEvent) => setFilterSettlement(e.target.value)}>
            <MenuItem value=""><em>All</em></MenuItem>
            {ALL_SETTLEMENT_TYPES.map((st) => <MenuItem key={st} value={st}>{st}</MenuItem>)}
          </Select>
        </FormControl>
        <FormControl size="small" sx={{ minWidth: 110 }}>
          <InputLabel>Settle Loc</InputLabel>
          <Select value={filterSettlementLocation} label="Settle Loc" onChange={(e: SelectChangeEvent) => setFilterSettlementLocation(e.target.value)}>
            <MenuItem value=""><em>All</em></MenuItem>
            {ALL_SETTLEMENT_LOCATIONS.map((sl) => <MenuItem key={sl} value={sl}>{sl}</MenuItem>)}
          </Select>
        </FormControl>
        <FormControl size="small" sx={{ minWidth: 150 }}>
          <InputLabel>Sec Lender</InputLabel>
          <Select value={filterSecLender} label="Sec Lender" onChange={(e: SelectChangeEvent) => setFilterSecLender(e.target.value)}>
            <MenuItem value=""><em>All</em></MenuItem>
            {allSecLenders.map((sl) => <MenuItem key={sl} value={sl}>{sl}</MenuItem>)}
          </Select>
        </FormControl>
        <FormControl size="small" sx={{ minWidth: 140 }}>
          <InputLabel>Action Pending</InputLabel>
          <Select value={filterPendingWith} label="Action Pending" onChange={(e: SelectChangeEvent) => setFilterPendingWith(e.target.value)}>
            <MenuItem value=""><em>All</em></MenuItem>
            {allPendingWith.map((pw) => <MenuItem key={pw} value={pw}>{pw}</MenuItem>)}
          </Select>
        </FormControl>
        <TextField size="small" placeholder="Search..." value={searchTerm} onChange={(e) => setSearchTerm(e.target.value)} slotProps={{ input: { startAdornment: (<InputAdornment position="start"><SearchIcon sx={{ fontSize: 18, color: "text.disabled" }} /></InputAdornment>) } }} sx={{ width: 160 }} />
        {hasActiveFilters && (<Tooltip title="Reset all filters"><IconButton size="small" onClick={resetFilters} sx={{ color: "#f87171" }}><ClearIcon fontSize="small" /></IconButton></Tooltip>)}
      </Box>

      {/* Bulk Update Bar */}
      <Box sx={{ display: "flex", flexDirection: "column", gap: 1, px: 1.5, py: 1, mx: 1, bgcolor: "background.default", borderRadius: 1, border: 1, borderColor: "divider" }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
          <EditNoteIcon sx={{ color: "primary.main", fontSize: 20 }} />
          <Typography variant="body2" sx={{ color: "text.secondary", fontSize: 13 }}>Update all selected rows in a column</Typography>
        </Box>
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <TextField label="Quantity" size="small" value={bulkQuantity} onChange={(e) => setBulkQuantity(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} sx={{ width: 110 }} />
          <TextField label="BPS" size="small" value={bulkBps} onChange={(e) => setBulkBps(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} sx={{ width: 100 }} />
          <TextField label="DVP Price" size="small" value={bulkDvpPrice} onChange={(e) => setBulkDvpPrice(e.target.value)} slotProps={{ inputLabel: { shrink: true } }} sx={{ width: 110 }} />
          <FormControl size="small" sx={{ minWidth: 100 }}>
            <InputLabel>Type</InputLabel>
            <Select value={bulkType} label="Type" onChange={(e: SelectChangeEvent) => setBulkType(e.target.value)}>
              <MenuItem value=""><em>None</em></MenuItem>
              {ORDER_TYPES.map((t) => <MenuItem key={t} value={t}>{t}</MenuItem>)}
            </Select>
          </FormControl>
          <TextField label="Trade Date" type="date" size="small" value={bulkTradeDate} onChange={(e) => setBulkTradeDate(e.target.value)} onClick={(e) => (e.currentTarget.querySelector("input") as HTMLInputElement)?.showPicker()} slotProps={{ inputLabel: { shrink: true } }} sx={{ width: 170, cursor: "pointer" }} />
          <TextField label="Settlement Date" type="date" size="small" value={bulkSettlementDate} onChange={(e) => setBulkSettlementDate(e.target.value)} onClick={(e) => (e.currentTarget.querySelector("input") as HTMLInputElement)?.showPicker()} slotProps={{ inputLabel: { shrink: true } }} sx={{ width: 170, cursor: "pointer" }} />
          <Button variant="contained" size="small" disabled={selectedRowCount === 0 || !(bulkBps || bulkQuantity || bulkDvpPrice || bulkTradeDate || bulkSettlementDate || bulkType)} onClick={handleApplyBulk} sx={{ bgcolor: "#22c55e", "&:hover": { bgcolor: "#16a34a" }, "&.Mui-disabled": { bgcolor: "action.disabledBackground", color: "text.disabled" }, textTransform: "none", fontWeight: 600, ml: 1 }}>
            Apply Changes{selectedRowCount > 0 ? ` (${selectedRowCount})` : ""}
          </Button>
        </Box>
      </Box>

      {/* Grid */}
      <Box sx={{ flexGrow: 1, px: 1, pb: 1 }}>
        <div style={{ width: "100%", height: "100%" }}>
          <AgGridReact<Order>
            key={current.id}
            ref={gridRef}
            theme={mode === "dark" ? sfpDarkTheme : sfpLightTheme}
            modules={[AllCommunityModule, AllEnterpriseModule]}
            rowData={rowData}
            columnDefs={columnDefs}
            defaultColDef={defaultColDef}
            getRowId={getRowId}
            context={gridContext}
            statusBar={statusBar}
            onGridReady={onGridReady}
            onFirstDataRendered={onFirstDataRendered}
            onSelectionChanged={onSelectionChanged}
            onColumnMoved={onColumnMoved}
            onSortChanged={onSortChanged}
            onColumnResized={onColumnResized}
            onColumnVisible={onColumnVisible}
            onCellValueChanged={onCellValueChanged}
            cellSelection={true}
            columnMenu="legacy"
            rowSelection={{ mode: "multiRow" }}
            selectionColumnDef={{ width: 32, maxWidth: 32, minWidth: 32, resizable: false, suppressHeaderMenuButton: true }}
            singleClickEdit
            headerHeight={32}
            rowHeight={34}
          />
        </div>
      </Box>

      {/* Detail panel */}
      {selectedOrder && (
        <OrderDetailPanel order={selectedOrder} onClose={() => setSelectedOrder(null)} />
      )}

      {/* Bulk Action Buttons */}
      <Box sx={{ display: "flex", justifyContent: "flex-end", gap: 1.5, px: 1.5, py: 1, borderTop: 1, borderTopColor: "divider" }}>
        <Button variant="contained" size="small" color="success" disabled={!buttonStates.accept} sx={{ textTransform: "none", fontWeight: 600 }}>Accept</Button>
        <Tooltip title={!buttonStates.counter && buttonStates.accept ? "Counter offers not allowed or limit reached for selected order(s)" : ""}>
          <span>
            <Button variant="outlined" size="small" color="warning" disabled={!buttonStates.counter} sx={{ textTransform: "none", fontWeight: 600 }}>Counter</Button>
          </span>
        </Tooltip>
        <Button variant="outlined" size="small" color="error" disabled={!buttonStates.reject} sx={{ textTransform: "none", fontWeight: 600 }}>Reject</Button>
        <Button variant="contained" size="small" startIcon={<SendIcon />} disabled={!buttonStates.submit} sx={{ textTransform: "none", fontWeight: 600, bgcolor: "#6366f1", "&:hover": { bgcolor: "#4f46e5" } }} onClick={() => { const api = gridRef.current?.api; if (!api) return; api.getSelectedRows().filter((r) => r.status === "New").forEach((r) => onSubmitNewRow(r.orderId)); }}>Submit</Button>
      </Box>
    </Box>
  );
}
