// Generated by AI (GitHub Copilot) - 2026-06-24
import { Box, Typography } from "@mui/material";

interface PlaceholderPageProps {
  title: string;
}

export default function PlaceholderPage({ title }: PlaceholderPageProps) {
  return (
    <Box sx={{ display: "flex", alignItems: "center", justifyContent: "center", height: "100%", opacity: 0.5 }}>
      <Box sx={{ textAlign: "center" }}>
        <Typography variant="h5" sx={{ color: "text.secondary", mb: 1 }}>
          {title}
        </Typography>
        <Typography variant="body2" sx={{ color: "text.disabled" }}>
          Existing SFP page — not part of this prototype
        </Typography>
      </Box>
    </Box>
  );
}
