// Generated by AI (GitHub Copilot) - 2026-06-29
import { useState, useMemo, useCallback, useRef, useEffect } from "react";
import {
  Box, Typography, Button, Tooltip, Paper, IconButton, Checkbox,
  LinearProgress, Divider, Dialog, DialogTitle,
  DialogContent, DialogActions, TextField, Popper, ClickAwayListener,
  InputAdornment, List, ListItemButton, ListItemIcon, ListItemText,
  Select, MenuItem, ToggleButton, ToggleButtonGroup, Snackbar, Alert,
} from "@mui/material";
import SearchIcon from "@mui/icons-material/Search";
import CloseIcon from "@mui/icons-material/Close";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import FlashOnIcon from "@mui/icons-material/FlashOn";
import AutoFixOffIcon from "@mui/icons-material/AutoFixOff";
import SendIcon from "@mui/icons-material/Send";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import WarningAmberIcon from "@mui/icons-material/WarningAmber";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutlined";
import { AgGridReact } from "ag-grid-react";
import type { ColDef, ColGroupDef, GridReadyEvent, CellValueChangedEvent } from "ag-grid-community";
import { AllCommunityModule, ModuleRegistry, themeQuartz } from "ag-grid-community";
import { AllEnterpriseModule } from "ag-grid-enterprise";
import { useThemeMode } from "../contexts/ThemeContext";
import { submitRfq } from "../services/apiClient";
import type { RfqData } from "../services/apiClient";

ModuleRegistry.registerModules([AllCommunityModule, AllEnterpriseModule]);

/* ── Themes ── */
const sfpDarkTheme = themeQuartz.withParams({
  backgroundColor: "#1a2332", foregroundColor: "#e8eaed",
  headerBackgroundColor: "#141d28", 
  oddRowBackgroundColor: "#1e2a3a", rowHoverColor: "#253347",
  selectedRowBackgroundColor: "#1e3a5f", borderColor: "#2d3748",
  accentColor: "#5c9ce6", chromeBackgroundColor: "#141d28",
  headerFontSize: 11, fontSize: 12,
});
const sfpLightTheme = themeQuartz.withParams({
  backgroundColor: "#ffffff", foregroundColor: "#1e293b",
  headerBackgroundColor: "#f1f5f9", 
  oddRowBackgroundColor: "#f8fafc", rowHoverColor: "#e2e8f0",
  selectedRowBackgroundColor: "#dbeafe", borderColor: "#e2e8f0",
  accentColor: "#1a73e8", chromeBackgroundColor: "#f1f5f9",
  headerFontSize: 11, fontSize: 12,
});

/* ═══════════════════════════════════════════════════════════════
   MODELS
   ═══════════════════════════════════════════════════════════════ */

interface SourcingBasket {
  id: string;
  name: string;
  securitiesCount: number;
  sourcedMV: number;
  totalMV: number;
}

interface SourcingLine {
  id: string;
  basketId: string;
  ticker: string;
  cusip: string;
  isin: string;
  totalQty: number;
  totalMV: number;
  remainingQty: number;
  avgBps: number | null;
  indBps: number | null;
  totalAvailable: number;
  totalAllocated: number;
}

interface CounterpartyQuote {
  counterpartyId: string;
  lineId: string;
  availableQty: number;
  bps: number;
  allocated: number;
}

interface Counterparty {
  id: string;
  name: string;
  region: string;
}

/* ═══════════════════════════════════════════════════════════════
   MOCK DATA
   ═══════════════════════════════════════════════════════════════ */

const COUNTERPARTIES: Counterparty[] = [
  { id: "bmo", name: "BMO Capital Markets", region: "Canada" },
  { id: "rbc", name: "RBC Capital Markets", region: "Canada" },
  { id: "td", name: "TD Securities", region: "Canada" },
  { id: "scotiabank", name: "Scotiabank", region: "Canada" },
  { id: "national", name: "National Bank", region: "Canada" },
  { id: "gs", name: "Goldman Sachs", region: "US" },
  { id: "jpm", name: "JP Morgan", region: "US" },
  { id: "ms", name: "Morgan Stanley", region: "US" },
  { id: "citi", name: "Citibank", region: "US" },
  { id: "bnp", name: "BNP Paribas", region: "Europe" },
  { id: "hsbc", name: "HSBC", region: "Europe" },
  { id: "seb", name: "SEB", region: "Europe" },
];

const mockBaskets: SourcingBasket[] = [
  { id: "BSK-101", name: "US Equities - FO Shorts", securitiesCount: 5, sourcedMV: 12300000, totalMV: 31206500 },
  { id: "BSK-102", name: "CAD Equities - CM Shorts", securitiesCount: 3, sourcedMV: 22932000, totalMV: 31767000 },
  { id: "BSK-103", name: "CAD Lend - Long to Repay", securitiesCount: 3, sourcedMV: 25662000, totalMV: 25662000 },
];

const mockSourcingLines: SourcingLine[] = [
  // BSK-101
  { id: "L1", basketId: "BSK-101", ticker: "AAPL US", cusip: "037833100", isin: "US0378331005", totalQty: 75000, totalMV: 14887500, remainingQty: 25000, avgBps: 38, indBps: 35, totalAvailable: 120000, totalAllocated: 50000 },
  { id: "L2", basketId: "BSK-101", ticker: "MSFT US", cusip: "594918104", isin: "US5949181045", totalQty: 30000, totalMV: 13356000, remainingQty: 10000, avgBps: 25, indBps: 22, totalAvailable: 85000, totalAllocated: 20000 },
  { id: "L3", basketId: "BSK-101", ticker: "NVDA US", cusip: "67066G104", isin: "US67066G1040", totalQty: 20000, totalMV: 2716000, remainingQty: 20000, avgBps: null, indBps: 55, totalAvailable: 45000, totalAllocated: 0 },
  { id: "L4", basketId: "BSK-101", ticker: "TSLA US", cusip: "88160R101", isin: "US88160R1014", totalQty: 12000, totalMV: 3145800, remainingQty: 12000, avgBps: null, indBps: 85, totalAvailable: 18000, totalAllocated: 0 },
  { id: "L5", basketId: "BSK-101", ticker: "META US", cusip: "30303M102", isin: "US30303M1027", totalQty: 8000, totalMV: 4082400, remainingQty: 8000, avgBps: null, indBps: 40, totalAvailable: 22000, totalAllocated: 0 },
  // BSK-102
  { id: "L6", basketId: "BSK-102", ticker: "SHOP CN", cusip: "82509L107", isin: "CA82509L1076", totalQty: 40000, totalMV: 5692000, remainingQty: 0, avgBps: 30, indBps: 28, totalAvailable: 65000, totalAllocated: 40000 },
  { id: "L7", basketId: "BSK-102", ticker: "RY CN", cusip: "780087102", isin: "CA7800871021", totalQty: 100000, totalMV: 17240000, remainingQty: 0, avgBps: 8, indBps: 7, totalAvailable: 200000, totalAllocated: 100000 },
  { id: "L8", basketId: "BSK-102", ticker: "ENB CN", cusip: "29250N105", isin: "CA29250N1050", totalQty: 150000, totalMV: 8835000, remainingQty: 150000, avgBps: null, indBps: 12, totalAvailable: 180000, totalAllocated: 0 },
  // BSK-103
  { id: "L9", basketId: "BSK-103", ticker: "TD CN", cusip: "891160509", isin: "CA8911605092", totalQty: 60000, totalMV: 4956000, remainingQty: 0, avgBps: 12, indBps: 12, totalAvailable: 90000, totalAllocated: 60000 },
  { id: "L10", basketId: "BSK-103", ticker: "BNS CN", cusip: "064149107", isin: "CA0641491075", totalQty: 80000, totalMV: 5856000, remainingQty: 0, avgBps: 10, indBps: 10, totalAvailable: 120000, totalAllocated: 80000 },
  { id: "L11", basketId: "BSK-103", ticker: "XBB CN", cusip: "46434G109", isin: "CA46434G1090", totalQty: 500000, totalMV: 14850000, remainingQty: 0, avgBps: 5, indBps: 5, totalAvailable: 600000, totalAllocated: 500000 },
];

// Pre-populate some counterparty quotes (simulating RFQ responses)
const initialQuotes: CounterpartyQuote[] = [
  // AAPL quotes
  { counterpartyId: "gs", lineId: "L1", availableQty: 40000, bps: 35, allocated: 30000 },
  { counterpartyId: "ms", lineId: "L1", availableQty: 35000, bps: 42, allocated: 20000 },
  { counterpartyId: "jpm", lineId: "L1", availableQty: 45000, bps: 38, allocated: 0 },
  // MSFT quotes
  { counterpartyId: "gs", lineId: "L2", availableQty: 30000, bps: 22, allocated: 20000 },
  { counterpartyId: "jpm", lineId: "L2", availableQty: 55000, bps: 25, allocated: 0 },
  // SHOP quotes
  { counterpartyId: "bmo", lineId: "L6", availableQty: 50000, bps: 28, allocated: 25000 },
  { counterpartyId: "td", lineId: "L6", availableQty: 30000, bps: 32, allocated: 15000 },
  // RY quotes
  { counterpartyId: "rbc", lineId: "L7", availableQty: 100000, bps: 7, allocated: 60000 },
  { counterpartyId: "bmo", lineId: "L7", availableQty: 80000, bps: 8, allocated: 40000 },
  // TD (lend - BSK-103)
  { counterpartyId: "td", lineId: "L9", availableQty: 60000, bps: 12, allocated: 60000 },
  // BNS
  { counterpartyId: "national", lineId: "L10", availableQty: 80000, bps: 10, allocated: 80000 },
  // XBB.TO
  { counterpartyId: "bmo", lineId: "L11", availableQty: 500000, bps: 5, allocated: 500000 },
];

/* ═══════════════════════════════════════════════════════════════
   BOOKING MODEL & DEFAULTS
   ═══════════════════════════════════════════════════════════════ */

interface BookingTrade {
  id: string;
  basketId: string;
  status: "Pending" | "Submitted" | "Booked" | "Error";
  tradeType: "Borrow" | "Lend";
  ticker: string;
  isin: string;
  cusip: string;
  modelPortfolio: string;
  quantity: number;
  bps: number;
  account: string;
  dealLabel: string;
  tradeDate: string;
  settlementDate: string;
  marketValue: number;
  counterpartyId: string;
  counterpartyName: string;
  validationErrors: string[];
}

// Account mappings — a counterparty can have multiple accounts
const ACCOUNT_MAPPINGS: Record<string, string[]> = {
  gs: ["GS AG TRI950 SF", "GS NA AGT949 SF"],
  ms: ["MS AG TRI840 SF", "MS NA AGT841 SF"],
  jpm: ["JPM AG TRI950 SF", "JPM NA AGT949 SF", "JPM LN AGT952 SF"],
  bmo: ["BMO AG DOM100 SF", "BMO NA DOM101 SF"],
  rbc: ["RBC AG DOM200 SF", "RBC NA DOM201 SF"],
  td: ["TD AG DOM300 SF", "TD NA DOM301 SF"],
  scotiabank: ["BNS AG DOM400 SF"],
  national: ["NBC AG DOM500 SF"],
  citi: ["CITI AG TRI960 SF", "CITI NA AGT961 SF"],
  bnp: ["BNP AG EUR700 SF"],
  hsbc: ["HSBC AG EUR800 SF"],
  seb: ["SEB AG EUR900 SF"],
};

const MODEL_PORTFOLIOS = ["ARTFSLBA", "ARTFCREA", "EQUSFSSA", "FIUGBTAB", "EQUCANBA", "EQUINTBA", "FIUGCABA", "EQUEMRBA", "ARTFMMBA"];
const DEAL_LABELS = ["Auto-SL", "Manual-SL", "Recall-Cover", "Overnight", "Term-7D", "Term-30D", "Open"];

// Mock GC (General Collateral) rates per counterparty (bps) — would come from backend
const GC_RATES: Record<string, number> = {
  bmo: 3.5, rbc: 4.0, td: 3.8, scotiabank: 4.2, national: 3.9,
  gs: 2.5, jpm: 2.8, ms: 3.0, citi: 3.2, bnp: 3.5, hsbc: 3.3, seb: 4.5,
};

// Restricted issuers for validation demo
const RESTRICTED_ISSUERS = ["TSLA US"];

/* ═══════════════════════════════════════════════════════════════
   COMPONENT
   ═══════════════════════════════════════════════════════════════ */

export default function SourcingPage() {
  const { mode } = useThemeMode();
  const gridRef = useRef<AgGridReact>(null);
  const bookingGridRef = useRef<AgGridReact>(null);
  const gridTheme = mode === "dark" ? sfpDarkTheme : sfpLightTheme;

  // State
  const [selectedBasketId, setSelectedBasketId] = useState<string>("BSK-101");
  const [selectedCPsByBasket, setSelectedCPsByBasket] = useState<Record<string, string[]>>({ "BSK-101": ["gs", "ms", "jpm"] });
  const selectedCPs = selectedCPsByBasket[selectedBasketId] ?? [];
  const [rfqSelectedCPs, setRfqSelectedCPs] = useState<Set<string>>(new Set(["gs", "ms", "jpm"]));
  const [rfqSentCPs, setRfqSentCPs] = useState<Record<string, Record<string, { sentAt: string; sentBy: string }>>>({}); 
  const [rfqModalOpen, setRfqModalOpen] = useState(false);
  const [rfqSnackbar, setRfqSnackbar] = useState<{ open: boolean; message: string; severity: "success" | "error" | "info" }>({ open: false, message: "", severity: "info" });
  const [quotes, setQuotes] = useState<CounterpartyQuote[]>(initialQuotes);
  const [bookingDialogOpen, setBookingDialogOpen] = useState(false);

  // Booking state — persist in sessionStorage
  const [bookingTrades, setBookingTrades] = useState<BookingTrade[]>(() => {
    try { const s = sessionStorage.getItem("booking-trades"); return s ? JSON.parse(s) : []; } catch { return []; }
  });
  const [bookingSelectedRows, setBookingSelectedRows] = useState<string[]>([]);
  const [bookingGroupBy, setBookingGroupBy] = useState<string | null>(null);
  // Bulk update fields
  const [bulkMP, setBulkMP] = useState("");
  const [bulkBPS, setBulkBPS] = useState("");
  const [bulkAccount, setBulkAccount] = useState("");
  const [bulkDealLabel, setBulkDealLabel] = useState("");
  const [bulkTradeDate, setBulkTradeDate] = useState("");
  const [bulkSettlementDate, setBulkSettlementDate] = useState("");

  // Persist booking trades to sessionStorage
  useEffect(() => {
    sessionStorage.setItem("booking-trades", JSON.stringify(bookingTrades));
  }, [bookingTrades]);

  // Counterparty dropdown state
  const [cpDropdownOpen, setCpDropdownOpen] = useState(false);
  const [cpSearchTerm, setCpSearchTerm] = useState("");
  const cpAnchorRef = useRef<HTMLDivElement>(null);

  // Security Details expand/collapse (CUSIP/ISIN visibility)
  const [secDetailsExpanded, setSecDetailsExpanded] = useState(false);

  // Current basket
  const selectedBasket = useMemo(() => mockBaskets.find((b) => b.id === selectedBasketId), [selectedBasketId]);

  // Lines for selected basket
  const basketLines = useMemo(() => mockSourcingLines.filter((l) => l.basketId === selectedBasketId), [selectedBasketId]);

  // Reset sourcing grid selection when basket changes
  useEffect(() => { setSelectedRows([]); setRfqSelectedCPs(new Set()); }, [selectedBasketId]);

  // Filtered counterparties for dropdown search
  const filteredCPs = useMemo(() => {
    if (!cpSearchTerm) return COUNTERPARTIES;
    const term = cpSearchTerm.toLowerCase();
    return COUNTERPARTIES.filter((cp) => cp.name.toLowerCase().includes(term) || cp.region.toLowerCase().includes(term));
  }, [cpSearchTerm]);

  // CPs with active allocations in the current basket (always visible, can't be removed)
  const allocatedCPs = useMemo(() => {
    const lineIds = new Set(basketLines.map((l) => l.id));
    const cpIds = new Set<string>();
    quotes.forEach((q) => { if (lineIds.has(q.lineId) && q.allocated > 0) cpIds.add(q.counterpartyId); });
    return cpIds;
  }, [basketLines, quotes]);

  // Effective visible CPs = user-selected + any with allocations (deduplicated, stable order)
  const visibleCPs = useMemo(() => {
    const merged = [...selectedCPs];
    allocatedCPs.forEach((cpId) => { if (!merged.includes(cpId)) merged.push(cpId); });
    return merged;
  }, [selectedCPs, allocatedCPs]);

  // Build grid row data — merge line data with counterparty quotes
  const rowData = useMemo(() => {
    return basketLines.map((line) => {
      const row: Record<string, unknown> = { ...line };
      visibleCPs.forEach((cpId) => {
        const quote = quotes.find((q) => q.lineId === line.id && q.counterpartyId === cpId);
        row[`${cpId}_avbl`] = quote?.availableQty ?? null;
        row[`${cpId}_bps`] = quote?.bps ?? null;
        row[`${cpId}_alloc`] = quote?.allocated ?? 0;
      });
      return row;
    });
  }, [basketLines, visibleCPs, quotes]);

  // Per-CP tile stats: ticker coverage, allocated MV, available MV
  const cpTileStats = useMemo(() => {
    const stats: Record<string, { tickersCovered: number; totalTickers: number; allocatedMV: number; availableMV: number }> = {};
    const totalTickers = basketLines.length;
    visibleCPs.forEach((cpId) => {
      let tickersCovered = 0;
      let allocatedMV = 0;
      let availableMV = 0;
      basketLines.forEach((line) => {
        const price = line.totalQty > 0 ? line.totalMV / line.totalQty : 0;
        const quote = quotes.find((q) => q.lineId === line.id && q.counterpartyId === cpId);
        if (quote && quote.availableQty > 0) {
          tickersCovered++;
          availableMV += quote.availableQty * price;
        }
        if (quote && quote.allocated > 0) {
          allocatedMV += quote.allocated * price;
        }
      });
      stats[cpId] = { tickersCovered, totalTickers, allocatedMV, availableMV };
    });
    return stats;
  }, [basketLines, selectedCPs, quotes]);

  // Row selection state
  const [selectedRows, setSelectedRows] = useState<string[]>([]);

  // Quick Allocate for a counterparty
  const handleQuickAllocate = useCallback((cpId: string) => {
    setQuotes((prev) => {
      const updated = [...prev];
      basketLines.forEach((line) => {
        const existingIdx = updated.findIndex((q) => q.lineId === line.id && q.counterpartyId === cpId);
        if (existingIdx >= 0) {
          const q = updated[existingIdx];
          const allocAmount = Math.min(q.availableQty, line.remainingQty);
          updated[existingIdx] = { ...q, allocated: allocAmount };
        }
      });
      return updated;
    });
  }, [basketLines]);

  // Clear all allocations for a specific CP in the current basket
  const handleClearAllocations = useCallback((cpId: string) => {
    setQuotes((prev) =>
      prev.map((q) =>
        q.counterpartyId === cpId && basketLines.some((l) => l.id === q.lineId) ? { ...q, allocated: 0 } : q
      )
    );
  }, [basketLines]);

  // Toggle RFQ selection for a counterparty
  const handleToggleRfqCP = useCallback((cpId: string) => {
    setRfqSelectedCPs((prev) => {
      const next = new Set(prev);
      if (next.has(cpId)) next.delete(cpId); else next.add(cpId);
      return next;
    });
  }, []);

  // Custom header group for "Security Details" with expand/collapse toggle
  const SecurityDetailsHeader = useCallback((props: Record<string, unknown>) => {
    const expanded = props.expanded as boolean;
    const onToggle = props.onToggle as () => void;
    return (
      <div style={{ display: "flex", alignItems: "center", gap: 4, width: "100%", justifyContent: "center" }}>
        <span style={{ fontSize: "0.72rem", fontWeight: 700 }}>Security Details</span>
        <button
          title={expanded ? "Hide CUSIP/ISIN" : "Show CUSIP/ISIN"}
          onClick={(e: React.MouseEvent) => { e.stopPropagation(); onToggle(); }}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 2, display: "flex", alignItems: "center", fontSize: "0.7rem", fontWeight: 700, color: "#5c9ce6" }}
        >
          {expanded ? "◂" : "▸"}
        </button>
      </div>
    );
  }, []);

  // Custom header group component for counterparty columns (defined inside component to avoid TDZ issues)
  const CpGroupHeader = useCallback((props: Record<string, unknown>) => {
    const displayName = props.displayName as string;
    const cpId = props.cpId as string;
    const onQuickAllocate = props.onQuickAllocate as (cpId: string) => void;
    const onClearAllocations = props.onClearAllocations as (cpId: string) => void;
    return (
      <div style={{ display: "flex", alignItems: "center", gap: 4, width: "100%", justifyContent: "center" }}>
        <span style={{ fontSize: "0.72rem", fontWeight: 700 }}>{displayName}</span>
        <button
          title={`Quick allocate all for ${displayName}`}
          onClick={(e: React.MouseEvent) => { e.stopPropagation(); onQuickAllocate(cpId); }}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 2, display: "flex", alignItems: "center" }}
        >
          <FlashOnIcon sx={{ fontSize: 13, color: "#f59e0b" }} />
        </button>
        <button
          title={`Clear allocations for ${displayName}`}
          onClick={(e: React.MouseEvent) => { e.stopPropagation(); onClearAllocations(cpId); }}
          style={{ background: "none", border: "none", cursor: "pointer", padding: 2, display: "flex", alignItems: "center" }}
        >
          <AutoFixOffIcon sx={{ fontSize: 13, color: "#ef4444" }} />
        </button>
      </div>
    );
  }, []);

  // Toggle security details expand/collapse
  const handleToggleSecDetails = useCallback(() => {
    setSecDetailsExpanded((prev) => !prev);
  }, []);

  // Build dynamic column defs with proper column groups
  const columnDefs: (ColDef | ColGroupDef)[] = useMemo(() => {
    const secDetailChildren: ColDef[] = [
      { headerName: "Ticker", field: "ticker", width: 100, cellStyle: { fontWeight: 700 } },
    ];
    if (secDetailsExpanded) {
      secDetailChildren.push(
        { headerName: "CUSIP", field: "cusip", width: 100 },
        { headerName: "ISIN", field: "isin", width: 130 },
      );
    }
    const securityDetailsGroup: ColGroupDef = {
      headerName: "Security Details",
      headerGroupComponent: SecurityDetailsHeader,
      headerGroupComponentParams: { expanded: secDetailsExpanded, onToggle: handleToggleSecDetails },
      headerClass: "cp-group-header",
      children: secDetailChildren,
    };

    const baseCols: (ColDef | ColGroupDef)[] = [
      securityDetailsGroup,
      { headerName: "Total Qty", field: "totalQty", width: 100, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
      { headerName: "Total MV (QC $)", field: "totalMV", width: 130, type: "numericColumn", valueFormatter: (p) => p.value != null ? `$${p.value.toLocaleString()}` : "" },
      { headerName: "Rem. Qty", field: "remainingQty", width: 95, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "", cellStyle: (p) => p.value > 0 ? { color: "#f59e0b", fontWeight: 600 } : undefined },
      { headerName: "Avg. BPS", field: "avgBps", width: 80, type: "numericColumn" },
      { headerName: "Ind. BPS", field: "indBps", width: 80, type: "numericColumn" },
      { headerName: "Total Available", field: "totalAvailable", width: 115, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
      { headerName: "Total Allocated", field: "totalAllocated", width: 115, type: "numericColumn", valueFormatter: (p) => p.value?.toLocaleString() ?? "", cellStyle: (p) => { const line = p.data as SourcingLine; return line && p.value === line.totalQty ? { color: "#10b981", fontWeight: 700 } : undefined; } },
    ];

    // Add column groups per visible counterparty (2-row header: group name row + child column row)
    visibleCPs.forEach((cpId) => {
      const cp = COUNTERPARTIES.find((c) => c.id === cpId);
      const cpName = cp?.name ?? cpId;

      const cpGroup: ColGroupDef = {
        headerName: cpName,
        headerClass: "cp-group-header",
        headerGroupComponent: CpGroupHeader,
        headerGroupComponentParams: { cpId, onQuickAllocate: handleQuickAllocate, onClearAllocations: handleClearAllocations },
        marryChildren: true,
        children: [
          {
            headerName: "Avbl. Qty",
            field: `${cpId}_avbl`,
            width: 95,
            type: "numericColumn",
            headerClass: "cp-child-header",
            cellClass: "cp-alloc-cell",
            valueFormatter: (p) => p.value != null ? p.value.toLocaleString() : "—",
            cellStyle: { color: "#6b7280" },
          },
          {
            headerName: "Bps",
            field: `${cpId}_bps`,
            width: 65,
            type: "numericColumn",
            headerClass: "cp-child-header",
            cellClass: "cp-alloc-cell",
            valueFormatter: (p) => p.value != null ? String(p.value) : "—",
          },
          {
            headerName: "Allocated",
            field: `${cpId}_alloc`,
            width: 95,
            type: "numericColumn",
            editable: true,
            headerClass: "cp-child-header",
            cellClass: "cp-alloc-cell",
            valueFormatter: (p) => p.value != null && p.value > 0 ? p.value.toLocaleString() : "",
            cellStyle: (p) => p.value > 0 ? { fontWeight: 700, color: "#3b82f6" } : undefined,
          },
        ],
      };
      baseCols.push(cpGroup);
    });

    return baseCols;
  }, [visibleCPs, CpGroupHeader, handleQuickAllocate, handleClearAllocations, SecurityDetailsHeader, secDetailsExpanded, handleToggleSecDetails]);

  // Persist column state in sessionStorage
  const COLUMN_STATE_KEY = "sourcing-grid-col-state";

  const onGridReady = useCallback((event: GridReadyEvent) => {
    const saved = sessionStorage.getItem(COLUMN_STATE_KEY);
    if (saved) {
      try { event.api.applyColumnState({ state: JSON.parse(saved), applyOrder: true }); } catch { /* ignore */ }
    } else {
      event.api.sizeColumnsToFit();
    }
  }, []);

  const onColumnStateChanged = useCallback(() => {
    if (!gridRef.current?.api) return;
    const state = gridRef.current.api.getColumnState();
    sessionStorage.setItem(COLUMN_STATE_KEY, JSON.stringify(state));
  }, []);

  // Handle allocation edit
  const onCellValueChanged = useCallback((event: CellValueChangedEvent) => {
    const field = event.colDef.field;
    if (!field || !field.endsWith("_alloc")) return;
    const cpId = field.replace("_alloc", "");
    const lineId = (event.data as SourcingLine).id;
    const newVal = Number(event.newValue) || 0;

    setQuotes((prev) => {
      const existing = prev.find((q) => q.lineId === lineId && q.counterpartyId === cpId);
      if (existing) {
        return prev.map((q) => q.lineId === lineId && q.counterpartyId === cpId ? { ...q, allocated: newVal } : q);
      }
      return [...prev, { counterpartyId: cpId, lineId, availableQty: 0, bps: 0, allocated: newVal }];
    });
  }, []);

  // Toggle counterparty selection (per-basket) — also auto-select for RFQ
  const handleToggleCP = (cpId: string) => {
    setSelectedCPsByBasket((prev) => {
      const current = prev[selectedBasketId] ?? [];
      const isAdding = !current.includes(cpId);
      const updated = isAdding ? [...current, cpId] : current.filter((id) => id !== cpId);
      // Auto-add to RFQ selection when adding a CP (if not already sent)
      if (isAdding && !(rfqSentCPs[selectedBasketId]?.[cpId])) {
        setRfqSelectedCPs((p) => { const n = new Set(p); n.add(cpId); return n; });
      } else if (!isAdding) {
        setRfqSelectedCPs((p) => { const n = new Set(p); n.delete(cpId); return n; });
      }
      return { ...prev, [selectedBasketId]: updated };
    });
  };

  // Remove a selected CP tile (per-basket)
  const handleRemoveCP = (cpId: string) => {
    setSelectedCPsByBasket((prev) => {
      const current = prev[selectedBasketId] ?? [];
      return { ...prev, [selectedBasketId]: current.filter((id) => id !== cpId) };
    });
    setRfqSelectedCPs((p) => { const n = new Set(p); n.delete(cpId); return n; });
  };

  // RFQ Modal state
  const [rfqModalCpBpsOverride, setRfqModalCpBpsOverride] = useState<Record<string, string>>({}); // per-CP BPS override
  const [rfqModalCpQtySource, setRfqModalCpQtySource] = useState<Record<string, "totalQty" | "remainingQty">>({}); // per-CP qty source
  const [rfqModalCpSettlement, setRfqModalCpSettlement] = useState<Record<string, "FOP" | "DVP">>({}); // per-CP settlement type
  const [rfqModalTickerBps, setRfqModalTickerBps] = useState<Record<string, string>>({}); // per-ticker override
  const [rfqModalCPs, setRfqModalCPs] = useState<string[]>([]);

  // Open RFQ modal — initialize modal CPs from current rfqSelectedCPs
  const openRfqModal = useCallback(() => {
    setRfqModalCPs([...rfqSelectedCPs]);
    setRfqModalCpBpsOverride({});
    setRfqModalCpQtySource({});
    setRfqModalCpSettlement({});
    setRfqModalTickerBps({});
    setRfqModalOpen(true);
  }, [rfqSelectedCPs]);

  // Confirm and send RFQ from modal — fires one POST /api/rfq per counterparty
  const handleConfirmSendRFQ = useCallback(async () => {
    const now = new Date().toLocaleString();
    let successCount = 0;
    let totalLines = 0;

    for (const cpId of rfqModalCPs) {
      const cp = COUNTERPARTIES.find((c) => c.id === cpId);
      const gcRate = GC_RATES[cpId] ?? 3.0;
      const cpBpsOverride = rfqModalCpBpsOverride[cpId] ?? "";
      const cpQtySource = rfqModalCpQtySource[cpId] ?? "totalQty";
      const cpSettlement = rfqModalCpSettlement[cpId] ?? "FOP";
      const today = new Date().toISOString().slice(0, 10);
      const rfqLines = basketLines
        .map((line) => {
          const qty = cpQtySource === "totalQty" ? line.totalQty : line.remainingQty;
          if (qty <= 0) return null;
          const tickerBps = rfqModalTickerBps[line.ticker];
          const bps = tickerBps ? parseFloat(tickerBps) : (cpBpsOverride ? parseFloat(cpBpsOverride) : gcRate);
          return {
            securityIdentifiers: [
              { idType: "TICKER", idValue: line.ticker },
              { idType: "CUSIP", idValue: line.cusip },
              { idType: "ISIN", idValue: line.isin },
            ],
            bidQuantity: qty,
            bidRate: isNaN(bps) ? gcRate : bps,
            country: "CA",
            collateralType: "CASH",
            collateralCurrency: "USD",
            loanSettlementDate: today,
            settlementType: cpSettlement,
          };
        })
        .filter((s): s is NonNullable<typeof s> => s !== null);

      if (rfqLines.length === 0) continue;

      const rfqData: RfqData = {
        borrowerEntityId: "HOOPP",
        borrowerParentId: "HOOPP",
        lenderEntityId: cpId,
        lenderParentId: cp?.name ?? cpId,
        requestForQuotes: rfqLines,
      };

      const result = await submitRfq(rfqData);
      if (result.success) {
        successCount++;
      } else {
        console.warn(`[RFQ] API returned error for ${cp?.name ?? cpId}:`, result.error);
      }
      // Count as sent regardless (prototype — endpoint may not exist yet)
      totalLines += rfqLines.length;
    }

    // Mark CPs as sent (always proceed for prototype)
    const sentUpdate: Record<string, { sentAt: string; sentBy: string }> = {};
    rfqModalCPs.forEach((cpId) => { sentUpdate[cpId] = { sentAt: now, sentBy: "Alex (you)" }; });
    setRfqSentCPs((prev) => ({ ...prev, [selectedBasketId]: { ...prev[selectedBasketId], ...sentUpdate } }));

    // Clear selections
    setRfqSelectedCPs(new Set());
    setRfqModalOpen(false);

    const cpCount = rfqModalCPs.length;
    if (successCount === cpCount) {
      setRfqSnackbar({ open: true, message: `RFQ sent to ${cpCount} counterpart${cpCount > 1 ? "ies" : "y"} (${totalLines} lines)`, severity: "success" });
    } else if (successCount > 0) {
      setRfqSnackbar({ open: true, message: `RFQ sent (${successCount}/${cpCount} succeeded, ${totalLines} lines). Some calls returned errors.`, severity: "info" });
    } else {
      setRfqSnackbar({ open: true, message: `RFQ recorded locally (${cpCount} CP${cpCount > 1 ? "s" : ""}, ${totalLines} lines). API endpoint not available — calls will retry when backend is ready.`, severity: "info" });
    }
  }, [basketLines, rfqModalCPs, rfqModalCpBpsOverride, rfqModalCpQtySource, rfqModalCpSettlement, rfqModalTickerBps, selectedBasketId]);

  // ═══ GENERATE TRADES — creates BookingTrade rows from ALL allocations in the basket ═══
  const handleGenerateTrades = useCallback(() => {
    const today = new Date().toISOString().slice(0, 10);
    const t1 = new Date(Date.now() + 86400000).toISOString().slice(0, 10);
    const trades: BookingTrade[] = [];
    let counter = 1;

    basketLines.forEach((line) => {
      // Find ALL quotes with allocations for this line (not limited to selectedCPs)
      const lineQuotes = quotes.filter((q) => q.lineId === line.id && q.allocated > 0);
      lineQuotes.forEach((quote) => {
        const cpId = quote.counterpartyId;
        const cp = COUNTERPARTIES.find((c) => c.id === cpId);
        const cpName = cp?.name ?? cpId;
        const price = line.totalQty > 0 ? line.totalMV / line.totalQty : 0;
        const mv = quote.allocated * price;
        const accounts = ACCOUNT_MAPPINGS[cpId] ?? [];
        const defaultAccount = accounts[0] ?? "";

        // Validation
        const errors: string[] = [];
        if (RESTRICTED_ISSUERS.includes(line.ticker)) errors.push("Restricted issuer");

        trades.push({
          id: `BKG-${String(counter++).padStart(4, "0")}`,
          basketId: selectedBasketId,
          status: errors.length > 0 ? "Error" : "Pending",
          tradeType: "Borrow",
          ticker: line.ticker,
          isin: line.isin,
          cusip: line.cusip,
          modelPortfolio: MODEL_PORTFOLIOS[0],
          quantity: quote.allocated,
          bps: quote.bps,
          account: defaultAccount,
          dealLabel: DEAL_LABELS[0],
          tradeDate: today,
          settlementDate: t1,
          marketValue: mv,
          counterpartyId: cpId,
          counterpartyName: cpName,
          validationErrors: errors,
        });
      });
    });
    // Replace trades for current basket, keep trades from other baskets
    setBookingTrades((prev) => [...prev.filter((t) => t.basketId !== selectedBasketId), ...trades]);
    setBookingSelectedRows([]);
  }, [basketLines, quotes, selectedBasketId]);

  // Bulk apply handler
  const handleBulkApply = useCallback(() => {
    if (bookingSelectedRows.length === 0) return;
    setBookingTrades((prev) => prev.map((t) => {
      if (!bookingSelectedRows.includes(t.id)) return t;
      const updated = { ...t };
      if (bulkMP) updated.modelPortfolio = bulkMP;
      if (bulkBPS) updated.bps = Number(bulkBPS);
      if (bulkAccount) updated.account = bulkAccount;
      if (bulkDealLabel) updated.dealLabel = bulkDealLabel;
      if (bulkTradeDate) updated.tradeDate = bulkTradeDate;
      if (bulkSettlementDate) updated.settlementDate = bulkSettlementDate;
      // Re-validate
      const errors: string[] = [];
      if (RESTRICTED_ISSUERS.includes(updated.ticker)) errors.push("Restricted issuer");
      if (updated.tradeDate > updated.settlementDate) errors.push("Trade date after settlement date");
      updated.validationErrors = errors;
      updated.status = errors.length > 0 ? "Error" : updated.status === "Error" ? "Pending" : updated.status;
      return updated;
    }));
  }, [bookingSelectedRows, bulkMP, bulkBPS, bulkAccount, bulkDealLabel, bulkTradeDate, bulkSettlementDate]);

  // Delete selected booking rows
  const handleDeleteBookingRows = useCallback(() => {
    if (bookingSelectedRows.length === 0) return;
    setBookingTrades((prev) => prev.filter((t) => !bookingSelectedRows.includes(t.id)));
    setBookingSelectedRows([]);
  }, [bookingSelectedRows]);

  // All possible accounts from visible CPs (for bulk dropdown)
  const allAccounts = useMemo(() => {
    const accts: string[] = [];
    visibleCPs.forEach((cpId) => { (ACCOUNT_MAPPINGS[cpId] ?? []).forEach((a) => { if (!accts.includes(a)) accts.push(a); }); });
    return accts;
  }, [visibleCPs]);

  // Booking grid column defs
  const bookingColumnDefs = useMemo(() => [
    { headerName: "", colId: "warning", width: 40, sortable: false, filter: false, resizable: false, suppressHeaderMenuButton: true,
      cellRenderer: (p: { data?: BookingTrade }) => {
        if (!p.data || p.data.validationErrors.length === 0) return null;
        return <Tooltip title={p.data.validationErrors.join("; ")}><WarningAmberIcon sx={{ fontSize: 15, color: "#ef4444" }} /></Tooltip>;
      },
      cellStyle: { display: "flex", justifyContent: "center", alignItems: "center" },
    },
    { headerName: "Status", field: "status", width: 90,
      cellStyle: (p) => {
        if (p.value === "Error") return { color: "#ef4444", fontWeight: 700 };
        if (p.value === "Pending") return { color: "#f59e0b", fontWeight: 600 };
        if (p.value === "Submitted") return { color: "#3b82f6", fontWeight: 600 };
        if (p.value === "Booked") return { color: "#10b981", fontWeight: 700 };
        return undefined;
      },
    },
    { headerName: "Trade Type", field: "tradeType", width: 95 },
    { headerName: "Ticker", field: "ticker", width: 90, cellStyle: { fontWeight: 700 } },
    { headerName: "ISIN", field: "isin", width: 130 },
    { headerName: "CUSIP", field: "cusip", width: 100 },
    { headerName: "Model Portfolio", field: "modelPortfolio", width: 155, editable: true,
      cellEditor: "agSelectCellEditor", cellEditorParams: { values: MODEL_PORTFOLIOS } },
    { headerName: "Quantity", field: "quantity", width: 100, type: "numericColumn",
      valueFormatter: (p) => p.value?.toLocaleString() ?? "" },
    { headerName: "BPS", field: "bps", width: 70, type: "numericColumn", editable: true },
    { headerName: "Account", field: "account", width: 160, editable: true,
      cellEditor: "agSelectCellEditor",
      cellEditorParams: (p: { data: BookingTrade }) => ({ values: ACCOUNT_MAPPINGS[p.data.counterpartyId] ?? [] }) },
    { headerName: "Deal Label", field: "dealLabel", width: 110, editable: true,
      cellEditor: "agSelectCellEditor", cellEditorParams: { values: DEAL_LABELS } },
    { headerName: "Trade Date", field: "tradeDate", width: 110, editable: true },
    { headerName: "Settlement", field: "settlementDate", width: 110, editable: true },
    { headerName: "Market Value", field: "marketValue", width: 130, type: "numericColumn",
      valueFormatter: (p) => p.value != null ? `$${p.value.toLocaleString(undefined, { maximumFractionDigits: 0 })}` : "" },
  ] as ColDef<BookingTrade>[], []);

  // Booking group-by config
  const bookingAutoGroupColumnDef: ColDef = useMemo(() => ({
    headerName: "Group",
    minWidth: 160,
    cellRendererParams: { suppressCount: false },
  }), []);

  const bookingRowGrouping = useMemo(() => {
    if (bookingGroupBy === "allocation") return "ticker";
    if (bookingGroupBy === "counterparty") return "account";
    return null;
  }, [bookingGroupBy]);

  // Filtered booking trades for current basket
  const filteredBookingTrades = useMemo(() => bookingTrades.filter((t) => t.basketId === selectedBasketId), [bookingTrades, selectedBasketId]);

  return (
    <Box sx={{ display: "flex", flexDirection: "column", height: "100%" }}>

      {/* ═══ TOP ROW: Baskets | Counterparties | Sourcing Grid ═══ */}
      <Box sx={{ display: "flex", flex: 1, minHeight: 0, overflow: "hidden" }}>

      {/* ═══ LEFT PANEL — BASKETS ═══ */}
      <Box sx={{ width: 220, minWidth: 120, display: "flex", flexDirection: "column", borderRight: 1, borderRightColor: "divider", overflow: "auto", resize: "horizontal" }}>
        <Typography sx={{ fontWeight: 700, fontSize: "0.8rem", textTransform: "uppercase", px: 1.5, pt: 1.5, pb: 0.5, color: "text.secondary" }}>
          Baskets
        </Typography>
        <Box sx={{ flex: 1, overflow: "auto", px: 1 }}>
          {mockBaskets.map((basket) => {
            const pct = basket.totalMV > 0 ? Math.round((basket.sourcedMV / basket.totalMV) * 100) : 0;
            const isSelected = basket.id === selectedBasketId;
            return (
              <Paper
                key={basket.id}
                elevation={isSelected ? 3 : 0}
                onClick={() => setSelectedBasketId(basket.id)}
                sx={{
                  p: 1.5, mb: 1, cursor: "pointer", borderRadius: 1.5,
                  border: isSelected ? 2 : 1,
                  borderColor: isSelected ? "primary.main" : "divider",
                  bgcolor: isSelected ? (mode === "dark" ? "#1e3a5f" : "#eff6ff") : "background.paper",
                  transition: "all 0.15s",
                  "&:hover": { borderColor: "primary.light" },
                }}
              >
                <Typography sx={{ fontWeight: 700, fontSize: "0.78rem", mb: 0.5 }}>{basket.name}</Typography>
                <Typography sx={{ fontSize: "0.7rem", color: "text.secondary", mb: 0.75 }}>
                  {basket.securitiesCount} securities
                </Typography>
                <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 0.5 }}>
                  <LinearProgress
                    variant="determinate"
                    value={pct}
                    color={pct >= 100 ? "success" : pct > 50 ? "primary" : "warning"}
                    sx={{ flex: 1, height: 8, borderRadius: 4 }}
                  />
                  <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, minWidth: 30 }}>{pct}%</Typography>
                </Box>
                <Box sx={{ display: "flex", justifyContent: "space-between" }}>
                  <Typography sx={{ fontSize: "0.65rem", color: "text.secondary" }}>
                    Sourced: ${(basket.sourcedMV / 1e6).toFixed(1)}M
                  </Typography>
                  <Typography sx={{ fontSize: "0.65rem", color: "text.secondary" }}>
                    Total: ${(basket.totalMV / 1e6).toFixed(1)}M
                  </Typography>
                </Box>
              </Paper>
            );
          })}
        </Box>
      </Box>

      {/* ═══ COUNTERPARTIES PANEL (narrow vertical) ═══ */}
      <Box sx={{ width: 220, minWidth: 160, display: "flex", flexDirection: "column", borderRight: 1, borderRightColor: "divider", overflow: "hidden", resize: "horizontal" }}>
        <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", px: 1.5, pt: 1.5, pb: 0.5 }}>
          <Typography sx={{ fontWeight: 700, fontSize: "0.75rem", textTransform: "uppercase", color: "text.secondary" }}>
            Counterparties
          </Typography>
          <Button
            variant="outlined"
            size="small"
            disabled={rfqSelectedCPs.size === 0}
            onClick={openRfqModal}
            sx={{ textTransform: "none", fontWeight: 600, fontSize: "0.7rem", minWidth: 0, px: 1, py: 0.25, lineHeight: 1.4, borderColor: "#10b981", color: "#10b981", "&:hover": { borderColor: "#059669", bgcolor: "rgba(16,185,129,0.08)" } }}
          >
            RFQ{rfqSelectedCPs.size > 0 ? ` (${rfqSelectedCPs.size})` : ""}
          </Button>
        </Box>
        <Box sx={{ px: 1.5, pb: 0.5 }}>
          <Typography
            component="span"
            onClick={() => {
              const unsent = selectedCPs.filter((id) => !rfqSentCPs[selectedBasketId]?.[id]);
              const allSelected = unsent.length > 0 && rfqSelectedCPs.size === unsent.length && unsent.every((id) => rfqSelectedCPs.has(id));
              setRfqSelectedCPs(allSelected ? new Set() : new Set(unsent));
            }}
            sx={{ fontSize: "0.68rem", color: "primary.main", cursor: "pointer", "&:hover": { textDecoration: "underline" } }}
          >
            {rfqSelectedCPs.size === selectedCPs.filter((id) => !rfqSentCPs[selectedBasketId]?.[id]).length && rfqSelectedCPs.size > 0 ? "Deselect All" : "Select All"}
          </Typography>
        </Box>

        {/* Searchable dropdown */}
        <Box sx={{ px: 1, pb: 1 }} ref={cpAnchorRef}>
          <TextField
            size="small"
            fullWidth
            placeholder="Search & select..."
            value={cpSearchTerm}
            onChange={(e) => { setCpSearchTerm(e.target.value); setCpDropdownOpen(true); }}
            onClick={() => setCpDropdownOpen(true)}
            slotProps={{
              input: {
                startAdornment: <InputAdornment position="start"><SearchIcon sx={{ fontSize: 14 }} /></InputAdornment>,
                endAdornment: <InputAdornment position="end"><ArrowDropDownIcon sx={{ fontSize: 16, cursor: "pointer" }} onClick={() => setCpDropdownOpen(!cpDropdownOpen)} /></InputAdornment>,
                sx: { fontSize: "0.75rem", height: 32 },
              },
            }}
          />
          <Popper open={cpDropdownOpen} anchorEl={cpAnchorRef.current} placement="bottom-start" sx={{ zIndex: 1300, width: 240 }}>
            <ClickAwayListener onClickAway={() => setCpDropdownOpen(false)}>
              <Paper elevation={4} sx={{ maxHeight: 250, overflow: "auto", mt: 0.5, border: 1, borderColor: "divider" }}>
                <List dense disablePadding>
                  {filteredCPs.map((cp) => (
                    <ListItemButton key={cp.id} onClick={() => handleToggleCP(cp.id)} sx={{ py: 0.3 }}>
                      <ListItemIcon sx={{ minWidth: 28 }}>
                        <Checkbox size="small" checked={selectedCPs.includes(cp.id)} sx={{ p: 0 }} />
                      </ListItemIcon>
                      <ListItemText
                        primary={cp.name}
                        secondary={cp.region}
                        slotProps={{ primary: { sx: { fontSize: "0.73rem" } }, secondary: { sx: { fontSize: "0.63rem" } } }}
                      />
                    </ListItemButton>
                  ))}
                  {filteredCPs.length === 0 && (
                    <Typography sx={{ px: 2, py: 1, fontSize: "0.75rem", color: "text.secondary" }}>No matches</Typography>
                  )}
                </List>
              </Paper>
            </ClickAwayListener>
          </Popper>
        </Box>

        {/* Selected counterparty tiles */}
        <Box sx={{ flex: 1, overflow: "auto", px: 1 }}>
          {visibleCPs.map((cpId) => {
            const cp = COUNTERPARTIES.find((c) => c.id === cpId);
            if (!cp) return null;
            const stats = cpTileStats[cpId];
            const hasAllocations = allocatedCPs.has(cpId);
            const sentInfo = rfqSentCPs[selectedBasketId]?.[cpId];
            const isSent = !!sentInfo;
            return (
              <Paper
                key={cpId}
                variant="outlined"
                sx={{ p: 0.75, mb: 0.75, borderRadius: 1, borderColor: hasAllocations ? "primary.main" : undefined }}
              >
                <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                  <Tooltip title={isSent ? `RFQ sent ${sentInfo.sentAt} by ${sentInfo.sentBy}` : rfqSelectedCPs.has(cpId) ? "Selected for RFQ" : "Click to include in RFQ"}>
                    <span>
                      <Checkbox
                        size="small"
                        checked={rfqSelectedCPs.has(cpId) || isSent}
                        disabled={isSent}
                        onChange={() => handleToggleRfqCP(cpId)}
                        sx={{ p: 0, mr: 0.3, '& .MuiSvgIcon-root': { fontSize: 16 }, ...(isSent ? { '&.Mui-disabled': { color: "#9e9e9e" } } : {}) }}
                      />
                    </span>
                  </Tooltip>
                  <Box sx={{ flex: 1, minWidth: 0 }}>
                    <Typography sx={{ fontSize: "0.72rem", fontWeight: 600, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>
                      {cp.name}
                    </Typography>
                    <Typography sx={{ fontSize: "0.62rem", color: "text.secondary" }}>{cp.region}</Typography>
                  </Box>
                  <Tooltip title={hasAllocations ? "Has allocations — cannot remove" : "Remove"}>
                    <span>
                      <IconButton size="small" onClick={() => handleRemoveCP(cpId)} disabled={hasAllocations} sx={{ p: 0.3 }}>
                        <CloseIcon sx={{ fontSize: 12 }} />
                      </IconButton>
                    </span>
                  </Tooltip>
                </Box>
                {stats && (
                  <Box sx={{ mt: 0.5, pt: 0.5, borderTop: 1, borderColor: "divider" }}>
                    <Box sx={{ display: "flex", justifyContent: "space-between", mb: 0.2 }}>
                      <Typography sx={{ fontSize: "0.6rem", color: "text.secondary" }}>Ticker Coverage:</Typography>
                      <Typography sx={{ fontSize: "0.6rem", fontWeight: 700 }}>{stats.tickersCovered}/{stats.totalTickers}</Typography>
                    </Box>
                    <Box sx={{ display: "flex", justifyContent: "space-between", mb: 0.2 }}>
                      <Typography sx={{ fontSize: "0.6rem", color: "text.secondary" }}>Allocated MV (USD):</Typography>
                      <Typography sx={{ fontSize: "0.6rem", fontWeight: 700 }}>${stats.allocatedMV >= 1e6 ? `${(stats.allocatedMV / 1e6).toFixed(2)}M` : stats.allocatedMV.toLocaleString(undefined, { maximumFractionDigits: 0 })}</Typography>
                    </Box>
                    <Box sx={{ display: "flex", justifyContent: "space-between" }}>
                      <Typography sx={{ fontSize: "0.6rem", color: "text.secondary" }}>Available MV (USD):</Typography>
                      <Typography sx={{ fontSize: "0.6rem", fontWeight: 700 }}>${stats.availableMV >= 1e6 ? `${(stats.availableMV / 1e6).toFixed(2)}M` : stats.availableMV.toLocaleString(undefined, { maximumFractionDigits: 0 })}</Typography>
                    </Box>
                  </Box>
                )}
              </Paper>
            );
          })}
          {visibleCPs.length === 0 && (
            <Typography sx={{ fontSize: "0.72rem", color: "text.secondary", textAlign: "center", mt: 2 }}>
              Select counterparties above
            </Typography>
          )}
        </Box>
      </Box>

      {/* ═══ RIGHT — SOURCING DETAIL GRID ═══ */}
      <Box sx={{ flex: 1, display: "flex", flexDirection: "column", minWidth: 0, overflow: "hidden" }}>

        {/* SOURCING GRID */}
        <Box sx={{ px: 1.5, pt: 1, flex: 1, minHeight: 0, overflow: "hidden" }}>
          <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 0.5 }}>
            <Typography sx={{ fontWeight: 700, fontSize: "0.8rem", textTransform: "uppercase", color: "text.secondary" }}>
              Sourcing — {selectedBasket?.name ?? ""}
            </Typography>
            <Box sx={{ display: "flex", gap: 1 }}>
              <Button
                variant="contained"
                size="small"
                disabled={selectedRows.length === 0}
                onClick={handleGenerateTrades}
                sx={{ textTransform: "none", fontWeight: 600, fontSize: "0.76rem", bgcolor: "#6366f1", "&:hover": { bgcolor: "#4f46e5" } }}
              >
                Generate Trades{selectedRows.length > 0 ? ` (${selectedRows.length})` : ""}
              </Button>
            </Box>
          </Box>
          <Box sx={{ height: "calc(100% - 32px)" }} className="sourcing-grid-container">
            <AgGridReact
              ref={gridRef}
              theme={gridTheme}
              rowData={rowData}
              columnDefs={columnDefs}
              onGridReady={onGridReady}
              onCellValueChanged={onCellValueChanged}
              onColumnResized={onColumnStateChanged}
              onColumnMoved={onColumnStateChanged}
              onColumnVisible={onColumnStateChanged}
              onColumnPinned={onColumnStateChanged}
              onSortChanged={onColumnStateChanged}
              getRowId={(params) => params.data.id}
              suppressCellFocus={false}
              animateRows
              rowHeight={32}
              headerHeight={28}
              groupHeaderHeight={30}
              rowSelection={{ mode: "multiRow", checkboxes: true, headerCheckbox: true }}
              selectionColumnDef={{ pinned: "left", width: 40, resizable: false, suppressHeaderMenuButton: true }}
              onSelectionChanged={(e) => {
                const selected = e.api.getSelectedRows().map((r: Record<string, unknown>) => r.id as string);
                setSelectedRows(selected);
              }}
              singleClickEdit
            />
          </Box>
        </Box>
      </Box>{/* end right panel */}
      </Box>{/* end top row */}

      {/* ═══ BOTTOM — BOOKING SECTION (full width) ═══ */}
      <Box sx={{ borderTop: 1, borderTopColor: "divider", px: 1.5, py: 1, height: filteredBookingTrades.length > 0 ? 300 : "auto", minHeight: 50, display: "flex", flexDirection: "column", resize: "vertical", overflow: "auto" }}>
          {/* Booking header bar */}
          <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 0.5 }}>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
              <Typography sx={{ fontWeight: 700, fontSize: "0.8rem", textTransform: "uppercase", color: "text.secondary" }}>
                Booking
              </Typography>
              {filteredBookingTrades.length > 0 && (
                <Typography sx={{ fontSize: "0.7rem", color: "text.secondary" }}>
                  {filteredBookingTrades.length} trade{filteredBookingTrades.length !== 1 ? "s" : ""}
                  {bookingSelectedRows.length > 0 && ` · ${bookingSelectedRows.length} selected`}
                </Typography>
              )}
            </Box>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
              {/* Group By toggles */}
              {filteredBookingTrades.length > 0 && (
                <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                  <Typography sx={{ fontSize: "0.68rem", color: "text.secondary", mr: 0.5 }}>Group By:</Typography>
                  <ToggleButtonGroup
                    size="small"
                    exclusive
                    value={bookingGroupBy}
                    onChange={(_e, val) => setBookingGroupBy(val)}
                    sx={{ height: 24 }}
                  >
                    <ToggleButton value="allocation" sx={{ fontSize: "0.68rem", px: 1, py: 0, textTransform: "none" }}>Allocation</ToggleButton>
                    <ToggleButton value="counterparty" sx={{ fontSize: "0.68rem", px: 1, py: 0, textTransform: "none" }}>Counterparty</ToggleButton>
                  </ToggleButtonGroup>
                </Box>
              )}
            </Box>
          </Box>

          {/* Bulk update bar */}
          {filteredBookingTrades.length > 0 && (
            <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 0.5, flexWrap: "wrap" }}>
              <Typography sx={{ fontSize: "0.65rem", color: "text.secondary", fontWeight: 600, mr: 0.5 }}>Bulk Update:</Typography>
              <Select size="small" displayEmpty value={bulkMP} onChange={(e) => setBulkMP(e.target.value)}
                sx={{ fontSize: "0.7rem", height: 24, minWidth: 130 }}>
                <MenuItem value="" sx={{ fontSize: "0.7rem" }}><em>Model Portfolio</em></MenuItem>
                {MODEL_PORTFOLIOS.map((mp) => <MenuItem key={mp} value={mp} sx={{ fontSize: "0.7rem" }}>{mp}</MenuItem>)}
              </Select>
              <TextField size="small" placeholder="BPS" value={bulkBPS} onChange={(e) => setBulkBPS(e.target.value)}
                sx={{ width: 55, "& input": { fontSize: "0.7rem", py: "2px", px: "6px" } }} slotProps={{ input: { sx: { height: 24 } } }} />
              <Select size="small" displayEmpty value={bulkAccount} onChange={(e) => setBulkAccount(e.target.value)}
                sx={{ fontSize: "0.7rem", height: 24, minWidth: 140 }}>
                <MenuItem value="" sx={{ fontSize: "0.7rem" }}><em>Account</em></MenuItem>
                {allAccounts.map((a) => <MenuItem key={a} value={a} sx={{ fontSize: "0.7rem" }}>{a}</MenuItem>)}
              </Select>
              <Select size="small" displayEmpty value={bulkDealLabel} onChange={(e) => setBulkDealLabel(e.target.value)}
                sx={{ fontSize: "0.7rem", height: 24, minWidth: 100 }}>
                <MenuItem value="" sx={{ fontSize: "0.7rem" }}><em>Deal Label</em></MenuItem>
                {DEAL_LABELS.map((d) => <MenuItem key={d} value={d} sx={{ fontSize: "0.7rem" }}>{d}</MenuItem>)}
              </Select>
              <TextField size="small" type="date" value={bulkTradeDate} onChange={(e) => setBulkTradeDate(e.target.value)}
                sx={{ width: 120, "& input": { fontSize: "0.7rem", py: "2px", px: "4px" } }} slotProps={{ input: { sx: { height: 24 } } }} />
              <TextField size="small" type="date" value={bulkSettlementDate} onChange={(e) => setBulkSettlementDate(e.target.value)}
                sx={{ width: 120, "& input": { fontSize: "0.7rem", py: "2px", px: "4px" } }} slotProps={{ input: { sx: { height: 24 } } }} />
              <Button variant="contained" size="small" onClick={handleBulkApply} disabled={bookingSelectedRows.length === 0}
                sx={{ textTransform: "none", fontSize: "0.7rem", fontWeight: 600, height: 24, minWidth: 50 }}>
                Apply
              </Button>
            </Box>
          )}

          {/* Booking AG Grid */}
          {filteredBookingTrades.length > 0 ? (
            <Box sx={{ flex: 1, minHeight: 0 }}>
              <AgGridReact
                key={`booking-grid-${bookingGroupBy ?? "none"}`}
                ref={bookingGridRef}
                theme={gridTheme}
                rowData={filteredBookingTrades}
                columnDefs={bookingRowGrouping
                  ? bookingColumnDefs.map((c) => c.field === bookingRowGrouping ? { ...c, rowGroup: true, hide: true } : c)
                  : bookingColumnDefs}
                getRowId={(params) => params.data.id}
                rowHeight={30}
                headerHeight={28}
                animateRows
                rowSelection={{ mode: "multiRow", checkboxes: true, headerCheckbox: true }}
                selectionColumnDef={{ width: 36, resizable: false, suppressHeaderMenuButton: true }}
                onSelectionChanged={(e) => {
                  const sel = e.api.getSelectedRows().map((r: BookingTrade) => r.id);
                  setBookingSelectedRows(sel);
                }}
                {...(bookingRowGrouping ? { rowGroupPanelShow: "never" as const, groupDefaultExpanded: -1, autoGroupColumnDef: bookingAutoGroupColumnDef } : {})}
                singleClickEdit
                suppressCellFocus={false}
              />
            </Box>
          ) : (
            <Box sx={{ display: "flex", alignItems: "center", justifyContent: "center", py: 2 }}>
              <Typography sx={{ fontSize: "0.75rem", color: "text.secondary", fontStyle: "italic" }}>
                No booking trades. Select rows in the sourcing grid and click "Generate Trades" to populate.
              </Typography>
            </Box>
          )}

          {/* Action buttons — bottom right */}
          {filteredBookingTrades.length > 0 && (
            <Box sx={{ display: "flex", justifyContent: "flex-end", gap: 1, pt: 0.75 }}>
              <Button
                variant="outlined"
                size="small"
                color="error"
                disabled={bookingSelectedRows.length === 0}
                onClick={handleDeleteBookingRows}
                startIcon={<DeleteOutlineIcon sx={{ fontSize: 14 }} />}
                sx={{ textTransform: "none", fontSize: "0.72rem", height: 26 }}
              >
                Delete
              </Button>
              <Button
                variant="contained"
                size="small"
                color="warning"
                disabled={bookingSelectedRows.length === 0}
                onClick={() => setBookingTrades((prev) => prev.map((t) => bookingSelectedRows.includes(t.id) ? { ...t, status: "Submitted" } : t))}
                sx={{ textTransform: "none", fontWeight: 600, fontSize: "0.72rem", height: 26 }}
              >
                Stage Trade
              </Button>
              <Button
                variant="contained"
                size="small"
                color="success"
                disabled={bookingSelectedRows.length === 0}
                onClick={() => setBookingDialogOpen(true)}
                startIcon={<CheckCircleIcon sx={{ fontSize: 14 }} />}
                sx={{ textTransform: "none", fontWeight: 600, fontSize: "0.72rem", height: 26 }}
              >
                Book
              </Button>
            </Box>
          )}
        </Box>{/* end booking section */}

      {/* BOOKING CONFIRMATION DIALOG */}
      <Dialog open={bookingDialogOpen} onClose={() => setBookingDialogOpen(false)} maxWidth="xs" fullWidth>
        <DialogTitle sx={{ fontSize: "1rem", fontWeight: 600 }}>Confirm Booking</DialogTitle>
        <DialogContent>
          <Typography variant="body2" sx={{ mb: 1 }}>
            You are about to book the following allocations for basket <strong>{selectedBasket?.name}</strong>:
          </Typography>
          <Box sx={{ maxHeight: 200, overflow: "auto" }}>
            {basketLines.filter((l) => l.totalAllocated > 0).map((line) => (
              <Box key={line.id} sx={{ display: "flex", justifyContent: "space-between", py: 0.5, borderBottom: 1, borderColor: "divider" }}>
                <Typography sx={{ fontSize: "0.8rem", fontWeight: 600 }}>{line.ticker}</Typography>
                <Typography sx={{ fontSize: "0.8rem" }}>{line.totalAllocated.toLocaleString()} / {line.totalQty.toLocaleString()}</Typography>
              </Box>
            ))}
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setBookingDialogOpen(false)} sx={{ textTransform: "none" }}>Cancel</Button>
          <Button variant="contained" color="success" onClick={() => setBookingDialogOpen(false)} sx={{ textTransform: "none" }}>
            Confirm Book
          </Button>
        </DialogActions>
      </Dialog>

      {/* RFQ CONFIRMATION MODAL */}
      <Dialog open={rfqModalOpen} onClose={() => setRfqModalOpen(false)} maxWidth="md" fullWidth>
        <DialogTitle sx={{ fontSize: "1rem", fontWeight: 600, pb: 0.5 }}>
          Confirm RFQ — {selectedBasket?.name}
        </DialogTitle>
        <DialogContent sx={{ pt: 1 }}>
          {/* Counterparties Grid */}
          <Box sx={{ border: 1, borderColor: "divider", borderRadius: 1, overflow: "hidden", mb: 1.5 }}>
            {/* Header row */}
            <Box sx={{ display: "grid", gridTemplateColumns: "1fr 70px 90px 120px 90px 36px", gap: 0, alignItems: "center", bgcolor: "action.hover", px: 1, py: 0.5 }}>
              <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, color: "text.secondary" }}>Counterparty</Typography>
              <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, color: "text.secondary" }}>GC Rate</Typography>
              <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, color: "text.secondary" }}>BPS Override</Typography>
              <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, color: "text.secondary" }}>Qty Source</Typography>
              <Typography sx={{ fontSize: "0.68rem", fontWeight: 700, color: "text.secondary" }}>Settlement</Typography>
              <Box />
            </Box>
            {/* CP rows */}
            <Box sx={{ maxHeight: 200, overflow: "auto" }}>
              {rfqModalCPs.map((cpId) => {
                const cp = COUNTERPARTIES.find((c) => c.id === cpId);
                const gcRate = GC_RATES[cpId] ?? 3.0;
                const cpQtySrc = rfqModalCpQtySource[cpId] ?? "totalQty";
                const cpSettle = rfqModalCpSettlement[cpId] ?? "FOP";
                return (
                  <Box key={cpId} sx={{ display: "grid", gridTemplateColumns: "1fr 70px 90px 120px 90px 36px", gap: 0, alignItems: "center", px: 1, py: 0.4, borderTop: 1, borderColor: "divider" }}>
                    <Typography sx={{ fontSize: "0.75rem", fontWeight: 600 }}>{cp?.name ?? cpId}</Typography>
                    <Typography sx={{ fontSize: "0.75rem", color: "text.secondary" }}>{gcRate} bps</Typography>
                    <TextField
                      size="small"
                      type="number"
                      placeholder="—"
                      value={rfqModalCpBpsOverride[cpId] ?? ""}
                      onChange={(e) => setRfqModalCpBpsOverride((prev) => ({ ...prev, [cpId]: e.target.value }))}
                      slotProps={{ htmlInput: { step: 0.1, min: 0, max: 100 } }}
                      sx={{ '& input': { fontSize: "0.72rem", py: 0.3, px: 0.5 }, width: 75 }}
                    />
                    <Select
                      size="small"
                      value={cpQtySrc}
                      onChange={(e) => setRfqModalCpQtySource((prev) => ({ ...prev, [cpId]: e.target.value as "totalQty" | "remainingQty" }))}
                      sx={{ fontSize: "0.7rem", height: 26, minWidth: 100 }}
                    >
                      <MenuItem value="totalQty" sx={{ fontSize: "0.72rem" }}>Total Qty</MenuItem>
                      <MenuItem value="remainingQty" sx={{ fontSize: "0.72rem" }}>Remaining Qty</MenuItem>
                    </Select>
                    <Select
                      size="small"
                      value={cpSettle}
                      onChange={(e) => setRfqModalCpSettlement((prev) => ({ ...prev, [cpId]: e.target.value as "FOP" | "DVP" }))}
                      sx={{ fontSize: "0.7rem", height: 26, minWidth: 75 }}
                    >
                      <MenuItem value="FOP" sx={{ fontSize: "0.72rem" }}>FOP</MenuItem>
                      <MenuItem value="DVP" sx={{ fontSize: "0.72rem" }}>DVP</MenuItem>
                    </Select>
                    <IconButton size="small" onClick={() => setRfqModalCPs((prev) => prev.filter((id) => id !== cpId))} sx={{ p: 0.3 }}>
                      <CloseIcon sx={{ fontSize: 14 }} />
                    </IconButton>
                  </Box>
                );
              })}
            </Box>
            {/* Add CP row */}
            {visibleCPs.filter((id) => !rfqModalCPs.includes(id) && !rfqSentCPs[selectedBasketId]?.[id]).length > 0 && (
              <Box sx={{ px: 1, py: 0.5, borderTop: 1, borderColor: "divider" }}>
                <Select
                  size="small"
                  displayEmpty
                  value=""
                  onChange={(e) => { if (e.target.value) setRfqModalCPs((prev) => [...prev, e.target.value as string]); }}
                  sx={{ fontSize: "0.72rem", height: 26, minWidth: 120 }}
                  renderValue={() => "+ Add Counterparty"}
                >
                  {visibleCPs.filter((id) => !rfqModalCPs.includes(id) && !rfqSentCPs[selectedBasketId]?.[id]).map((cpId) => {
                    const cp = COUNTERPARTIES.find((c) => c.id === cpId);
                    return <MenuItem key={cpId} value={cpId} sx={{ fontSize: "0.75rem" }}>{cp?.name ?? cpId}</MenuItem>;
                  })}
                </Select>
              </Box>
            )}
          </Box>

          <Divider sx={{ mb: 1.5 }} />

          {/* Per-ticker BPS overrides */}
          <Typography sx={{ fontSize: "0.72rem", color: "text.secondary", mb: 0.5 }}>Per-ticker BPS override (optional — overrides CP-level):</Typography>
          <Box sx={{ maxHeight: 160, overflow: "auto", border: 1, borderColor: "divider", borderRadius: 1, p: 0.5 }}>
            <Box sx={{ display: "grid", gridTemplateColumns: "1fr 80px 80px", gap: 0.3, alignItems: "center" }}>
              <Typography sx={{ fontSize: "0.65rem", fontWeight: 700, color: "text.secondary" }}>Ticker</Typography>
              <Typography sx={{ fontSize: "0.65rem", fontWeight: 700, color: "text.secondary" }}>Qty</Typography>
              <Typography sx={{ fontSize: "0.65rem", fontWeight: 700, color: "text.secondary" }}>BPS</Typography>
              {basketLines.map((line) => {
                const qty = line.totalQty;
                return (
                  <Box key={line.id} sx={{ display: "contents" }}>
                    <Typography sx={{ fontSize: "0.72rem", fontWeight: 600 }}>{line.ticker}</Typography>
                    <Typography sx={{ fontSize: "0.72rem" }}>{qty.toLocaleString()}</Typography>
                    <TextField
                      size="small"
                      type="number"
                      placeholder="—"
                      value={rfqModalTickerBps[line.ticker] ?? ""}
                      onChange={(e) => setRfqModalTickerBps((prev) => ({ ...prev, [line.ticker]: e.target.value }))}
                      slotProps={{ htmlInput: { step: 0.1, min: 0, max: 50 } }}
                      sx={{ '& input': { fontSize: "0.72rem", py: 0.3, px: 0.5 }, width: 70 }}
                    />
                  </Box>
                );
              })}
            </Box>
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setRfqModalOpen(false)} sx={{ textTransform: "none" }}>Cancel</Button>
          <Button
            variant="contained"
            onClick={handleConfirmSendRFQ}
            disabled={rfqModalCPs.length === 0}
            startIcon={<SendIcon sx={{ fontSize: 14 }} />}
            sx={{ textTransform: "none", fontWeight: 600, bgcolor: "#10b981", "&:hover": { bgcolor: "#059669" } }}
          >
            Confirm & Send RFQ
          </Button>
        </DialogActions>
      </Dialog>

      {/* RFQ Snackbar */}
      <Snackbar open={rfqSnackbar.open} autoHideDuration={4000} onClose={() => setRfqSnackbar((s) => ({ ...s, open: false }))} anchorOrigin={{ vertical: "bottom", horizontal: "center" }}>
        <Alert severity={rfqSnackbar.severity} onClose={() => setRfqSnackbar((s) => ({ ...s, open: false }))} sx={{ width: "100%" }}>
          {rfqSnackbar.message}
        </Alert>
      </Snackbar>
    </Box>
  );
}
