// Generated by AI (GitHub Copilot) - 2026-06-26
import { useState } from "react";
import { AppBar, Toolbar, Typography, Tabs, Tab, Box, Chip, Menu, MenuItem, ListItemIcon, ListItemText, IconButton, Tooltip } from "@mui/material";
import PermIdentityIcon from "@mui/icons-material/PermIdentity";
import ArrowDropDownIcon from "@mui/icons-material/ArrowDropDown";
import CheckIcon from "@mui/icons-material/Check";
import LightModeIcon from "@mui/icons-material/LightMode";
import DarkModeIcon from "@mui/icons-material/DarkMode";
import { usePerspective, ENTITIES, type PerspectiveEntity } from "../contexts/PerspectiveContext";
import { useThemeMode } from "../contexts/ThemeContext";

interface NavBarProps {
  activeRoute: string;
  onNavigate: (route: string) => void;
  actionableOrderCount?: number;
}

const routes = [
  { name: "Events", path: "/events" },
  { name: "Sourcing", path: "/sourcing" },
  { name: "Orders", path: "/orders", showBadge: true },
  { name: "Repay", path: "/repay" },
  { name: "Booking", path: "/booking" },
  { name: "Basket Trades", path: "/baskets" },
  { name: "Staged Trades", path: "/staged-trades" },
  { name: "Rerates", path: "/rerates" },
  { name: "Trade History", path: "/history" },
];

export default function NavBar({ activeRoute, onNavigate, actionableOrderCount }: NavBarProps) {
  const activeIndex = routes.findIndex((r) => r.path === activeRoute);
  const { current, setCurrent } = usePerspective();
  const { mode, toggleTheme } = useThemeMode();
  const [anchorEl, setAnchorEl] = useState<null | HTMLElement>(null);

  const handleSelectEntity = (entity: PerspectiveEntity) => {
    setCurrent(entity);
    setAnchorEl(null);
  };

  return (
    <AppBar position="static" sx={{ bgcolor: "background.paper" }}>
      <Toolbar variant="dense" sx={{ minHeight: 48, px: 2 }}>
        <Typography
          variant="subtitle1"
          sx={{ fontWeight: 700, color: "text.primary", mr: 2, whiteSpace: "nowrap" }}
        >
          Securities Financing Portal
        </Typography>
        <Box sx={{ flexGrow: 1 }} />
        <Chip
          label="PROTOTYPE"
          size="small"
          sx={{ bgcolor: "#f59e0b", color: "#000", fontWeight: 700, fontSize: "0.7rem", mr: 1.5 }}
        />
        <Tooltip title={`Switch to ${mode === "dark" ? "light" : "dark"} theme`}>
          <IconButton onClick={toggleTheme} size="small" sx={{ color: "text.secondary", mr: 1 }}>
            {mode === "dark" ? <LightModeIcon fontSize="small" /> : <DarkModeIcon fontSize="small" />}
          </IconButton>
        </Tooltip>
        <Chip
          icon={<PermIdentityIcon sx={{ color: "#5c9ce6 !important", fontSize: 18 }} />}
          label={
            <Box sx={{ display: "flex", alignItems: "center", gap: 0.3 }}>
              <span>{current.label}</span>
              <ArrowDropDownIcon sx={{ fontSize: 16, color: "#5c9ce6" }} />
            </Box>
          }
          variant="outlined"
          onClick={(e) => setAnchorEl(e.currentTarget)}
          sx={{
            color: "#5c9ce6",
            borderColor: "#5c9ce6",
            fontWeight: 600,
            fontSize: "0.8rem",
            cursor: "pointer",
            "&:hover": { bgcolor: "rgba(92,156,230,0.08)" },
          }}
        />
        <Menu
          anchorEl={anchorEl}
          open={Boolean(anchorEl)}
          onClose={() => setAnchorEl(null)}
          slotProps={{ paper: { sx: { bgcolor: "background.paper", border: "1px solid", borderColor: "divider", minWidth: 200 } } }}
        >
          {ENTITIES.map((entity) => (
            <MenuItem
              key={entity.id}
              onClick={() => handleSelectEntity(entity)}
              selected={entity.id === current.id}
              sx={{ "&.Mui-selected": { bgcolor: "rgba(92,156,230,0.12)" } }}
            >
              <ListItemIcon>
                {entity.id === current.id ? <CheckIcon sx={{ color: "#5c9ce6" }} /> : <PermIdentityIcon sx={{ color: "#6b7280" }} />}
              </ListItemIcon>
              <ListItemText
                primary={entity.label}
                slotProps={{ primary: { sx: { fontSize: "0.85rem", color: entity.id === current.id ? "primary.main" : "text.primary" } } }}
              />
            </MenuItem>
          ))}
        </Menu>
      </Toolbar>
      <Tabs
        value={activeIndex >= 0 ? activeIndex : false}
        onChange={(_, idx) => onNavigate(routes[idx].path)}
        variant="scrollable"
        scrollButtons="auto"
        textColor="inherit"
        slotProps={{ indicator: { sx: { bgcolor: "primary.main", height: 3 } } }}
        sx={{
          bgcolor: "background.default",
          minHeight: 36,
          "& .MuiTab-root": { minHeight: 36, py: 0.5 },
        }}
      >
        {routes.map((r) => (
          <Tab
            key={r.path}
            label={
              <Box sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                {r.name}
                {r.showBadge && actionableOrderCount != null && actionableOrderCount > 0 && (
                  <Chip
                    label={actionableOrderCount}
                    size="small"
                    sx={{
                      height: 16,
                      fontSize: "0.6rem",
                      fontWeight: 700,
                      bgcolor: "#f59e0b",
                      color: "#000",
                      minWidth: 20,
                    }}
                  />
                )}
              </Box>
            }
          />
        ))}
      </Tabs>
    </AppBar>
  );
}
