// Generated by AI (GitHub Copilot) - 2026-06-26
import { useState } from "react";
import {
  Drawer, Box, Typography, Button, Chip, Stepper, Step, StepLabel, StepContent,
  Divider, IconButton, Tooltip, Collapse,
} from "@mui/material";
import CloseIcon from "@mui/icons-material/Close";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import ExpandLessIcon from "@mui/icons-material/ExpandLess";
import CheckCircleIcon from "@mui/icons-material/CheckCircle";
import CancelIcon from "@mui/icons-material/Cancel";
import SwapHorizIcon from "@mui/icons-material/SwapHoriz";
import HistoryIcon from "@mui/icons-material/History";
import {
  type Order, type AuditEntry, ENTITY_LABELS, MAX_COUNTER_OFFERS, getNextActionBy, getSecLenderLabel,
} from "../mockData";
import { statusColors } from "../theme";
import { usePerspective } from "../contexts/PerspectiveContext";

function isTerminalStatus(s: string): boolean {
  return ["Booked", "Rejected", "Failed", "Expired", "Cancelled"].includes(s);
}

/**
 * Build dynamic workflow steps from audit trail.
 * Returns step labels derived from the actual progression.
 */
function buildWorkflowSteps(order: Order): { label: string; description: string; actor: string; timestamp: string; isError: boolean }[] {
  return order.auditTrail.map((entry) => {
    const isError = entry.status === "Rejected" || entry.status === "Failed";
    return {
      label: entry.status,
      description: entry.action,
      actor: entry.actor,
      timestamp: entry.timestamp,
      isError,
    };
  });
}

interface OrderDetailPanelProps {
  order: Order;
  onClose: () => void;
}

export default function OrderDetailPanel({ order, onClose }: OrderDetailPanelProps) {
  const { current } = usePerspective();
  const [showAudit, setShowAudit] = useState(true);
  const terminal = isTerminalStatus(order.status);
  const nextAction = getNextActionBy(order);
  const counterDisabled = !order.allowCounterOffer || order.counterOfferCount >= MAX_COUNTER_OFFERS;
  const workflowSteps = buildWorkflowSteps(order);
  // Active step is the last one (all steps up to here are completed)
  const activeStepIndex = workflowSteps.length - 1;

  return (
    <Drawer anchor="right" open onClose={onClose} slotProps={{ paper: { sx: { width: 500, bgcolor: "background.paper", p: 0 } } }}>
      <Box sx={{ display: "flex", flexDirection: "column", height: "100%", overflow: "hidden" }}>
        {/* Header */}
        <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", p: 2, borderBottom: 1, borderColor: "divider" }}>
          <Box>
            <Typography variant="h6" sx={{ fontWeight: 700, fontSize: 16 }}>{order.orderId}</Typography>
            <Box sx={{ display: "flex", gap: 1, mt: 0.5, flexWrap: "wrap" }}>
              <Chip label={order.status} size="small" sx={{ bgcolor: statusColors[order.status] + "22", color: statusColors[order.status], fontWeight: 600, height: 22, fontSize: "0.7rem" }} />
              <Chip label={order.orderType} size="small" variant="outlined" sx={{ height: 22, fontSize: "0.7rem" }} />
              <Chip label={order.settlementLocation} size="small" variant="outlined" sx={{ height: 22, fontSize: "0.7rem" }} />
              {order.counterOfferCount > 0 && (
                <Chip
                  label={`Counter ${order.counterOfferCount}/${MAX_COUNTER_OFFERS}${order.counterOfferCount >= MAX_COUNTER_OFFERS ? " FINAL" : ""}`}
                  size="small"
                  sx={{ bgcolor: "rgba(234,179,8,0.15)", color: "#eab308", fontWeight: 600, height: 22, fontSize: "0.7rem" }}
                />
              )}
            </Box>
          </Box>
          <IconButton onClick={onClose} size="small"><CloseIcon /></IconButton>
        </Box>

        {/* Scrollable body */}
        <Box sx={{ flexGrow: 1, overflow: "auto", p: 2 }}>
          {/* Pending With Banner */}
          {!terminal && (
            <Box sx={{ mb: 2, p: 1.5, bgcolor: "primary.main", borderRadius: 1, opacity: 0.9 }}>
              <Typography variant="body2" sx={{ color: "#fff", fontWeight: 600 }}>
                Pending with: {nextAction}
              </Typography>
            </Box>
          )}

          {/* Counter Offer Status */}
          {order.counterOfferCount > 0 && (
            <Box sx={{ mb: 2, p: 1.5, bgcolor: "rgba(234,179,8,0.08)", border: "1px solid rgba(234,179,8,0.3)", borderRadius: 1 }}>
              <Typography variant="body2" sx={{ color: "#eab308", fontWeight: 600 }}>
                Counter Offers: {order.counterOfferCount} / {MAX_COUNTER_OFFERS}
                {order.counterOfferCount >= MAX_COUNTER_OFFERS && " \u2014 LIMIT REACHED"}
              </Typography>
              {!order.allowCounterOffer && (
                <Typography variant="caption" sx={{ color: "text.secondary", mt: 0.5, display: "block" }}>
                  Further counter offers have been disabled. Must accept or reject.
                </Typography>
              )}
            </Box>
          )}

          {/* Dynamic Workflow Stepper — built from audit trail */}
          <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 1 }}>
            <Typography variant="subtitle2" sx={{ fontWeight: 600, color: "text.secondary" }}>
              Workflow Progression
            </Typography>
            {!terminal && (
              <Chip label="In Progress" size="small" sx={{ bgcolor: "rgba(96,165,250,0.15)", color: "#60a5fa", height: 20, fontSize: "0.65rem" }} />
            )}
          </Box>
          <Stepper
            activeStep={terminal ? workflowSteps.length : activeStepIndex}
            orientation="vertical"
            sx={{
              mb: 2,
              "& .MuiStepConnector-line": { minHeight: 16 },
              "& .MuiStepLabel-label": { fontSize: "0.8rem" },
            }}
          >
            {workflowSteps.map((step, idx) => (
              <Step key={idx} completed={terminal || idx < workflowSteps.length}>
                <StepLabel
                  error={step.isError}
                  optional={
                    <Typography variant="caption" sx={{ color: "text.disabled", fontSize: "0.65rem" }}>
                      {step.actor} \u00b7 {formatTimestamp(step.timestamp)}
                      {idx > 0 && ` (+${getTimeDelta(workflowSteps[idx - 1].timestamp, step.timestamp)})`}
                    </Typography>
                  }
                  sx={{
                    "& .MuiStepLabel-label": {
                      color: step.label.startsWith("Countered") ? "#fb923c" : undefined,
                      fontWeight: step.label.startsWith("Countered") ? 600 : undefined,
                    },
                  }}
                >
                  {step.label}
                </StepLabel>
                <StepContent>
                  <Typography variant="body2" sx={{ fontSize: "0.78rem", color: "text.primary", pl: 0.5 }}>
                    {step.description}
                  </Typography>
                </StepContent>
              </Step>
            ))}
          </Stepper>

          {/* Awaiting next action indicator for non-terminal */}
          {!terminal && (
            <Box sx={{ mb: 2, pl: 4, display: "flex", alignItems: "center", gap: 1 }}>
              <Box sx={{ width: 10, height: 10, borderRadius: "50%", bgcolor: "#facc15", animation: "expiry-pulse 2s ease-in-out infinite" }} />
              <Typography variant="body2" sx={{ fontSize: "0.78rem", color: "text.secondary", fontStyle: "italic" }}>
                Awaiting response from {nextAction}...
              </Typography>
            </Box>
          )}

          <Divider sx={{ my: 2 }} />

          {/* Audit Trail (raw log view) */}
          <Box sx={{ display: "flex", alignItems: "center", justifyContent: "space-between", mb: 1 }}>
            <Box sx={{ display: "flex", alignItems: "center", gap: 1 }}>
              <HistoryIcon sx={{ fontSize: 18, color: "text.secondary" }} />
              <Typography variant="subtitle2" sx={{ fontWeight: 600, color: "text.secondary" }}>
                Audit Log ({order.auditTrail.length} entries)
              </Typography>
            </Box>
            <Button size="small" onClick={() => setShowAudit(!showAudit)} endIcon={showAudit ? <ExpandLessIcon /> : <ExpandMoreIcon />} sx={{ textTransform: "none", fontSize: "0.75rem" }}>
              {showAudit ? "Hide" : "Show"}
            </Button>
          </Box>

          <Collapse in={showAudit}>
            <Box sx={{ pl: 1, borderLeft: "2px solid", borderColor: "divider" }}>
              {order.auditTrail.map((entry, idx) => (
                <AuditEntryRow key={idx} entry={entry} previousEntry={idx > 0 ? order.auditTrail[idx - 1] : undefined} isLast={idx === order.auditTrail.length - 1} />
              ))}
            </Box>
          </Collapse>

          <Divider sx={{ my: 2 }} />

          {/* Order Details Grid */}
          <Typography variant="subtitle2" sx={{ mb: 1, fontWeight: 600, color: "text.secondary" }}>Order Details</Typography>
          <Box sx={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "8px 16px" }}>
            <DetailField label="Security" value={order.securityId} />
            <DetailField label="CUSIP" value={order.cusip} />
            <DetailField label="ISIN" value={order.isin} />
            <DetailField label="Sec Lender" value={getSecLenderLabel(order, current.id)} />
            <DetailField label="Quantity" value={order.quantity.toLocaleString()} />
            <DetailField label="Fee Rate" value={order.feeRate != null ? `${(order.feeRate * 100).toFixed(2)} BPS` : "—"} />
            <DetailField label="Settlement Type" value={order.settlementType} />
            <DetailField label="Settlement Location" value={order.settlementLocation} />
            <DetailField label="Price" value={`$${order.price.toFixed(2)}`} />
            <DetailField label="DVP Price" value={`$${order.dvpPrice.toFixed(2)}`} />
            <DetailField label="Trade Date" value={order.tradeDate} />
            <DetailField label="Settlement Date" value={order.settlementDate} />
            <DetailField label="Order Expiry" value={formatTimestamp(order.orderExpiryUtc)} />
            <DetailField label="Last Updated" value={formatTimestamp(order.lastUpdatedUtc)} />
            <DetailField label="Last Updated By" value={order.lastUpdatedByUserId} />
            <DetailField label="Lender" value={ENTITY_LABELS[order.lenderEntityId] ?? order.lenderEntityId} />
            <DetailField label="Borrower" value={ENTITY_LABELS[order.borrowerEntityId] ?? order.borrowerEntityId} />
          </Box>

          {order.notes && (
            <>
              <Divider sx={{ my: 2 }} />
              <Typography variant="subtitle2" sx={{ mb: 0.5, fontWeight: 600, color: "text.secondary" }}>Notes</Typography>
              <Typography variant="body2" sx={{ color: "text.primary", fontSize: 13 }}>{order.notes}</Typography>
            </>
          )}
        </Box>

        {/* Action Buttons (fixed footer) */}
        {!terminal && (
          <Box sx={{ display: "flex", justifyContent: "flex-end", gap: 1.5, p: 2, borderTop: 1, borderColor: "divider" }}>
            <Button variant="contained" color="success" size="small" startIcon={<CheckCircleIcon />} sx={{ textTransform: "none", fontWeight: 600 }}>
              Accept
            </Button>
            <Tooltip title={counterDisabled ? "Counter offers not allowed or limit reached" : ""}>
              <span>
                <Button variant="outlined" color="warning" size="small" startIcon={<SwapHorizIcon />} disabled={counterDisabled} sx={{ textTransform: "none", fontWeight: 600 }}>
                  Counter{order.counterOfferCount > 0 ? ` (${order.counterOfferCount}/${MAX_COUNTER_OFFERS})` : ""}
                </Button>
              </span>
            </Tooltip>
            <Button variant="outlined" color="error" size="small" startIcon={<CancelIcon />} sx={{ textTransform: "none", fontWeight: 600 }}>
              Reject
            </Button>
          </Box>
        )}
      </Box>
    </Drawer>
  );
}

/* ── Helper Components ── */

function AuditEntryRow({ entry, previousEntry, isLast }: { entry: AuditEntry; previousEntry?: AuditEntry; isLast: boolean }) {
  const elapsed = previousEntry ? getTimeDelta(previousEntry.timestamp, entry.timestamp) : null;
  const statusColor = getAuditStatusColor(entry.status);

  return (
    <Box sx={{ position: "relative", pl: 2, pb: isLast ? 0 : 1.5, "&::before": { content: '""', position: "absolute", left: -5, top: 6, width: 8, height: 8, borderRadius: "50%", bgcolor: statusColor, border: "2px solid", borderColor: "background.paper" } }}>
      <Box sx={{ display: "flex", alignItems: "flex-start", gap: 1 }}>
        <Chip label={entry.status} size="small" sx={{ bgcolor: statusColor + "22", color: statusColor, height: 18, fontSize: "0.65rem", fontWeight: 600 }} />
        {elapsed && (
          <Typography variant="caption" sx={{ color: "text.disabled", fontSize: "0.65rem", mt: 0.2 }}>
            +{elapsed}
          </Typography>
        )}
      </Box>
      <Typography variant="body2" sx={{ fontSize: "0.78rem", color: "text.primary", mt: 0.3 }}>
        {entry.action}
      </Typography>
      <Box sx={{ display: "flex", alignItems: "center", gap: 1, mt: 0.2 }}>
        <Typography variant="caption" sx={{ color: "text.secondary", fontSize: "0.7rem" }}>
          {entry.actor}
        </Typography>
        <Typography variant="caption" sx={{ color: "text.disabled", fontSize: "0.65rem" }}>
          {formatTimestamp(entry.timestamp)}
        </Typography>
      </Box>
    </Box>
  );
}

function DetailField({ label, value }: { label: string; value: string }) {
  return (
    <Box>
      <Typography variant="caption" sx={{ color: "text.disabled", fontSize: "0.7rem" }}>{label}</Typography>
      <Typography variant="body2" sx={{ fontWeight: 500, fontSize: "0.82rem" }}>{value}</Typography>
    </Box>
  );
}

/* ── Helpers ── */

function formatTimestamp(utc: string): string {
  if (!utc) return "\u2014";
  const d = new Date(utc);
  const yyyy = d.getFullYear();
  const mo = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  let h = d.getHours();
  const ampm = h >= 12 ? "PM" : "AM";
  h = h % 12 || 12;
  return `${yyyy}-${mo}-${dd} ${String(h).padStart(2, "0")}:${String(d.getMinutes()).padStart(2, "0")}:${String(d.getSeconds()).padStart(2, "0")} ${ampm}`;
}

function getTimeDelta(from: string, to: string): string {
  const ms = new Date(to).getTime() - new Date(from).getTime();
  if (ms < 0) return "";
  const secs = Math.floor(ms / 1000);
  if (secs < 60) return `${secs}s`;
  const mins = Math.floor(secs / 60);
  if (mins < 60) return `${mins}m`;
  const hours = Math.floor(mins / 60);
  const remMins = mins % 60;
  if (hours < 24) return remMins > 0 ? `${hours}h ${remMins}m` : `${hours}h`;
  const days = Math.floor(hours / 24);
  return `${days}d ${hours % 24}h`;
}

function getAuditStatusColor(status: string): string {
  if (status.startsWith("Countered")) return "#fb923c";
  return statusColors[status as keyof typeof statusColors] || "#9ca3af";
}
