// Generated by AI (GitHub Copilot) - 2026-06-26
import { PerspectiveProvider } from './contexts/PerspectiveContext';
import { ThemeContextProvider } from './contexts/ThemeContext';
import AppContent from './AppContent';

export default function App() {
  return (
    <ThemeContextProvider>
      <PerspectiveProvider>
        <AppContent />
      </PerspectiveProvider>
    </ThemeContextProvider>
  );
}
