// Generated by AI (GitHub Copilot) - 2026-06-29
import { useState, useMemo, useCallback, useSyncExternalStore } from 'react';
import { Box } from '@mui/material';
import NavBar from './components/NavBar';
import OrdersPage from './pages/OrdersPage';
import EventsPage from './pages/EventsPage';
import SourcingPage from './pages/SourcingPage';
import PlaceholderPage from './pages/PlaceholderPage';
import { usePerspective } from './contexts/PerspectiveContext';
import { mockOrders } from './mockData';

const TERMINAL_STATUSES = new Set(['Accepted', 'Expired', 'Rejected', 'Booked']);

// Sync route state with browser URL (pushState-based routing)
function usePathname() {
  const subscribe = useCallback((cb: () => void) => {
    window.addEventListener('popstate', cb);
    return () => window.removeEventListener('popstate', cb);
  }, []);
  return useSyncExternalStore(subscribe, () => window.location.pathname);
}

export default function AppContent() {
  const pathname = usePathname();
  const route = pathname === '/' ? '/orders' : pathname;
  const { current } = usePerspective();

  const navigate = useCallback((path: string) => {
    window.history.pushState(null, '', path);
    // Dispatch popstate so useSyncExternalStore re-renders
    window.dispatchEvent(new PopStateEvent('popstate'));
  }, []);

  // Count actionable orders visible to the current entity
  const actionableOrderCount = useMemo(() => {
    return mockOrders.filter((o) => {
      const isRelevant = o.lenderEntityId === current.id || o.borrowerEntityId === current.id;
      return isRelevant && !TERMINAL_STATUSES.has(o.status);
    }).length;
  }, [current.id]);

  const renderPage = () => {
    switch (route) {
      case '/orders': return <OrdersPage />;
      case '/events': return <EventsPage />;
      case '/sourcing': return <SourcingPage />;
      case '/repay': return <PlaceholderPage title="Repay" />;
      case '/booking': return <PlaceholderPage title="Booking" />;
      case '/baskets': return <PlaceholderPage title="Basket Trades" />;
      case '/staged-trades': return <PlaceholderPage title="Staged Trades" />;
      case '/rerates': return <PlaceholderPage title="Rerates" />;
      case '/history': return <PlaceholderPage title="Trade History" />;
      default: return <OrdersPage />;
    }
  };

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', height: '100vh', bgcolor: 'background.default' }}>
      <NavBar activeRoute={route} onNavigate={navigate} actionableOrderCount={actionableOrderCount} />
      <Box sx={{ flex: 1, overflow: 'hidden', p: 1 }}>
        {renderPage()}
      </Box>
    </Box>
  );
}
