// Generated by AI (GitHub Copilot) - 2026-06-26

/* ── Order Status Enum ── */
export type OrderStatus =
  | "New"
  | "Draft"
  | "Submitted"
  | "Pending"
  | "Countered"
  | "Accepted"
  | "Rejected"
  | "Booking"
  | "Booked"
  | "Failed"
  | "Expired"
  | "Cancelled";

export type OrderType = "Borrow" | "Lend" | "Repay" | "Recall";

export type OrderDirection = "Outgoing" | "Incoming";

export type SettlementType = "FOP" | "DVP";

export type SettlementLocation = "DTC" | "CDS" | "Fed";

export interface AuditEntry {
  status: string; // OrderStatus or descriptive counter label e.g. "Countered (SEB)"
  action: string;
  actor: string;
  timestamp: string;
}

export interface Order {
  orderId: string;
  orderType: OrderType | "";
  status: OrderStatus;
  lenderEntityId: string;
  borrowerEntityId: string;
  submittedByEntityId: string;
  lastUpdatedByEntityId: string;
  lastUpdatedByUserId: string;
  counterpartyLabel: string;
  securityId: string;
  cusip: string;
  isin: string;
  quantity: number;
  feeRate: number | null;
  tradeDate: string;
  settlementDate: string;
  settlementType: SettlementType;
  settlementLocation: SettlementLocation;
  price: number;
  dvpPrice: number;
  lastUpdatedUtc: string;
  orderExpiryUtc: string;
  counterOfferCount: number;
  allowCounterOffer: boolean;
  auditTrail: AuditEntry[];
  notes?: string;
}

/** Max counter offers allowed per order */
export const MAX_COUNTER_OFFERS = 2;

/** Fields that must be filled before submitting a new order */
export const MANDATORY_NEW_ORDER_FIELDS: (keyof Order)[] = [
  "orderType", "securityId", "quantity", "settlementType", "settlementLocation", "tradeDate", "settlementDate",
];

/** Entity ID → display label lookup */
export const ENTITY_LABELS: Record<string, string> = {
  HOOPP: "HOOPP",
  SEB: "SEB AB",
  SSBT_AGT_INT: "SSBT AGT INT",
  SSBT_AGT_H2696: "SSBT AGT H2696",
  SSBT_AGT: "SSBT AGT",
  SSBT_UST: "SSBT UST",
};

/** All known counterparty entity IDs (for dropdown) */
export const ALL_ENTITY_IDS = Object.keys(ENTITY_LABELS);

/** Create a blank "New" order row with default values */
let newOrderSeq = 1;
export function createNewOrderRow(viewerEntityId: string): Order {
  const today = new Date();
  const t2 = new Date(today);
  t2.setDate(t2.getDate() + 2);
  const formatDate = (d: Date) => d.toISOString().slice(0, 10);
  const id = `NEW-${String(newOrderSeq++).padStart(4, "0")}`;

  return {
    orderId: id,
    orderType: "",
    status: "New",
    lenderEntityId: "",
    borrowerEntityId: viewerEntityId,
    submittedByEntityId: viewerEntityId,
    lastUpdatedByEntityId: viewerEntityId,
    lastUpdatedByUserId: "",
    counterpartyLabel: "",
    securityId: "",
    cusip: "",
    isin: "",
    quantity: 0,
    feeRate: null,
    tradeDate: formatDate(today),
    settlementDate: formatDate(t2),
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 0,
    dvpPrice: 0,
    lastUpdatedUtc: new Date().toISOString(),
    orderExpiryUtc: "15 min",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [],
    notes: "",
  };
}

/** Helper to generate a dynamic expiry UTC string relative to now (for demo urgency states) */
function demoExpiry(minutesFromNow: number): string {
  return new Date(Date.now() + minutesFromNow * 60000).toISOString();
}

/** Compute direction relative to the viewing entity */
export function getDirection(order: Order, viewerEntityId: string): OrderDirection {
  return order.submittedByEntityId === viewerEntityId ? "Outgoing" : "Incoming";
}

/** Compute who initiated — returns the actual entity label */
export function getInitiatedBy(order: Order, _viewerEntityId: string): string {
  return ENTITY_LABELS[order.submittedByEntityId] ?? order.submittedByEntityId;
}

/** Compute who last updated — returns the user's email */
export function getLastUpdatedBy(order: Order): string {
  return order.lastUpdatedByUserId;
}

/** Compute sec lender label — the counterparty in the trade (never yourself).
 *  External counterparties always face HOOPP; HOOPP faces external counterparties. */
export function getSecLenderLabel(order: Order, viewerEntityId?: string): string {
  if (!viewerEntityId) {
    // Fallback: show the lender entity (legacy behavior)
    return ENTITY_LABELS[order.lenderEntityId] ?? order.lenderEntityId;
  }
  // Show the OTHER party — the one you're facing
  const otherEntityId = order.lenderEntityId === viewerEntityId
    ? order.borrowerEntityId
    : order.lenderEntityId;
  return ENTITY_LABELS[otherEntityId] ?? otherEntityId;
}

/** Compute counterparty label — the OTHER entity from viewer's perspective */
export function getCounterpartyLabel(order: Order, viewerEntityId: string): string {
  const otherEntityId = order.lenderEntityId === viewerEntityId
    ? order.borrowerEntityId
    : order.lenderEntityId;
  return ENTITY_LABELS[otherEntityId] ?? otherEntityId;
}

/** Compute order type from viewer's perspective:
 *  Borrower sees Borrow/Repay, Lender sees Lend/Recall */
const VIEWER_TYPE_MAP: Record<string, Record<OrderType, OrderType>> = {
  borrower: { Borrow: "Borrow", Lend: "Borrow", Recall: "Repay", Repay: "Repay" },
  lender:   { Borrow: "Lend",   Lend: "Lend",   Recall: "Recall", Repay: "Recall" },
};
export function getOrderTypeForViewer(order: Order, viewerEntityId: string): OrderType {
  const role = order.borrowerEntityId === viewerEntityId ? "borrower" : "lender";
  return VIEWER_TYPE_MAP[role][order.orderType];
}

/**
 * Compute who needs to take the next action on this order.
 */
export function getNextActionBy(order: Order): string {
  switch (order.status) {
    case "Draft":
      return ENTITY_LABELS[order.submittedByEntityId] ?? order.submittedByEntityId;
    case "Submitted":
    case "Pending": {
      const otherEntityId = order.submittedByEntityId === order.lenderEntityId
        ? order.borrowerEntityId
        : order.lenderEntityId;
      return ENTITY_LABELS[otherEntityId] ?? otherEntityId;
    }
    case "Countered": {
      const responderId = order.lastUpdatedByEntityId === order.lenderEntityId
        ? order.borrowerEntityId
        : order.lenderEntityId;
      return ENTITY_LABELS[responderId] ?? responderId;
    }
    case "Accepted":
    case "Booking":
      return "System";
    default:
      return "\u2014";
  }
}

/* ── Mock Orders Data ── */
export const mockOrders: Order[] = [
  {
    orderId: "ORD-2026-0001",
    orderType: "Borrow",
    status: "Booked",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "lars.bergman@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "AAPL US",
    cusip: "037833100",
    isin: "US0378331005",
    quantity: 10000,
    feeRate: 0.45,
    tradeDate: "2026-06-23",
    settlementDate: "2026-06-25",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 198.50,
    dvpPrice: 197.75,
    lastUpdatedUtc: "2026-06-23T15:30:00Z",
    orderExpiryUtc: "2026-06-23T16:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "aye@hoopp.com", timestamp: "2026-06-23T10:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-23T10:00:05Z" },
      { status: "Accepted", action: "Accepted by SEB", actor: "lars.bergman@seb.se", timestamp: "2026-06-23T14:30:00Z" },
      { status: "Booking", action: "Auto-booking initiated", actor: "System", timestamp: "2026-06-23T14:30:10Z" },
      { status: "Booked", action: "Trade booked successfully", actor: "System", timestamp: "2026-06-23T15:30:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0002",
    orderType: "Borrow",
    status: "Accepted",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "anna.kvist@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "MSFT US",
    cusip: "594918104",
    isin: "US5949181045",
    quantity: 25000,
    feeRate: 0.30,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 445.20,
    dvpPrice: 444.80,
    lastUpdatedUtc: "2026-06-24T10:15:00Z",
    orderExpiryUtc: "2026-06-24T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-24T08:30:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T08:30:05Z" },
      { status: "Accepted", action: "Accepted by SEB", actor: "anna.kvist@seb.se", timestamp: "2026-06-24T10:15:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0003",
    orderType: "Borrow",
    status: "Countered",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "lars.bergman@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "NVDA US",
    cusip: "67066G104",
    isin: "US67066G1040",
    quantity: 5000,
    feeRate: 1.10,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 135.60,
    dvpPrice: 135.10,
    lastUpdatedUtc: "2026-06-24T11:45:00Z",
    orderExpiryUtc: demoExpiry(35),  // ~35 min from now → amber urgency
    counterOfferCount: 1,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted at 0.85% BPS", actor: "aye@hoopp.com", timestamp: "2026-06-24T09:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T09:00:05Z" },
      { status: "Countered (SEB)", action: "SEB countered with 1.10% BPS (vs requested 0.85%)", actor: "lars.bergman@seb.se", timestamp: "2026-06-24T11:45:00Z" },
    ],
    notes: "SEB countered: 1.10% vs HOOPP's requested 0.85%",
  },
  {
    orderId: "ORD-2026-0004",
    orderType: "Borrow",
    status: "Pending",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "TSLA US",
    cusip: "88160R101",
    isin: "US88160R1014",
    quantity: 8000,
    feeRate: 0.75,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 252.30,
    dvpPrice: 251.90,
    lastUpdatedUtc: "2026-06-24T13:00:00Z",
    orderExpiryUtc: demoExpiry(90),  // ~1.5 hr from now → normal/green
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "aye@hoopp.com", timestamp: "2026-06-24T12:55:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T13:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0005",
    orderType: "Borrow",
    status: "Submitted",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "jose.chang@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "CM CN",
    cusip: "136069101",
    isin: "CA1360691010",
    quantity: 50000,
    feeRate: 0.20,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 82.15,
    dvpPrice: 81.90,
    lastUpdatedUtc: "2026-06-24T14:20:00Z",
    orderExpiryUtc: demoExpiry(180),  // 3 hrs → normal
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-24T14:20:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0006",
    orderType: "Borrow",
    status: "Rejected",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "anna.kvist@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "AMZN US",
    cusip: "023135106",
    isin: "US0231351067",
    quantity: 15000,
    feeRate: 0.55,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 198.40,
    dvpPrice: 198.00,
    lastUpdatedUtc: "2026-06-24T09:30:00Z",
    orderExpiryUtc: "2026-06-24T12:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "aye@hoopp.com", timestamp: "2026-06-24T08:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T08:00:05Z" },
      { status: "Rejected", action: "Rejected \u2014 Insufficient inventory", actor: "anna.kvist@seb.se", timestamp: "2026-06-24T09:30:00Z" },
    ],
    notes: "Insufficient inventory",
  },
  {
    orderId: "ORD-2026-0007",
    orderType: "Borrow",
    status: "Countered",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "lars.bergman@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "BNS CN",
    cusip: "064149107",
    isin: "CA0641491075",
    quantity: 30000,
    feeRate: 0.22,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 72.80,
    dvpPrice: 72.45,
    lastUpdatedUtc: "2026-06-24T12:10:00Z",
    orderExpiryUtc: demoExpiry(8),  // ~8 min from now → red flashing
    counterOfferCount: 1,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted at 0.18% BPS", actor: "aye@hoopp.com", timestamp: "2026-06-24T09:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T09:00:05Z" },
      { status: "Countered (SEB)", action: "SEB countered with 0.22% BPS", actor: "lars.bergman@seb.se", timestamp: "2026-06-24T12:10:00Z" },
    ],
    notes: "SEB countered: 0.22% vs HOOPP's requested 0.18%",
  },
  {
    orderId: "ORD-2026-0008",
    orderType: "Borrow",
    status: "Countered",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "GOOG US",
    cusip: "02079K305",
    isin: "US02079K3059",
    quantity: 12000,
    feeRate: 0.35,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 178.90,
    dvpPrice: 178.50,
    lastUpdatedUtc: "2026-06-26T10:45:00Z",
    orderExpiryUtc: demoExpiry(3),  // ~3 min from now → red pulsing (critical)
    counterOfferCount: 2,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Order submitted at 0.25% BPS", actor: "aye@hoopp.com", timestamp: "2026-06-25T14:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-25T14:00:05Z" },
      { status: "Countered (SEB)", action: "SEB countered with 0.40% BPS", actor: "lars.bergman@seb.se", timestamp: "2026-06-25T16:30:00Z" },
      { status: "Countered (HOOPP)", action: "HOOPP countered with 0.35% BPS (final counter \u2014 no further counters allowed)", actor: "aye@hoopp.com", timestamp: "2026-06-26T10:45:00Z" },
    ],
    notes: "Final counter sent (0.35% BPS). Counter offers no longer allowed \u2014 SEB must accept or reject.",
  },

  // ── SSBT orders ──
  {
    orderId: "ORD-2026-0040",
    orderType: "Borrow",
    status: "Pending",
    lenderEntityId: "SSBT_AGT_INT",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SSBT AGT INT",
    securityId: "JPM US",
    cusip: "46625H100",
    isin: "US46625H1005",
    quantity: 20000,
    feeRate: 0.38,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 215.80,
    dvpPrice: 215.40,
    lastUpdatedUtc: "2026-06-25T14:30:00Z",
    orderExpiryUtc: demoExpiry(12),  // ~12 min from now → red (< 15 min)
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "aye@hoopp.com", timestamp: "2026-06-25T14:25:00Z" },
      { status: "Pending", action: "Received by SSBT AGT INT", actor: "System", timestamp: "2026-06-25T14:30:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0041",
    orderType: "Borrow",
    status: "Accepted",
    lenderEntityId: "SSBT_AGT_H2696",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SSBT_AGT_H2696",
    lastUpdatedByUserId: "ops.team@ssbt.com",
    counterpartyLabel: "SSBT AGT H2696",
    securityId: "GS US",
    cusip: "38141G104",
    isin: "US38141G1040",
    quantity: 8000,
    feeRate: 0.52,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 565.30,
    dvpPrice: 564.80,
    lastUpdatedUtc: "2026-06-25T16:00:00Z",
    orderExpiryUtc: "2026-06-25T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-25T13:00:00Z" },
      { status: "Pending", action: "Received by SSBT AGT H2696", actor: "System", timestamp: "2026-06-25T13:00:05Z" },
      { status: "Accepted", action: "Accepted by SSBT AGT H2696", actor: "ops.team@ssbt.com", timestamp: "2026-06-25T16:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0042",
    orderType: "Borrow",
    status: "Countered",
    lenderEntityId: "SSBT_AGT",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SSBT_AGT",
    lastUpdatedByUserId: "lending.desk@ssbt.com",
    counterpartyLabel: "SSBT AGT",
    securityId: "BAC US",
    cusip: "060505104",
    isin: "US0605051046",
    quantity: 50000,
    feeRate: 0.28,
    tradeDate: "2026-06-26",
    settlementDate: "2026-06-28",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 42.85,
    dvpPrice: 42.60,
    lastUpdatedUtc: "2026-06-26T09:30:00Z",
    orderExpiryUtc: demoExpiry(50),  // ~50 min from now → amber (< 1 hr)
    counterOfferCount: 1,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Order submitted at 0.20% BPS", actor: "aye@hoopp.com", timestamp: "2026-06-26T08:00:00Z" },
      { status: "Pending", action: "Received by SSBT AGT", actor: "System", timestamp: "2026-06-26T08:00:05Z" },
      { status: "Countered (SSBT AGT)", action: "SSBT AGT countered with 0.28% BPS", actor: "lending.desk@ssbt.com", timestamp: "2026-06-26T09:30:00Z" },
    ],
    notes: "SSBT AGT countered: 0.28% vs HOOPP's requested 0.20%",
  },
  {
    orderId: "ORD-2026-0043",
    orderType: "Borrow",
    status: "Pending",
    lenderEntityId: "SSBT_UST",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "jose.chang@hoopp.com",
    counterpartyLabel: "SSBT UST",
    securityId: "T 2.5 05/31",
    cusip: "91282CJL6",
    isin: "US91282CJL63",
    quantity: 5000000,
    feeRate: 0.05,
    tradeDate: "2026-06-26",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "Fed",
    price: 99.125,
    dvpPrice: 99.10,
    lastUpdatedUtc: "2026-06-26T11:00:00Z",
    orderExpiryUtc: demoExpiry(150),  // 2.5 hrs → normal
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "UST borrow order submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-26T11:00:00Z" },
      { status: "Pending", action: "Received by SSBT UST", actor: "System", timestamp: "2026-06-26T11:00:05Z" },
    ],
    notes: "US Treasury borrow via SSBT UST desk. Fed wire settlement.",
  },

  // ── Lend orders ──
  {
    orderId: "ORD-2026-0010",
    orderType: "Lend",
    status: "Pending",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "SEB",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "lars.bergman@seb.se",
    counterpartyLabel: "HOOPP",
    securityId: "RY CN",
    cusip: "780087102",
    isin: "CA7800871021",
    quantity: 40000,
    feeRate: 0.12,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "CDS",
    price: 148.25,
    dvpPrice: 147.90,
    lastUpdatedUtc: "2026-06-24T08:45:00Z",
    orderExpiryUtc: demoExpiry(45),  // ~45 min → amber
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Lend order submitted by SEB", actor: "lars.bergman@seb.se", timestamp: "2026-06-24T08:40:00Z" },
      { status: "Pending", action: "Awaiting HOOPP response", actor: "System", timestamp: "2026-06-24T08:45:00Z" },
    ],
    notes: "Incoming offer from SEB",
  },
  {
    orderId: "ORD-2026-0011",
    orderType: "Lend",
    status: "Accepted",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "SEB",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "HOOPP",
    securityId: "TD CN",
    cusip: "891160509",
    isin: "CA8911605092",
    quantity: 60000,
    feeRate: 0.15,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 88.50,
    dvpPrice: 88.20,
    lastUpdatedUtc: "2026-06-24T09:00:00Z",
    orderExpiryUtc: "2026-06-24T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Lend order submitted by SEB", actor: "lars.bergman@seb.se", timestamp: "2026-06-24T08:00:00Z" },
      { status: "Pending", action: "Awaiting HOOPP response", actor: "System", timestamp: "2026-06-24T08:00:05Z" },
      { status: "Accepted", action: "Accepted by HOOPP", actor: "aye@hoopp.com", timestamp: "2026-06-24T09:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0012",
    orderType: "Lend",
    status: "Pending",
    lenderEntityId: "HOOPP",
    borrowerEntityId: "SEB",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "mike.li@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "BMO CN",
    cusip: "063671101",
    isin: "CA0636711016",
    quantity: 20000,
    feeRate: 0.18,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "CDS",
    price: 127.30,
    dvpPrice: 127.00,
    lastUpdatedUtc: "2026-06-24T10:30:00Z",
    orderExpiryUtc: "2026-06-26T15:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Lend order submitted at 0.18% BPS", actor: "mike.li@hoopp.com", timestamp: "2026-06-24T09:30:00Z" },
      { status: "Pending", action: "Awaiting SEB response", actor: "System", timestamp: "2026-06-24T09:30:05Z" },
    ],
  },
  {
    orderId: "ORD-2026-0013",
    orderType: "Lend",
    status: "Expired",
    lenderEntityId: "HOOPP",
    borrowerEntityId: "SEB",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "ENB CN",
    cusip: "29250N105",
    isin: "CA29250N1050",
    quantity: 35000,
    feeRate: 0.08,
    tradeDate: "2026-06-23",
    settlementDate: "2026-06-25",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 55.40,
    dvpPrice: 55.15,
    lastUpdatedUtc: "2026-06-23T17:00:00Z",
    orderExpiryUtc: "2026-06-23T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Lend order submitted", actor: "aye@hoopp.com", timestamp: "2026-06-23T15:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-23T15:00:05Z" },
      { status: "Expired", action: "No response within 2 hours \u2014 order expired", actor: "System", timestamp: "2026-06-23T17:00:00Z" },
    ],
    notes: "Expired - no response within 2 hours",
  },

  // ── Recall orders ──
  {
    orderId: "ORD-2026-0020",
    orderType: "Recall",
    status: "Submitted",
    lenderEntityId: "HOOPP",
    borrowerEntityId: "SEB",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "jose.chang@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "MSFT US",
    cusip: "594918104",
    isin: "US5949181045",
    quantity: 12000,
    feeRate: 0.30,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 445.20,
    dvpPrice: 444.80,
    lastUpdatedUtc: "2026-06-25T08:00:00Z",
    orderExpiryUtc: "2026-06-27T16:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Recall submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-25T08:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0021",
    orderType: "Recall",
    status: "Pending",
    lenderEntityId: "HOOPP",
    borrowerEntityId: "SEB",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "TSLA US",
    cusip: "88160R101",
    isin: "US88160R1014",
    quantity: 5000,
    feeRate: 0.75,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "DTC",
    price: 252.30,
    dvpPrice: 251.90,
    lastUpdatedUtc: "2026-06-25T09:15:00Z",
    orderExpiryUtc: "2026-06-27T16:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Recall submitted", actor: "aye@hoopp.com", timestamp: "2026-06-25T09:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-25T09:15:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0022",
    orderType: "Recall",
    status: "Countered",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "SEB",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "mike.li@hoopp.com",
    counterpartyLabel: "HOOPP",
    securityId: "RY CN",
    cusip: "780087102",
    isin: "CA7800871021",
    quantity: 20000,
    feeRate: 0.12,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "CDS",
    price: 148.25,
    dvpPrice: 147.90,
    lastUpdatedUtc: "2026-06-24T16:30:00Z",
    orderExpiryUtc: "2026-06-26T14:00:00Z",
    counterOfferCount: 1,
    allowCounterOffer: true,
    auditTrail: [
      { status: "Submitted", action: "Recall submitted by SEB", actor: "anna.kvist@seb.se", timestamp: "2026-06-24T14:00:00Z" },
      { status: "Pending", action: "Awaiting HOOPP response", actor: "System", timestamp: "2026-06-24T14:00:05Z" },
      { status: "Countered (HOOPP)", action: "HOOPP countered with partial quantity 20,000", actor: "mike.li@hoopp.com", timestamp: "2026-06-24T16:30:00Z" },
    ],
    notes: "Counterparty recall request - HOOPP countered with partial quantity",
  },

  // ── Repay orders ──
  {
    orderId: "ORD-2026-0030",
    orderType: "Repay",
    status: "Booked",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "anna.kvist@seb.se",
    counterpartyLabel: "SEB AB",
    securityId: "AMZN US",
    cusip: "023135106",
    isin: "US0231351067",
    quantity: 15000,
    feeRate: 0.55,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "DTC",
    price: 198.40,
    dvpPrice: 198.00,
    lastUpdatedUtc: "2026-06-24T14:00:00Z",
    orderExpiryUtc: "2026-06-24T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Repay submitted", actor: "aye@hoopp.com", timestamp: "2026-06-24T11:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-24T11:00:05Z" },
      { status: "Accepted", action: "Accepted by SEB", actor: "anna.kvist@seb.se", timestamp: "2026-06-24T13:00:00Z" },
      { status: "Booking", action: "Auto-booking initiated", actor: "System", timestamp: "2026-06-24T13:00:10Z" },
      { status: "Booked", action: "Trade booked", actor: "System", timestamp: "2026-06-24T14:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0031",
    orderType: "Repay",
    status: "Pending",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "aye@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "BNS CN",
    cusip: "064149107",
    isin: "CA0641491075",
    quantity: 30000,
    feeRate: 0.22,
    tradeDate: "2026-06-25",
    settlementDate: "2026-06-27",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 72.80,
    dvpPrice: 72.45,
    lastUpdatedUtc: "2026-06-25T07:30:00Z",
    orderExpiryUtc: "2026-06-27T16:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Repay submitted", actor: "aye@hoopp.com", timestamp: "2026-06-25T07:25:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-25T07:30:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0032",
    orderType: "Repay",
    status: "Accepted",
    lenderEntityId: "HOOPP",
    borrowerEntityId: "SEB",
    submittedByEntityId: "SEB",
    lastUpdatedByEntityId: "SEB",
    lastUpdatedByUserId: "lars.bergman@seb.se",
    counterpartyLabel: "HOOPP",
    securityId: "TD CN",
    cusip: "891160509",
    isin: "CA8911605092",
    quantity: 25000,
    feeRate: 0.15,
    tradeDate: "2026-06-24",
    settlementDate: "2026-06-26",
    settlementType: "FOP",
    settlementLocation: "CDS",
    price: 88.50,
    dvpPrice: 88.20,
    lastUpdatedUtc: "2026-06-24T11:00:00Z",
    orderExpiryUtc: "2026-06-24T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Repay submitted by SEB", actor: "lars.bergman@seb.se", timestamp: "2026-06-24T09:00:00Z" },
      { status: "Pending", action: "Awaiting HOOPP response", actor: "System", timestamp: "2026-06-24T09:00:05Z" },
      { status: "Accepted", action: "Accepted by HOOPP", actor: "aye@hoopp.com", timestamp: "2026-06-24T11:00:00Z" },
    ],
  },
  {
    orderId: "ORD-2026-0033",
    orderType: "Repay",
    status: "Failed",
    lenderEntityId: "SEB",
    borrowerEntityId: "HOOPP",
    submittedByEntityId: "HOOPP",
    lastUpdatedByEntityId: "HOOPP",
    lastUpdatedByUserId: "jose.chang@hoopp.com",
    counterpartyLabel: "SEB AB",
    securityId: "ENB CN",
    cusip: "29250N105",
    isin: "CA29250N1050",
    quantity: 10000,
    feeRate: 0.08,
    tradeDate: "2026-06-23",
    settlementDate: "2026-06-25",
    settlementType: "DVP",
    settlementLocation: "CDS",
    price: 55.40,
    dvpPrice: 55.15,
    lastUpdatedUtc: "2026-06-23T16:45:00Z",
    orderExpiryUtc: "2026-06-23T17:00:00Z",
    counterOfferCount: 0,
    allowCounterOffer: false,
    auditTrail: [
      { status: "Submitted", action: "Repay submitted", actor: "jose.chang@hoopp.com", timestamp: "2026-06-23T14:00:00Z" },
      { status: "Pending", action: "Received by counterparty", actor: "System", timestamp: "2026-06-23T14:00:05Z" },
      { status: "Accepted", action: "Accepted by SEB", actor: "anna.kvist@seb.se", timestamp: "2026-06-23T15:30:00Z" },
      { status: "Booking", action: "Auto-booking initiated", actor: "System", timestamp: "2026-06-23T15:30:10Z" },
      { status: "Failed", action: "Settlement failed \u2014 insufficient collateral", actor: "System", timestamp: "2026-06-23T16:45:00Z" },
    ],
    notes: "Settlement failed - insufficient collateral",
  },
];
