// Generated by AI (GitHub Copilot) - 2026-06-24
import { createTheme } from "@mui/material/styles";

/**
 * SFP-matching dark theme — replicates the HOOPP ISG design system colors.
 * Based on @hoopp/isg.theme "livid" palette.
 */
export const sfpDarkTheme = createTheme({
  palette: {
    mode: "dark",
    primary: { main: "#5c9ce6" },
    secondary: { main: "#a78bfa" },
    success: { main: "#4ade80" },
    warning: { main: "#facc15" },
    error: { main: "#f87171" },
    info: { main: "#60a5fa" },
    background: {
      default: "#0f1419",
      paper: "#1a2332",
    },
    text: {
      primary: "#e8eaed",
      secondary: "#9aa0a6",
      disabled: "#5f6368",
    },
    divider: "#2d3748",
  },
  typography: {
    fontFamily: '"Segoe UI", "Roboto", "Helvetica Neue", Arial, sans-serif',
    h4: { fontWeight: 600, fontSize: "1rem", textTransform: "uppercase" },
    h6: { fontWeight: 600 },
  },
  components: {
    MuiAppBar: {
      defaultProps: { elevation: 0 },
      styleOverrides: {
        root: { borderBottom: "1px solid #2d3748" },
      },
    },
    MuiTab: {
      styleOverrides: {
        root: {
          textTransform: "none",
          fontWeight: 500,
          fontSize: "0.875rem",
          minHeight: 42,
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: { fontWeight: 600, fontSize: "0.75rem" },
      },
    },
  },
});

/**
 * SFP light theme — same structure, light palette.
 */
export const sfpLightTheme = createTheme({
  palette: {
    mode: "light",
    primary: { main: "#1a73e8" },
    secondary: { main: "#7c3aed" },
    success: { main: "#16a34a" },
    warning: { main: "#ca8a04" },
    error: { main: "#dc2626" },
    info: { main: "#2563eb" },
    background: {
      default: "#f8fafc",
      paper: "#ffffff",
    },
    text: {
      primary: "#1e293b",
      secondary: "#64748b",
      disabled: "#94a3b8",
    },
    divider: "#e2e8f0",
  },
  typography: {
    fontFamily: '"Segoe UI", "Roboto", "Helvetica Neue", Arial, sans-serif',
    h4: { fontWeight: 600, fontSize: "1rem", textTransform: "uppercase" },
    h6: { fontWeight: 600 },
  },
  components: {
    MuiAppBar: {
      defaultProps: { elevation: 0 },
      styleOverrides: {
        root: { borderBottom: "1px solid #e2e8f0" },
      },
    },
    MuiTab: {
      styleOverrides: {
        root: {
          textTransform: "none",
          fontWeight: 500,
          fontSize: "0.875rem",
          minHeight: 42,
        },
      },
    },
    MuiChip: {
      styleOverrides: {
        root: { fontWeight: 600, fontSize: "0.75rem" },
      },
    },
  },
});

/* Status color map — matches SFP's CSS variable-based status colors */
export const statusColors: Record<string, string> = {
  New: "#a78bfa",           // violet (user is actively filling)
  Draft: "#84cc16",         // lime (new)
  Submitted: "#60a5fa",     // blue
  Pending: "#facc15",       // yellow
  Quoted: "#818cf8",        // indigo
  Countered: "#fb923c",     // orange
  Accepted: "#4ade80",      // green
  Rejected: "#f87171",      // red
  Booking: "#38bdf8",       // sky blue
  Booked: "#22c55e",        // green (darker)
  Settled: "#10b981",       // emerald
  Failed: "#ef4444",        // red (bright)
  Expired: "#6b7280",       // gray
  Cancelled: "#9ca3af",     // gray (lighter)
};

/* Trade type colors — matches SFP Booking page pills (from @hoopp/isg.theme) */
export const tradeTypeColors: Record<string, { bg: string; text: string }> = {
  Borrow: { bg: "#8787bb", text: "#0a0a11" },   // purple8
  Lend: { bg: "#a5a5cc", text: "#0a0a11" },     // purple6
  Recall: { bg: "#93d3cd", text: "#04110f" },    // teal5
  Repay: { bg: "#67c1b8", text: "#04110f" },     // teal7
};
